### ISSUE TITLE
Open Source Cardboard design lab

### ISSUE THREAD

**Issue by Consti10** [googlevr/cardboard#10]
Since you already made cardboard open source, It might be possible to (re-release) the cardboard design lab source code.

**Comment by Consti10** [comment]
I'm working on a integration of cardboard into my open source vertex displacement distortion correction implementation here: [https://github.com/Consti10/RenderingX/tree/master/RenderingXCore/src/main/cpp/GLPrograms/DistortionCorrection](url)
And also will fix the issue described here:
[https://stackoverflow.com/questions/58303389/daydream-gvr-headset-distortion-model](url)

For reference: After looking trough the cardboard source code I don't think the distortion model uses tangential distortion parameters (as defined by brown conrady).

**Comment by Consti10** [comment]
Note: links above are bugged.

**Comment by jballoffet** [comment]
Thanks for requesting the feature. We'll put it in the backlog of features to consider on our roadmap.

**Comment by Consti10** [comment]
Hello everyone, I think I was able to find a way to migrate the de-centering distortion model of cardboard to an Open-Source Vertex displacement distortion correction implementation.
Here is an example screenshot of  [my cardboard fork](https://github.com/Consti10/cardboard) that renders a blue mesh using off-screen render texture and a green mesh on top using VDDC:
![example_vddc](https://user-images.githubusercontent.com/16462285/70716970-ad631480-1ced-11ea-9c8d-d85ceb1b1a1d.png)
It aligns almost perfectly.

**Comment by birdimus** [comment]
Is the request to update CDL?  The source is still available in https://github.com/googlevr/gvr-unity-sdk/tree/v0.9.1/Samples/CardboardDesignLab

I may take a look if there is interest in updating it.

**Comment by Consti10** [comment]
However, you can check out [RenderingX](https://github.com/Consti10/RenderingX) for a working Open source implementation. Feedback welcome !
