### ISSUE TITLE
(Unity) On iOS the widgets are rendered in the wrong location on devices with a notch.

### ISSUE THREAD

**Issue by chaosemer** [googlevr/cardboard#100]
This only affects when the app is built with Unity 2019.3.14f1 and later.
    * This is due to [`Screen.safeArea()`](https://docs.unity3d.com/2019.4/Documentation/ScriptReference/Screen-safeArea.html) not taking the notch into account on iPhone XS, iPhone XR, and iPhone 11.

**Comment by UnityKR** [comment]
Welcome to the new version release.
You did a really good job.

Question.
Is this the same reason that the button disappears intermittently?
(Close Button, Gear Button)
The button is not visible, but it works.

**Comment by UnityKR** [comment]
Does this issue cause the app crash?
If so, please release a new version as soon as possible.

**Comment by chaosemer** [comment]
It is not expected that this would be related to a crash or the buttons disappearing. Perhaps the buttons disappearing is related to #50 ?

For the crash, please look through the existing crash bugs, it may be one of those.

**Comment by UnityKR** [comment]
#50 same Issue.

Thanks.

**Comment by jballoffet** [comment]
A fix for this has just been submitted and it will be included in the next release.

**Comment by naiteon** [comment]
> A fix for this has just been submitted and it will be included in the next release.

Does this also apply for the same problem on Android 10 devices with notch which also have the eye textures rendered wrongly?

**Comment by chaosemer** [comment]
This was fixed in v1.4.0.

**Comment by andrewio** [comment]
Actual for: v1.4.1,  iPhone XS Max, iOS 14.3, OpenGLES3, Unity 2019.4.10
