### ISSUE TITLE
(Unity) Asset Packages/com.google.xr.cardboard/build.date has no meta file, but it's in an immutable folder. The asset will be ignored.

### ISSUE THREAD

**Issue by joker-gizmo** [googlevr/cardboard#101]
build.date has no meta and asset doesn't work because of it
checked on Unity 2019.4.9f1 and 2019.4.0f1

can be fixed by deletion of build.date

**Comment by chaosemer** [comment]
Oops! That was an oversight of our internal build system. I'll do a force-push to remove build.date from cardboard-xr-plugin's history.

**Comment by chaosemer** [comment]
Done.
