### ISSUE TITLE
Cardboard XR iPhone 11 Pixelated...

### ISSUE THREAD

**Issue by UnityKR** [googlevr/cardboard#111]
Question.

on iPhone 11
The screen looks pixelated when viewed with a VR device.

I would appreciate it if you let me know your recommended settings.
thank you..

**Comment by jballoffet** [comment]
Thank you for reporting this. Could you please provide a picture of the device screen that depicts the issue? Please also provide:
- The required steps to expose the issue.
- If the XR Plugin is used, the version of Unity being used.
- The phone being used.
- The viewer’s parameters being used.
- The viewer being used (if it is a standard one).

**Comment by jballoffet** [comment]
Without a repro project, we can not help here. If you are still having this issue, please reopen and point us to a repro project with steps to reproduce.
