### ISSUE TITLE
IOS14 Cardboard view is completely broken

### ISSUE THREAD

**Issue by AerinFloreo** [googlevr/cardboard#118]
On all apps that I can find that use Cardboard in IOS14 (IPhone), the VR view is insanely bugged. The camera swings wildly all over the place.

Here is a video example: https://www.reddit.com/r/youtube/comments/i1nbs0/ios_14_vr_error/, and another here https://www.reddit.com/r/GoogleCardboard/comments/iw04pj/just_upgraded_to_ios_14_now_this_is_what_i_get/

The official Google Cardboard app-store application is broken as soon as you start it. It is also broken on the app I develop for which uses GVR and Unity.

Weirdly, it will temporarily function as expected if you restart your IPhone. The time it takes to break is seemingly random - sometimes it will be broken right away, and sometimes it will work for hours before breaking.

We have tested this on two Iphone8+, and an Iphone11.

Things I have tried:
- Updating to beta IOS14.2 does not fix the issue.
- Rebuilding in XCode 12.2 Beta does not fix the issue
- No errors or warning appear in my local build for our GVR project.

**Comment by JoaoBorks** [comment]
@AerinFloreo did you use the [new plugin](https://github.com/googlevr/cardboard-xr-plugin) or the [deprecated one](https://github.com/googlevr/gvr-unity-sdk)? I'm using the deprecated one, and it reproduces everything you described. Then I built the sample scene from the new plugin on Unity 2019.4.11f1 and it's working normally so far. Tested on iPhone XR and SE.

**Comment by AerinFloreo** [comment]
> @AerinFloreo did you use the [new plugin](https://github.com/googlevr/cardboard-xr-plugin) or the [deprecated one](https://github.com/googlevr/gvr-unity-sdk)? I'm using the deprecated one, and it reproduces **everything** you described. Then I built the sample scene from the new plugin on Unity 2019.4.11f1 and it's working normally so far. Tested on iPhone XR and SE.

We are currently using the deprecated one. However, I imagine the official Google Cardboard app is not using the depreciated one?

**Comment by JoaoBorks** [comment]
> 
> 
> > @AerinFloreo did you use the [new plugin](https://github.com/googlevr/cardboard-xr-plugin) or the [deprecated one](https://github.com/googlevr/gvr-unity-sdk)? I'm using the deprecated one, and it reproduces **everything** you described. Then I built the sample scene from the new plugin on Unity 2019.4.11f1 and it's working normally so far. Tested on iPhone XR and SE.
> 
> We are currently using the deprecated one. However, I imagine the official Google Cardboard app is not using the depreciated one?

The last update to the iOS Google Cardboard app was 4 years ago, so yeah, they are indeed using the deprecated plugin. One thing I noticed is that I can see VR videos on Youtube (that uses cardboard) with no issues as well.

So I guess we'll have to update the plugin then.. We will also have to update our app to Unity 2019.4, since we were sticking to 2018.4 LTS and that version is not supported.

**Comment by AerinFloreo** [comment]
> > > @AerinFloreo did you use the [new plugin](https://github.com/googlevr/cardboard-xr-plugin) or the [deprecated one](https://github.com/googlevr/gvr-unity-sdk)? I'm using the deprecated one, and it reproduces **everything** you described. Then I built the sample scene from the new plugin on Unity 2019.4.11f1 and it's working normally so far. Tested on iPhone XR and SE.
> > 
> > 
> > We are currently using the deprecated one. However, I imagine the official Google Cardboard app is not using the depreciated one?
> 
> The last update to the iOS Google Cardboard app was 4 years ago, so yeah, they are indeed using the deprecated plugin. One thing I noticed is that I can see VR videos on Youtube (that uses cardboard) with no issues as well.
> 
> So I guess we'll have to update the plugin then.. We will also have to update our app to Unity 2019.4, since we were sticking to 2018.4 LTS and that version is not supported.

Wow, we are in the exact situation as you regarding 2018.4 LTS. Yikes, that is quite a bit of work, but thank you very much for this insight! Really appreciate it.

**Comment by AerinFloreo** [comment]
I'm going to close this: GVR is now obsolete, not depreciated, for IOS14.

**Comment by julien-tamade** [comment]
I believe Apple's release of iOS 14.0.1 a few hours ago fixes this issue. Please correct me if I am wrong as I've only tested on my phone.

**Comment by JoaoBorks** [comment]
> 
> 
> I believe Apple's release of iOS 14.0.1 a few hours ago fixes this issue. Please correct me if I am wrong as I've only tested on my phone.

Unfortunately, it does not fix the issue at all. You probably got it working because your device had just restarted. If you wait some time, it will start glitching all over again.

**Comment by julien-tamade** [comment]
@JoaoBorks damn i guess it was wishful thinking. My team just tested after upgrading another phone and it works ok on that one as well. I've been continuing to test on my upgraded phone without issue. Any idea on timeline for issue to start appearing?

**Comment by JoaoBorks** [comment]
> 
> 
> @JoaoBorks damn i guess it was wishful thinking. My team just tested after upgrading another phone and it works ok on that one as well. I've been continuing to test on my upgraded phone without issue. Any idea on timeline for issue to start appearing?

It seems very random.. On a SE it took a few hours while on an XR it took a few minutes. But if you are using the obsolete plugin and the issue did not reproduce after some hours, perhaps we missed something. Are you using Unity 2018.4?

**Comment by julien-tamade** [comment]
> > @JoaoBorks damn i guess it was wishful thinking. My team just tested after upgrading another phone and it works ok on that one as well. I've been continuing to test on my upgraded phone without issue. Any idea on timeline for issue to start appearing?
> 
> It seems very random.. On a SE it took a few hours while on an XR it took a few minutes. But if you are using the obsolete plugin and the issue did not reproduce after some hours, perhaps we missed something. Are you using Unity 2018.4?

I'm using 2018.4.9f1. I have the Unity projected embedded inside a native swift project. I know the issue was definitely happening on iOS14.0.0, but it hasn't happened yet on iOS14.0.1. Will keep testing though. 360 or "magic window" mode was working fine though but the VR was rolling like crazy

**Comment by jotcreative** [comment]
Matterport VR just dropped support for iOS due to this; a tragedy for someone who had planned to give a dozen people a demo on their iPhones tomorrow.

**Comment by reemaalsalem** [comment]
have u found any solution to fix this ? and does the new plugin fix that bug ?

**Comment by johnfriedrich** [comment]
> > > have u found any solution to fix this ? and does the new plugin fix that bug ? **(Continue Spinning View in IPhone device for Virtual Reality)**
> > 
> > 
> > Yes, just use this new plugin
> 
> Which plugin can you send any demo or link.

Documentation can be found here: https://developers.google.com/cardboard/develop
