### ISSUE TITLE
Cardboard is being Initialized but left and right eye not being rendered.

### ISSUE THREAD

**Issue by SamTrudgianMelody** [googlevr/cardboard#119]
Hi I am using Unity Unity 2019.3.15f1 and I am building a cardboard application for both iOS and Android and have an issue where I can initialize the cardboard subsystem using `XRGeneralSettings.Instance.Manager.InitializeLoader();/XRGeneralSettings.Instance.Manager.InitializeLoadSync();`.  can stop cardboard by using `XRGeneralSettings.Instance.Manager.DeinitiaizeLoader();`

**iOS**
This changes the FoV of my camera and makes things really blurry. I can switch between turning cardboard on and off, yet there is no left or right eye rendering (The classic Cardboard UI).
https://puu.sh/GwjYt/e004e029e7.png

**Android**
This cramps the entire camera view into the top left of the screen in landscape mode and afterwards crashes.
https://puu.sh/GwjZk/c7c5437c9e.png

Any guidance is much appreciated. Any information that is needed, I will gladly provide

**Comment by JoaoBorks** [comment]
Make sure to call `XRGeneralSettings.Instance.Manager.StartSubsystems()` after `Initialize` and `XRGeneralSettings.Instance.Manager.StopSubsystems()` before `Deinitialize`. If your view gets distorted after exit VR, try `camera.ResetAspect()` after `Deinitialize`. If you experience crashes, [check this out](https://github.com/googlevr/cardboard/issues/59#issuecomment-702923140)

**Comment by jballoffet** [comment]
This is a duplicate issue, please take a look at #59.
