### ISSUE TITLE
Older versions will be open sourced too?

### ISSUE THREAD

**Issue by yuripourre** [googlevr/cardboard#12]
I am using the CardboardSDK 0.5.1 for a long time now and I have several private apps using it.

There are any plans to release it's code?

**Comment by jballoffet** [comment]
There are no plans to release 0.5.1. The latest SDK comes from the same code base, but with a handful of additional bugfixes and quality improvements.

**Comment by yuripourre** [comment]
Alright, thank you for your answer.
Supposing someone reverse engineered this particular old version from bytecode, do you think that would be an issue if the code becomes public under the same rules as this repository (Google CLA and Apache License)?

**Comment by fredsa** [comment]
@yuripourre I assume you're using the Google VR SDK for Android (https://github.com/googlevr/gvr-android-sdk/). Please consult the README.md and LICENSE files in that repository for the version you're using (in your case 0.5.1), where you'll find a link to the applicable terms of service and/or open source licenses that apply to that the files included in that release.
