### ISSUE TITLE
EXCEPTION/crash in main/CardboardApi::RenderWidgets/CardboardApi::CardboardApiImpl::RenderWidget

### ISSUE THREAD

**Issue by mganesh83** [googlevr/cardboard#120]
I have followed every step in this link: https://developers.google.com/cardboard/develop/unity/quickstart
Only difference is I have set the target API level to 28, since my phone Realme1 (Oppo CPH1859), is at API level 28. 
Unity version: 2020.1.4f1. XR Plugin version: 1.2.0
I have ensured that camera and sdcard permissions are enabled for the app.
I did try it with the latest available API level also (30) and it gives the exact same crash. The screen is blank/black.
Does anybody have a workaround for this issue? Does changing any setting fix this issue?
I am very new to Android and Unity development, so please pardon me if this is something trivial that I am unaware of.

Below is the log from logcat:
-----------------------------

09-26 16:57:35.457 28993 28993 E AndroidRuntime: FATAL EXCEPTION: main
09-26 16:57:35.457 28993 28993 E AndroidRuntime: Process: com.DefaultCompany.a5, PID: 28993
09-26 16:57:35.457 28993 28993 E AndroidRuntime: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-26 16:57:35.457 28993 28993 E AndroidRuntime: Version '2020.1.4f1 (fa717bb873ec)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
09-26 16:57:35.457 28993 28993 E AndroidRuntime: Build fingerprint: 'OPPO/CPH1859/CPH1859:9/PPR1.180610.011/1587903909:user/release-keys'
09-26 16:57:35.457 28993 28993 E AndroidRuntime: Revision: '0'
09-26 16:57:35.457 28993 28993 E AndroidRuntime: ABI: 'arm64'
09-26 16:57:35.457 28993 28993 E AndroidRuntime: Timestamp: 2020-09-26 16:57:34+0530
09-26 16:57:35.457 28993 28993 E AndroidRuntime: pid: 28993, tid: 31590, name: Thread-5  >>> com.DefaultCompany.a5 <<<
09-26 16:57:35.457 28993 28993 E AndroidRuntime: uid: 10284
09-26 16:57:35.457 28993 28993 E AndroidRuntime: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-26 16:57:35.457 28993 28993 E AndroidRuntime:     x0  0000000000000000  x1  0000000000007b66  x2  0000000000000006  x3  0000000000000008
09-26 16:57:35.457 28993 28993 E AndroidRuntime:     x4  fefeff73f992ffd7  x5  fefeff73f992ffd7  x6  fefeff73f992ffd7  x7  7f7f7f7fffff7fff
09-26 16:57:35.457 28993 28993 E AndroidRuntime:     x8  0000000000000083  x9  00000074fa978828  x10 fffffff87ffffbdf  x11 0000000000000001
09-26 16:57:35.457 28993 28993 E AndroidRuntime:     x12 00000074567feb18  x13 ffffffffffffffff  x14 ffffffffff000000  x15 ffffffffffffffff
09-26 16:57:35.457 28993 28993 E AndroidRuntime:     x16 00000074fa9af2b0  x17 00000074fa8ed3d8  x18 00000074567fe2da  x19 0000000000007141
09-26 16:57:35.457 28993 28993 E AndroidRuntime:     x20 0000000000007b66  x21 0000000000000083  x22 0000000000000000  x23 000000745ca0608c
09-26 16:57:35.457 28993 28993 E AndroidRuntime:     x24 0000000000000000  x25 00000074567ff588  x26 00000000000027b3  x27 00000074739f1c10
09-26 16:57:35.457 28993 28993 E AndroidRuntime:     x28 000000745929d50c  x29 00000074567fef40
09-26 16:57:35.457 28993 28993 E AndroidRuntime:     sp  00000074567fef00  lr  00000074fa8e1b90  pc  00000074fa8e1bbc
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 
09-26 16:57:35.457 28993 28993 E AndroidRuntime: backtrace:
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #00 pc 0000000000021bbc  /system/lib64/libc.so (abort+124) (BuildId: 7bb3d32d6929587ccf497e3aaadcca34)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #01 pc 00000000000648a0  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libcardboard_api.so (BuildId: dd90749eb9a668980e1490134d06648632804b11)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #02 pc 00000000000655ec  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libcardboard_api.so (cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams)+552) (BuildId: dd90749eb9a668980e1490134d06648632804b11)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #03 pc 00000000000636f4  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libcardboard_api.so (cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidgets()+164) (BuildId: dd90749eb9a668980e1490134d06648632804b11)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #04 pc 0000000000063640  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libcardboard_api.so (cardboard::unity::CardboardApi::RenderWidgets()+24) (BuildId: dd90749eb9a668980e1490134d06648632804b11)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #05 pc 0000000000067e3c  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libcardboard_api.so (BuildId: dd90749eb9a668980e1490134d06648632804b11)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #06 pc 0000000000067d64  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libcardboard_api.so (BuildId: dd90749eb9a668980e1490134d06648632804b11)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #07 pc 0000000000067d2c  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libcardboard_api.so (BuildId: dd90749eb9a668980e1490134d06648632804b11)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #08 pc 00000000003fc0e8  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libunity.so (BuildId: debaca61687b745e8ea32dce3966ba1c49ede538)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #09 pc 000000000051e194  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libunity.so (BuildId: debaca61687b745e8ea32dce3966ba1c49ede538)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #10 pc 000000000051e9e0  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libunity.so (BuildId: debaca61687b745e8ea32dce3966ba1c49ede538)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #11 pc 0000000000516ca0  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libunity.so (BuildId: debaca61687b745e8ea32dce3966ba1c49ede538)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #12 pc 00000000001d7660  /data/app/com.DefaultCompany.a5-c6RnMxhf7OJCtjflolhWwQ==/lib/arm64/libunity.so (BuildId: debaca61687b745e8ea32dce3966ba1c49ede538)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #13 pc 0000000000084bb4  /system/lib64/libc.so (__pthread_start(void*)+36) (BuildId: 7bb3d32d6929587ccf497e3aaadcca34)
09-26 16:57:35.457 28993 28993 E AndroidRuntime:       #14 pc 00000000000234bc  /system/lib64/libc.so (__start_thread+68) (BuildId: 7bb3d32d6929587ccf497e3aaadcca34)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libc.abort(abort:124)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libcardboard_api.0x648a0(Native Method)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libcardboard_api.cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams)(RenderWidget:552)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libcardboard_api.cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidgets()(RenderWidgets:164)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libcardboard_api.cardboard::unity::CardboardApi::RenderWidgets()(RenderWidgets:24)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libcardboard_api.0x67e3c(Native Method)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libcardboard_api.0x67d64(Native Method)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libcardboard_api.0x67d2c(Native Method)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libunity.0x3fc0e8(Native Method)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libunity.0x51e194(Native Method)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libunity.0x51e9e0(Native Method)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libunity.0x516ca0(Native Method)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libunity.0x1d7660(Native Method)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libc.__pthread_start(void*)(__pthread_start:36)
09-26 16:57:35.457 28993 28993 E AndroidRuntime: 	at libc.__start_thread(__start_thread:68)

**Comment by magiwanders** [comment]
Check if OpenGLES3 is selected instead of OpenGLES2. This was my issue and my problem was identical

**Comment by jballoffet** [comment]
It seems this is a duplicate issue, please take a look at #116.
