### ISSUE TITLE
Help with Reticle Pointer

### ISSUE THREAD

**Issue by julien-tamade** [googlevr/cardboard#121]
Hi, Does anybody know how I can re-use the old reticle pointer? Ideally I'd love to know if anybody has implemented the pointer alternative to interact with gameobjects and UI, but Even if i have to determine enter and exit conditions on my own, it would be really helpful to repurpose the old one to get the expanding and contracting circle. Thanks in advance!

**Comment by JoaoBorks** [comment]
I'm implementing a gaze pointer based on [this](http://talesfromtherift.com/vr-gaze-input/). It's an extension for Unity Event System Input Module, so it works for both UI and game objects (if you use a [Physics Raycaster](https://docs.unity3d.com/2018.1/Documentation/ScriptReference/EventSystems.PhysicsRaycaster.html) and [Event Trigger](https://docs.unity3d.com/2018.3/Documentation/ScriptReference/EventSystems.EventTrigger.html) components)

**Comment by jballoffet** [comment]
This is a duplicate issue, please take a look at #47.
