### ISSUE TITLE
XR cardboard plugin is not working in play mode

### ISSUE THREAD

**Issue by MusemoDeveloper** [googlevr/cardboard#122]
Unity in play mode gives this exception: 
EntryPointNotFoundException: CardboardQrCode_getSavedDeviceParams
Google.XR.Cardboard.Api.HasDeviceParams () (at Library/PackageCache/com.google.xr.cardboard@0d3b490442/Runtime/Api.cs:101)
CardboardStartup.Start () (at Assets/Samples/Google Cardboard XR Plugin for Unity/1.2.0/Hello Cardboard/Scripts/CardboardStartup.cs:39)

I am using: 
Unity 2019.4.11
Cardboard XR plugin, uploaded into the app via  Unity package manager, git
How can I fix that?

**Comment by JoaoBorks** [comment]
@MusemoDeveloper  the cardboard api is not supposed to work inside the Unity Editor, only on standalone builds. You should wrap the api calls inside `#if !UNITY_EDITOR` preprocessor directives.
