### ISSUE TITLE
Carboard XR plugin with OpenGLes 3.0

### ISSUE THREAD

**Issue by dipaw** [googlevr/cardboard#125]
Hello, the Unity build of OpenGLES 3.0 crashes at startup. Do you plan to support opengles 3.0?

**Comment by dletozeun** [comment]
It should help for the crash.

**Comment by dipaw** [comment]
> It should help for the crash.
What should help?

Btw builds with OpenGLES 2.0 works fine,but do not have URP features.

**Comment by jballoffet** [comment]
This is a duplicate issue, please take a look at #40.
