### ISSUE TITLE
iOS 14?

### ISSUE THREAD

**Issue by irgipaulius** [googlevr/cardboard#129]
Is it possible to add support for Apple's Metal Graphics API? Or do we flag this repo as "obsolete" or "Android only"?
If the latter, then I'd like to hear an in-depth thorough reasoning why this cannot be modified to work on iOS devices. Pretty please.

Thanks.

**Comment by julien-tamade** [comment]
Apparently, Metal support is coming.  #11. In February they said later this year, so hopefully soon. Still waiting to get an update on the expected timeline though.

**Comment by jballoffet** [comment]
This is a duplicate issue, please take a look at #11.
