### ISSUE TITLE
Support for Android Studio x86 emulator?

### ISSUE THREAD

**Issue by petr666** [googlevr/cardboard#13]
Hi,
would it be possible to add support for x86 emulator in Android Studio? If I am not mistaken, it should be sufficient to add libprotobuf-lite.a for x86 in order to be able to compile sdk.
Emulating arm is unusable slow, not to mention newest available image is for api 25.

**Comment by jballoffet** [comment]
Thanks for requesting the feature. We'll put it in the backlog of features to consider on our roadmap. Meanwhile, you can try to add it on your own. As you correctly said, the only needed thing to compile the SDK for x86 architectures is to add a libprotobuf-lite built for that specific arch. I encourage you to follow [these](https://developers.google.com/cardboard/develop/c/protobuf) steps, but remember to modify the environment variables to match your requirements.

**Comment by chaosemer** [comment]
In v1.1 we removed the dependency on libprotobuf-lite for Android, we are now using a Java protobuf library. While we haven't tested that this works in the emulator, I see no reason why it would not.

Please reopen this issue if there are still blockers with using Cardboard in the Android emulator.
