### ISSUE TITLE
is not available 6dof?

### ISSUE THREAD

**Issue by mrsions** [googlevr/cardboard#135]
I added to do the latest version of 6dof. But it doesn't work.

`  <uses-feature
    android:name="android.hardware.vr.headtracking"
    android:version="1"
    android:required="true" />`

i try added this. but not work moving position

sdk : https://github.com/googlevr/cardboard-xr-plugin
unity: 2019.4.11

**Comment by jballoffet** [comment]
Cardboard SDK does not support 6DoF and there are currently no plans to support it. However, it may be considered in a future update.

**Comment by jballoffet** [comment]
This is a duplicate issue, please take a look at #7.
