### ISSUE TITLE
CommandInvokationFailure: Gradle build failed. 

### ISSUE THREAD

**Issue by IBelieveICanCode** [googlevr/cardboard#137]
[Environment]
Unity version: Unity 2020.1.7f, 2019.4.11f, 2019.315f
Google Cardboard XR Plugin for Unity: both 1.2.0; 1.1.0

How to get:
I Just followed the [instruction](https://developers.google.com/cardboard/develop/unity/quickstart)
It seems like I checked and completed everything the instruction says but it doesn't help. 
![image](https://user-images.githubusercontent.com/45063550/95304406-3fe03000-088d-11eb-9bba-e7ccb563a7bc.png)

**Comment by JoaoBorks** [comment]
You are not really showing the error with this message. I've discovered by now that this plugin is not compatible with Firebase. If you're using Firebase, you should try to solve compatibility issues by yourself while the official solution is not available. But to get a better debug session, I suggest you to export as a project and then open on Android Studio. Try to build from there instead, as it will give you more meaningful logs.

**Comment by IBelieveICanCode** [comment]
I don't use Firebase. I try to build HelloCardboard scene, which can be imported with plugin
The only thing which narrows things down a bit is this:
![image](https://user-images.githubusercontent.com/45063550/95338762-f0fdbf00-08bb-11eb-93e5-8fc355f88d00.png)

**Comment by jballoffet** [comment]
It seems this is a duplicate issue, please take a look at #80.
