### ISSUE TITLE
"VR Frame for Eyes" is too small!

### ISSUE THREAD

**Issue by andrewio** [googlevr/cardboard#145]
I use Huawei Mate 20x for Unity builds.
Next you can see 2 examples how it is, and how it must be.

**If I use new Cardboard XR Plugin 1.2 then I have small size of "VR Frame"**:
![Google Cardboard XR](https://user-images.githubusercontent.com/5120782/96996880-50550380-1539-11eb-9e07-423fc40d332d.jpeg)

**If I use old Google VR SDK 1.200.1 then I have normal size of "VR Frame"**:
![Google-VR-SDK](https://user-images.githubusercontent.com/5120782/96996938-6ebaff00-1539-11eb-96a0-0c8fee215447.jpeg)

What the issue? 
Why they are different? 
How to fix that? 
Is it bug?

**Comment by JoaoBorks** [comment]
Possible duplicate of #144

**Comment by jballoffet** [comment]
This seems to be a duplicate of issue #100, which is fixed in the next release (1.4.0). I am closing this as a duplicate, however if the next release does not fix this issue, please reopen.
