### ISSUE TITLE
Back button and Settings break after changing the scene in Unity

### ISSUE THREAD

**Issue by myasovik** [googlevr/cardboard#147]
In Unity 2019.4 build for iOS v14

On first scene it works fine but after loading next scene back button and settings become inactive black cubes.

**Comment by JoaoBorks** [comment]
It was supposed to be fixed in [1.3.0](https://github.com/googlevr/cardboard/releases/tag/v1.3.0) according to their release note. The original issue is #50

**Comment by myasovik** [comment]
Hello,
I updated my project in "Unity" with googlevr to 1.3.0. I see that icons now look correct but they are still not responsive. When I click on "settings" nothing happening also when I click "X" nothing happening there is code I expecting to execute:

```
private void Update()
    {

        if (Input.GetKeyDown(KeyCode.Escape))
        {
            SetState(GameState.MENU);
        }
    } 
```

Thank you for the help.

**Comment by JoaoBorks** [comment]
This would work on the old cardboard plugin. On the new one, you need to use:
```csharp
if (Api.IsCloseButtonPressed)
{
    SetState(GameState.MENU);
}
```
Check the Package's [sample](https://github.com/googlevr/cardboard-xr-plugin/blob/f9d253a54b52efa99e2bd45e854f95246e32be23/Samples%7E/hellocardboard-unity/Scripts/CardboardStartup.cs#L55) for instance.

**Comment by myasovik** [comment]
Worked.

Thank you
