### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [googlevr/cardboard#15]
Would you like to [wrap any pointers](https://github.com/googlevr/cardboard/blob/6e91e143b148d7e95cd8bd804062f000cd885818/sdk/distortion_mesh.cc#L20 "Update candidate: DistortionMesh class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by jballoffet** [comment]
Thanks for the feature request. We are cleaning up the code internally by using std::vector. This will be included in the next release. If you would like to create additional changes, please read CONTRIBUTING.md and follow the process. Patches are welcome.

**Comment by chaosemer** [comment]
In v1.1 we cleaned up a bunch of code. If there are further clean ups you'd like to propose, please read CONTRIBUTING.md and submit a patch.

**Comment by elfring** [comment]
Would you like to [reconsider the approach for resizing of vectors](https://github.com/googlevr/cardboard/blob/ec0fff2d7e2d82a6df79952d67e0e6a0bf740531/sdk/distortion_mesh.cc#L24 "Update candidate: DistortionMesh constructor")?
