### ISSUE TITLE
Setting Default Viewer Profile?

### ISSUE THREAD

**Issue by julien-tamade** [googlevr/cardboard#153]
My app is always viewed on the same headset and it doesn't have a barcode to scan. Anybody know if there's a way to set a default profile that will always be used?

Thanks!

**Comment by jballoffet** [comment]
There are two different things that you could do. Option one is to create a QR code for your viewer by using the [Viewer Profile Generator](https://arvr.google.com/cardboard/viewerprofilegenerator/). The other option is to save the device parameters in the source code, similar to what has been done for the Cardboard V1 Viewer. You could use [this class](https://github.com/googlevr/cardboard/blob/master/sdk/device_params/android/java/com/google/cardboard/sdk/deviceparams/CardboardV1DeviceParams.java) as a reference. Then you can change the default values (selected when the QR code activity is skipped) [here](https://github.com/googlevr/cardboard/blob/22983a5bfb6a8f6c78b41e1f44ffb0fe9a1dc64a/sdk/qrcode/android/java/com/google/cardboard/sdk/QrCodeCaptureActivity.java#L218).

**Comment by julien-tamade** [comment]
@jballoffet thanks for the response. Would there be any way to do this from the Unity code? Right now I've removed the barcode scanning from the app because it will just cause more confusion for our users, but ideally I could set the parameters on launch from Unity. Any thoughts?

**Comment by xiesi88** [comment]
> There are two different things that you could do. Option one is to create a QR code for your viewer by using the [Viewer Profile Generator](https://arvr.google.com/cardboard/viewerprofilegenerator/). The other option is to save the device parameters in the source code, similar to what has been done for the Cardboard V1 Viewer. You could use [this class](https://github.com/googlevr/cardboard/blob/master/sdk/device_params/android/java/com/google/cardboard/sdk/deviceparams/CardboardV1DeviceParams.java) as a reference. Then you can change the default values (selected when the QR code activity is skipped) [here](https://github.com/googlevr/cardboard/blob/22983a5bfb6a8f6c78b41e1f44ffb0fe9a1dc64a/sdk/qrcode/android/java/com/google/cardboard/sdk/QrCodeCaptureActivity.java#L218).

Hope to provide an easy way to modify these parameters, it is best to set them directly in Unity.

**Comment by Git327017278** [comment]
How to call  QR code activity is skipped @ @jballoffet

**Comment by julien-tamade** [comment]
@jballoffet  Wonder if this can be added as a feature request for the Unity SDK?

**Comment by jballoffet** [comment]
A solution for this issue has been asked in #198 and addressed in #224 for Android platforms. We are in the process of migrating those changes internally. In case you would like to add the implementation for iOS platforms and/or the addition of the Unity API [here](https://github.com/googlevr/cardboard-xr-plugin/blob/38cb0047bbc1b5a56c113164c9915fe2d22bc664/Runtime/Api.cs#L192), please read CONTRIBUTING.md and follow the process. Patches are welcome. I'm closing this issue in favor of #198.
