### ISSUE TITLE
How do I recenter the VR viewer?

### ISSUE THREAD

**Issue by myasovik** [googlevr/cardboard#154]
Hello,

I am using Unity 2019.4 and building app for iOS. 
The problem I am having is when I start app and holding the phone vertical, I am getting my menu shifted to the right. So player see empty back ground and to see main menu he/she need to turn the head 45-90 deg.

When I hold phone horizontal and start the app do not have such problem, menu is strait in front of me.

So I need to reset or recenter view that it looked like was set the camera in the beginning when app get started vertical.

**Comment by Mandelbrow** [comment]
Can only agree. The API needs a cheep method to recenter.
I have the camera inside the player mesh, so when the player is rotated, the vr tracking has to be reset on each frame.

**Comment by jballoffet** [comment]
This is a duplicate issue, please take a look at #63.
