### ISSUE TITLE
Getting head rotation on IOS

### ISSUE THREAD

**Issue by whizzkid** [googlevr/cardboard#155]
using unity 2019.4.14f1
I'm trying to get a menu to be consistently displayed at the players feet, facing the same way as the player, by rotating the menu to the same y angle.

This works fine in editor (windows and mac) and on android, but on IOS when I try to display the the camera's rotation from script (or any of its parents) is always 0,0,0 while the stereo view and headtracking seem to work normally.  

using the xr interaction toolkit I also added an XRcontroller to the camera and use that to interact with stuff.   that also doesnt work on ios.

so something is working differently on ios than anywhere else...

how do i get the head's rotation consistently on all devices? is it on another object or something?

**Comment by jballoffet** [comment]
In order to allow us to reproduce this issue, could you please provide a link to a simple Unity project where this issue is shown? Please also provide:
- The required steps to expose the issue.
- The phone and OS version being used.
- The viewer’s parameters being used.

**Comment by whizzkid** [comment]
This can b

**Comment by jballoffet** [comment]
Thanks for the update.
