### ISSUE TITLE
How to emulate the camera motion in the scene?

### ISSUE THREAD

**Issue by yuhany1024** [googlevr/cardboard#156]
I'm trying to run the HelloVR demo following the guideline(https://developers.google.com/cardboard/develop/unity/quickstart). Everything works well, but can I emulate the camera motion in the scene? For previous version, I can control the camera in this way:
Alt+Move Mouse = Change Yaw/pitch; Ctrl + Move Mouse = Change Roll.

How to make a split view like this:
![](http://mammothinteractive.com/wp-content/uploads/2017/03/86.png)

I'm using unity2020 and MacBook. I'd like to build an iOS game.

**Comment by JoaoBorks** [comment]
Currently, there's no official solution for that. I've made a pull request to add the camera simulation input, but not the stereo rendering. You can check it here: googlevr/cardboard-xr-plugin#13
