### ISSUE TITLE
Error when running the helloVR demo: cannot start the process because a file name has not been provided.

### ISSUE THREAD

**Issue by yuhany1024** [googlevr/cardboard#157]
I'm trying the helloVR demo following the instruction(https://developers.google.com/vr/develop/unity/get-started-ios). I'm using an oder version of Cardboard SDK (GVR SDK for Unity v1.200.1, https://github.com/googlevr/gvr-unity-sdk/releases). I'm on MacBook and using unity2019.4.9.f.

Every time when I run the helloVR demo, it throws away an error:
**InvalidOperationException: Cannot start process because a file name has not been provided.
System.Diagnostics.Process.Start () (at <14e3453b740b4bd690e8d4e5a013a715>:0)
(wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
Gvr.Internal.InstantPreview.RunCommand (System.String fileName, System.String arguments, System.String& output, System.String& errors) (at Assets/GoogleVR/Scripts/InstantPreview/Internal/InstantPreview.cs:797)
Gvr.Internal.InstantPreview+<>c__DisplayClass68_1.<Start>b__1 () (at Assets/GoogleVR/Scripts/InstantPreview/Internal/InstantPreview.cs:301)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.ExecutionContext.Run (System.Threading.E**

I have also tried other version of unity (2018-2020) and other version of the SDK. The same error occurs. There's no error when running another demo of the SDK(KeyboardDemo). How to solve it?

**Comment by dletozeun** [comment]
Hi,

The older Google VR SDK no longer work with Unity and especially on iOS 14.x where the gyroscope sensor output is not handled correctly and the view rotates randomly very fast. So you'll have to upgrade to the [new SDK](https://developers.google.com/cardboard/develop/ios/quickstart).

![image](https://user-images.githubusercontent.com/5956242/98914592-27d18100-24c9-11eb-953e-33507130c4e2.png)

**Comment by whizzkid** [comment]
and the older sdk included the UIWebView component, which is no longer allowed on the Appstore. so even if it did work, you couldn't publish your work.

**Comment by yuhany1024** [comment]
> Hi,
> 
> The older Google VR SDK no longer work with Unity and especially on iOS 14.x where the gyroscope sensor output is not handled correctly and the view rotates randomly very fast. So you'll have to upgrade to the [new SDK](https://developers.google.com/cardboard/develop/ios/quickstart).
> 
> ![image](https://user-images.githubusercontent.com/5956242/98914592-27d18100-24c9-11eb-953e-33507130c4e2.png)

But I want to render different contents to two eyes. I heard that the latest version doesn’t support it.(using two cameras targeted to different eyes and culling mask to filter the contents.) Is there any solution to it or any other SDK can achieve it?

**Comment by dletozeun** [comment]
Yes AFAIK, the old trick using two cameras doesn't work anymore. However if you can do it through shaders, look at unity_StereoEyeIndex built-in variable there:

https://docs.unity3d.com/Manual/SinglePassStereoRendering.html

**Comment by jballoffet** [comment]
As mentioned above, GVR and the old Cardboard SDK have been deprecated and this new version should be used instead. About rendering different contents to each eye, please see #146.
