### ISSUE TITLE
Graddle error: Resouce not found. @style/Theme.AppCompat.NoActionBar.

### ISSUE THREAD

**Issue by maxBetaVR** [googlevr/cardboard#158]

**Comment by maxBetaVR** [comment]
Graddle error: Resouce not found. @style/Theme.AppCompat.NoActionBar.

**Comment by maxBetaVR** [comment]
help wanted.

When building I get graddle error: Resouce not found. Its looking for @style/Theme.AppCompat.NoActionBar. I have tried various android SDK versions. ALso tried building before importing this package and its fine until I import the package again.

Thanks

**Comment by maxBetaVR** [comment]
Help requested.

When building I get graddle error: Resouce not found. Its looking for @style/Theme.AppCompat.NoActionBar. I have tried various android SDK versions. ALso tried building before importing this package and its fine until I import the package again.

Thanks
.

**Comment by JoaoBorks** [comment]
This is probably because you didn't [add the dependencies](https://developers.google.com/cardboard/develop/unity/quickstart#publishing_settings) to the custom gradle template.

**Comment by maxBetaVR** [comment]
Many thank JoaBorks,

I seemed to miss that part of the instructions, for no reason other than my carelessness. 

While I'm past that build error the build still fails on:

CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Unity/Hub/Editor/2019.4.9f1/Editor/Data/PlaybackEngines/AndroidPlayer\OpenJDK\bin\java.exe -classpath "C:\Program Files\Unity\Hub\Editor\2019.4.9f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-5.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleDebug"

both Java and gradle-launcher-5.1.1 are in the right places.

Anyway thanks for getting me over the 1st hurdle.

David
.
