### ISSUE TITLE
[Bug] Not fullscreen on iPhone 12

### ISSUE THREAD

**Issue by AnhPham** [googlevr/cardboard#159]
I am using this Cardboard XR Plugin for Unity
https://github.com/googlevr/cardboard-xr-plugin

It works well on almost iPhone except iPhone 12. It looks not fullscreen.
![124838014_284848476175971_212715124449588353_n](https://user-images.githubusercontent.com/1193578/99039300-b1f91280-25b9-11eb-90e8-648e03ef9c1d.jpg)

Please help. Thank you!

**Comment by dletozeun** [comment]
Hi, 

Take a look at #144, it will be fixed in the next release and there is even a quick fix provided if you can't wait.

**Comment by AnhPham** [comment]
> Hi,
> 
> Take a look at #144, it will be fixed in the next release and there is even a quick fix provided if you can't wait.

@dletozeun Thank you very much!!!

**Comment by jballoffet** [comment]
As @dletozeun pointed out, this is a duplicate issue, please take a look at #144.
