### ISSUE TITLE
Small docs edit - Help on getting to the Gradle tab

### ISSUE THREAD

**Issue by irwinwilliams** [googlevr/cardboard#16]
I'm not familiar with Android Studio. I got the Unity SDK to produce a demo of the cardboard app but saw the guidance on your docs saying AS is the more up-to-date place for this stuff.
It took me a minute to figure out the steps in the quickstart:
2. In Android Studio, select Open an existing Android Studio Project, then select the directory where the Cardboard SDK and the HelloCardboard demo app were cloned into.
3. To assemble the Cardboard SDK, double-click the assemble option in the Gradle tab.

So, I realized that the project file explorer was not in fact the Gradle tab and I had to google it what that was. Helpfully, you can access it on windows with "CTRL+SHIFT+A".  
Thus, could you add just that note just after the statement in Step 3? 
Something like, 

2. In Android Studio, select Open an existing Android Studio Project, then select the directory where the Cardboard SDK and the HelloCardboard demo app were cloned into.
3. To assemble the Cardboard SDK, double-click the assemble option in the Gradle tab (open with CTRL+SHIFT+A).

**Comment by jballoffet** [comment]
Thank you for reporting this. We’ll review the documentation and improve this step to make it easier to follow.

**Comment by chaosemer** [comment]
This was fixed in the past, but we forgot to mark this issue as closed. :)
