### ISSUE TITLE
Build errors when compiling the SDK target on iOS with Release configuration

### ISSUE THREAD

**Issue by kafumanto** [googlevr/cardboard#166]
Hi,

the `sdk.xcodeproj` project file is missing an include directory in the Release configuration, causing compile errors when building for shipping. Patch attached.

[cardboard-ios-release.patch.txt](https://github.com/googlevr/cardboard/files/5592025/cardboard-ios-release.patch.txt)

**Comment by jballoffet** [comment]
Thank you for reporting this issue. I confirm I'm able to repro it locally. It has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it.

**Comment by jballoffet** [comment]
A fix for this has been submitted and it will be included in v1.5.0 (the fix missed the v1.4.0 branch cut).

**Comment by chaosemer** [comment]
This was fixed in v1.5.0.
