### ISSUE TITLE
Issues with daydream v2 headset

### ISSUE THREAD

**Issue by Consti10** [googlevr/cardboard#17]
Hello,
I have tested the distortion values reported by gvr (google vr, deprecated) with this test application [code](https://github.com/Consti10/RenderingX/blob/master/RenderingXExample/src/main/cpp/example2/example_distortion.h)
![example_distortion_vertex_displacement](https://user-images.githubusercontent.com/16462285/73460295-8c778100-4378-11ea-8a3c-4bfef7563ee7.png)

They seem to fit the cardboard undistortion model exactly except for one headset - the daydream view 2017.
![Screenshot_2020-01-30-16-02-11](https://user-images.githubusercontent.com/16462285/73461282-2c81da00-437a-11ea-8206-c9155da290b6.jpg)

On further investigation I noticed that the reported k1,k2 values for the distortion are different than what other headset(s) use or just completely wrong.
v1: `0.385F,0.593F` and
v2:  `0.4331F,-0.0856F`

Note that the second polynomial factor of the 2017 headset is negative, and just in general this undistortion makes no sense.

Any ideas ?

**Comment by Consti10** [comment]
Note that for VDDC I have to use a inverse polynomial that obviously won't always fit- but for the viewport occlusion ( in the picture you can not only see the vignette of gvr, but also the occlusion mesh I created to simulate the vignette of gvr in cardboard) I use the polynomialDistortion.inverse() and it still doesn't produce a output that makes sense.

**Comment by jballoffet** [comment]
@Consti10 Below you will find the distortion coefficients for Daydream Viewers V1 and V2. Keep in mind that Daydream V2 has three distortion coefficients instead of just two.

- Daydream Viewers V1: ```0.385f, 0.593f```
- Daydream Viewers V2: ```0.4331f, -0.0856f, 1.4535f```

**Comment by Consti10** [comment]
Thanks,
I dropped anything that was more than 2 values. This fixed the problem.
