### ISSUE TITLE
Cardboard-XR-Recenter issue

### ISSUE THREAD

**Issue by Angelium-hamza** [googlevr/cardboard#176]
hello amazing people I am facing an issue regarding the Cardboard Recenter issue.
i am using XRInputSubsystem.TryRecenter for recentering but it always returns false. and Cardboard camera is not recentered.
i am using https://developers.google.com/cardboard/develop/unity/quickstart SDK.
thanks in advance.

**Comment by jballoffet** [comment]
This is a duplicate issue, please take a look at #63.
