### ISSUE TITLE
Google Cardboard doesn't import on Windows Unity Project

### ISSUE THREAD

**Issue by AudacityChild1** [googlevr/cardboard#179]
I have tried the Https URL and it gives me this error each and everytime on Windows does ANYONE know how to fix this PLEASE!! I'm very desperate, I can't find any help on this besides to add the Https URL and to have Opengles2 enabled which I already have...

Here's my error...
Cannot perform upm operation: Unable to add package [https://github.com/googlevr/cardboard.git]:
  No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub [NotFound].See console for more details
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

Error adding package: https://github.com/googlevr/cardboard.git.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by AudacityChild1** [comment]
Please any help would help.

**Comment by Treecrotch** [comment]
Hi. Take a look at post #4 here. I posted some info on getting git to work, and also instructions how to use it without git.

https://forum.unity.com/threads/google-carboard-vr.1021009/#post-6622186

**Comment by whizzkid** [comment]
A tip for the future,   read the error messages you get..

This one actually tells you what to do, namely:  Please install Git on your system then restart Unity and Unity Hub

So, to install GIT, go here:  [https://git-scm.com/download/win](https://git-scm.com/download/win)

click on "click here to download manually"

run the file you downloaded and install git.

restart unity

try installing the cardboard package again.

**Comment by CreaProjects** [comment]
I had the same issue, you have to add a new variable named "PATH" with a path to your Git "bin" folder:

![image](https://user-images.githubusercontent.com/71306904/102604747-eca81a80-4124-11eb-92d9-ab95755e4370.png)

**Comment by jballoffet** [comment]
As @whizzkid pointed out, git installation is required in order to add the Cardboard XR Plugin via the GitHub repository (as mentioned in the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart#set_up_your_development_environment). There you'll also find a link to Unity's documentation about git support.
