### ISSUE TITLE
Contribution and state of the project

### ISSUE THREAD

**Issue by jnroesch** [googlevr/cardboard#18]
Hello everyone :)

I am patiently waiting for the Unity SDK and while waiting I came up with a few questions.

This project is said to be open source however the contribution guidelines state that PRs are not accepted. So how exactly is the community supposed to contribute to the project when google itself cannot guarantee continuous development?

What is the current state of the project? I have read in some other issues that metal (iOS) for example does not work and will "hopefully" be fixed later this year. So what is the sdk currently capable of and what is still missing in comparison to the currently used version by unity? When is the unity sdk supposed to be released and will it also be open source? With Unity dropping cardboard support in Unity 2019 and Unity 2018 support coming to a close in a year the information out there about the cardboard open source project are not enough for any company to make any well-informed decisions regarding mobile VR. Also with apple having deprecated OpenGL for a long time and possibly removing it with their new phone generation in fall it is hard to justify waiting for the release of the SDK when it does not even support such major platforms correctly.

Our company currently relies heavily on cardboard, therefore getting as much information as possible on this topic is essential to us. 

Thanks for clarifying in advance :)

**Comment by fredsa** [comment]
Hi @jnroesch 

Apologies for the confusing text in`CONTRIBUTING.md`. We'll update that text to clarify that while we don't use GitHub's pull request process and tools, we are able to to review the contents of pull requests and patches, as long as the requirements currently documented in `CONTRIBUTING.md` are met.


- The best place to track status for the new Unity SDK, or be notified once it comes out is probably to watch / star issue #8.
- To track progress on Metal support, please watch / star issue #11
