### ISSUE TITLE
Cardboard XR is laggy compared to Cardboard SDK

### ISSUE THREAD

**Issue by StaplesDev** [googlevr/cardboard#180]
I have upgraded my project to have the Cardboard XR plugin instead of the Cardboard SKD to fix the error happening with IOS 14 having the cardboard view flip around the screen. 

The issue I am having on unity 2019.3 is the frame rate is worse than the cardboard sdk when you are in the cardboard view and moving the screen around it is very choppy. Is there any way to add in a smoother movement to not cause this issue. (Using tracked pose driver as the cardboard view would not work without it) 

When tracking the performance of the app, everything is in the green and the phone is not being overloaded.

**Comment by Treecrotch** [comment]
I am also facing this problem. Testing on a pixel 4 XL, hellocardboard unity scene. I filed an issue here:
https://github.com/googlevr/cardboard/issues/173

The framerate is high but something is off with head rotation, its choppy, not smooth, inconsistent . When I use this same device with the "cardboard" app downloaded from google play, its good and smooth with no issue.

Also note, if you are getting **extreme** chop, it could be this
_project settings > player > resolution and presentation.
uncheck optimize frame pacing._

**Comment by jballoffet** [comment]
This is a duplicate issue, please take a look at #164.
