### ISSUE TITLE
Can XR Cardboard run in embedded native iOS project?

### ISSUE THREAD

**Issue by CryoCodex** [googlevr/cardboard#184]
Hello let me explain the situation so far

I have a native iOS project that uses Firebase (and hence uses Protobuf), when I try to compile it with this XR Cardboard plugin after the integration process to the Native App I find this message:

**com.google.xr.cardboard/Runtime/iOS/cardboard_api.a(repeated_field.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64**

I notice that there is a sdk folder (which am assuming can be compiled with bitcode enabled = yes) and so I did, and replaced the .a file given by unity with this new one that should have bitcode enabled = yes, but I still keep getting the same message mentioned above. Bear in mind this is what I've tried so far from the info I could gather, if someone can point me in the right direction or if what I'm trying to do is not viable please do let me know. Thanks so much in advance, and if I missed some information that may be useful do let me know so I can check I can provide it.

**Note: I mentioned that uses Firebase (and hence uses Protobuf) that's because when I compile the whole native project target without bitcode the app does compile but it will get an exception on launch with the stack trace giving Protobuf entries, guessing it may be because there is some kind of conflict between these?**

**Comment by jballoffet** [comment]
As explained in #84, Cardboard SDK's Xcode project is currently configured to not enable bitcode support. Nevertheless, as you did you could rebuild it with that option enabled, but bear in mind that you will also need to rebuild the [protobuf prebuilt binary](https://github.com/googlevr/cardboard/blob/master/third_party/libprotobuf/ios/lib/libprotobuf-lite.a) first, which wasn't originally built with bitcode support enabled. [Here](https://developers.google.com/cardboard/develop/ios/protobuf) you will find the instructions to build it. I'm closing this issue as a duplicate, please reach out to us in #84 in case it is required.
