### ISSUE TITLE
HelloCardboard Monoscopic only on iOS 14

### ISSUE THREAD

**Issue by echolocat** [googlevr/cardboard#189]
I built the Sample HelloCardboard scene in Unity using the 1.4.1 Google Cardboard XR Plugin for Unity and am loading it on my iPhone 12 Pro running iOS 14. I scan the Google Cardboard Viewer QR code and yet when the project runs it only appears in monoscopic (see image below), not stereoscopic. Suggestions? Do I need to change something in the Project or Build Settings? In the Project Settings > XR Plugin Management I have "Initialize XR on Startup" checked and also checked the Google Cardboard plugin for Unity. Many hours into this - would appreciate help!

@chaosemer ? I saw this issued mentioned on another post but it was never directly addressed.

![hello](https://user-images.githubusercontent.com/32625118/103620614-ac98b400-4ee8-11eb-946b-855ba6af11e2.png)

**Comment by jballoffet** [comment]
Thanks for reaching out to us. About your question, yes, some settings need to be properly set in the Project Settings. Please take a close look at the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart) and follow the steps described there. If the issue persists once all steps have been properly executed, please reopen this issue with a repro project and the steps required to reproduce it.
