### ISSUE TITLE
How to Simulate Movement like in old GVR Package?

### ISSUE THREAD

**Issue by Helaly96** [googlevr/cardboard#192]
I am trying to replicate an old project I made using GVR Package with the new plugin system, but unlike the previous version of the package you cannot use (Alt+Mouse) or (Ctrl+Mouse) to emulate the head movement, so you are stuck in your place, is there any way to emulate this in the new system?

**Comment by jballoffet** [comment]
This is a duplicate issue, please take a look at #51.
