### ISSUE TITLE
QR code scanning on Android may fail without error message while Google Play services is being updated or internet connection is unreliable.

### ISSUE THREAD

**Issue by chaosemer** [googlevr/cardboard#2]

**Comment by jballoffet** [comment]
This issue has been already fixed:
- In case there's an issue with the required dependencies, this log is shown: https://github.com/googlevr/cardboard/blob/09681a1577266f70f5e1d37b6c4a029ca7c5427d/sdk/qrcode/android/java/com/google/cardboard/sdk/QrCodeCaptureActivity.java#L179-L180
- In case there's a connection error, this log is shown: https://github.com/googlevr/cardboard/blob/09681a1577266f70f5e1d37b6c4a029ca7c5427d/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/QrCodeContentProcessor.java#L94-L95
