### ISSUE TITLE
Screen size is too small

### ISSUE THREAD

**Issue by xiesi88** [googlevr/cardboard#201]
Hope to help us solve this problem as soon as possible. We are developing a children's popular science VR APP. The screen size of binocular rendering is too small in the entire mobile phone screen, and the edges of the black mask frame are not blurred.
![f7881a105c13ccf5fa53de0e9c737e7b](https://user-images.githubusercontent.com/27883184/106859949-b63b5480-66fe-11eb-8a71-ad890474c51a.jpg)
![9088f915db27f8532a6f81b16938c64b](https://user-images.githubusercontent.com/27883184/106859965-b9cedb80-66fe-11eb-8d76-51bd67f97ff9.jpg)
![52ea0fc654c540a9aa33dd1069f6aa3a](https://user-images.githubusercontent.com/27883184/106859986-c05d5300-66fe-11eb-8673-5bdb588702b8.jpg)

We have customized a VR cardboard. We hope to set the size of the binocular screen and the degree of distortion through the code, so that the binocular rendering screen size can be more suitable for our VR cardboard. Because we do not have the ability to develop binocular rendering, our VR app is developed based on Carborad sdk.

![image](https://user-images.githubusercontent.com/27883184/106860183-fa2e5980-66fe-11eb-9857-3952aba1910d.png)
![image](https://user-images.githubusercontent.com/27883184/106860260-13370a80-66ff-11eb-8a56-e8beb50d2fd4.png)

**Comment by jballoffet** [comment]
About the SetViewerProfile API, please see #198.

About the blurred borders, that's a GVR feature that currently the Cardboard SDK does not support. We'll put it in the backlog of features to consider on our roadmap.

About the screen size issue, could you please provide more information about it, such as:
- What does each picture represent? Under what conditions/settings were they obtained?
- Is this taking place on Android or iOS phones?
- Is Unity being used?
- The phone and OS version being used.
