### ISSUE TITLE
decrease the viewport 

### ISSUE THREAD

**Issue by aniltirola** [googlevr/cardboard#202]
I am playing with `hellocardboard-ios`. Everything works. Now I try to find out where I can decrease the viewport. Or in other words. The camera should see a little bit more of the room. So as the user zoomed out. I played with the value `kZNear` in the file `HelloCardboardRenderer.mm`. But this gets me to unpredictable results. Maybe this is the wrong approach. Please help with this.

**Comment by jballoffet** [comment]
Sorry for the long delay here. In a VR experience, changing values such as the FOV (but not changing the viewer's lenses accordingly) would end up distorting the scene. If you want the camera to show a little bit more of the room, you should either move the camera position backwards, or move the world forwards. The kZNear and kZFar values are not related to the FOV but to the z-axis clipping planes (see Perspective projection section in https://learnopengl.com/Getting-started/Coordinate-Systems). HTH.
