### ISSUE TITLE
Questions About Version 1.5.0

### ISSUE THREAD

**Issue by neptali-duque** [googlevr/cardboard#205]
Hello, I see that the roapmap does have plans to support the Metal API in the version 1.5.0, and well using OpenGL is deprecated for iOS specially if you have Native + Unity apps, is there a possibility to know like an estimate of when this release is going to happen? Thanks so much in advance

**Comment by jballoffet** [comment]
About Metal integration, please see https://github.com/googlevr/cardboard/issues/11#issuecomment-762316402. Once we have finished adding Metal support to the Cardboard SDK and XR Plugin (we have already finished integrating it to iOS natively and we are currently working on the Unity integration via the XR Plugin), we’ll be able to release v.1.5.0. I’d recommend you star or watch issue #11 to be notified when the Metal integration is completed.
