### ISSUE TITLE
VR on Google Cardboard (android) using Unity  not working correctly

### ISSUE THREAD

**Issue by vedantmodi1** [googlevr/cardboard#206]
I am new to Unity and VR. I am trying to create a very basic VR application using Unity and my Android phone via Google Cardboard.

I followed the steps given here, https://developers.google.com/cardboard/develop/unity/quickstart, https://docs.unity3d.com/Manual/android-sdksetup.html and installed android studio sdk on my laptop.

Here is my scene, hierarchy, and build settings. No error while building. The refrigerator model is my game object, and as you can see the camera points at the refrigerator, at least that's what I inferred.

![Setup2](https://user-images.githubusercontent.com/44337913/107110627-6def7400-686f-11eb-82b1-e160899f4c29.jpg)
![Setup1](https://user-images.githubusercontent.com/44337913/107110629-6f20a100-686f-11eb-9043-4ebd7e4703c3.jpg)
![Output3](https://user-images.githubusercontent.com/44337913/107110630-6fb93780-686f-11eb-9905-16e6de0d9605.jpg)
![Output2](https://user-images.githubusercontent.com/44337913/107110631-7051ce00-686f-11eb-92aa-b52a6e9649a7.jpg)
![Output-1](https://user-images.githubusercontent.com/44337913/107110632-7051ce00-686f-11eb-82ab-58fc2457f374.jpg)
![Setup3](https://user-images.githubusercontent.com/44337913/107110633-70ea6480-686f-11eb-9bd4-ad5b27bc3fb3.jpg)

On my phone, I only see the green background when facing down, as I turn my phone up it changes into white. Nothing else is seen.
Please help me I'm really stuck and don't know what to do or where I've gone wrong.

**Comment by hyenachi** [comment]
If you use Graphics APIs opengles2, change it to opengles3.
Project Settings -> Player -> Other Settings->Graphics APIs->OpenGLES3

**Comment by vedantmodi1** [comment]
It is already using OpenGLES3 and vulcan

**Comment by Treecrotch** [comment]
> It is already using OpenGLES3 and vulcan

Is OpenGLES3 at the top of the list?

If vulkan is at the top of the list, it will use vulkan first if the phone supports it, but i believe cardboard does not support it. So openGLES3 must be at the top of the list and/or remove vulkan.

**Comment by vedantmodi1** [comment]
worked! thank you so much, slight problem though... 
This is the view when i look upwards at a 45-60 degree angle. The camera seems to be on the floor as I cannot view the floor texture.
![image](https://user-images.githubusercontent.com/44337913/107676812-920fe280-6cbf-11eb-98fb-4c87b99732cf.png)

But here my camera faces downwards as it probably should on my phone too.
![image](https://user-images.githubusercontent.com/44337913/107676912-abb12a00-6cbf-11eb-94a4-26121b3fd4c5.png)

**Comment by agalbachicar** [comment]
Consider removing Vulkan. Unity will set as default rendering API the top most option and Cardboard XR Plugin does not support it yet. Keeping either OpenGL ES3 or ES2 should work.

**Comment by vedantmodi1** [comment]
Deleted vulcan... That doesnt seem to solve the camera view issue

**Comment by Treecrotch** [comment]
The camera should be at the same place as your editor game view. 

If its on the floor... I mean could you have an object w gravity on or something? ...that should do the same when playing in editor though. 

To troubleshoot that i would move the camera, hit play on editor, and export and retest on phone. 

Put in a script to move the camera in and Update() method and see where you end up w that movement, stuff like that.
