### ISSUE TITLE
The close and gear buttons in VR not working

### ISSUE THREAD

**Issue by jacobotrf** [googlevr/cardboard#214]
Hello

The close (Api.IsCloseButtonPressed) and gear (Api.IsGearButtonPressed) buttons not responde to click. I haven't done anything change in the proyect exct the steps describes here (https://developers.google.com/cardboard/develop/unity/quickstart). Only I have dowloaded the XR Plugin Managent (v3.2.16) and the this package (Google Cardboard XR v1.4.1)

![image](https://user-images.githubusercontent.com/32145048/108387395-d5150d00-720d-11eb-8805-0eeb21751d78.png)

This is the code include in the script VrModeController.cs

    public void Update()
    {
        if (_isVrModeEnabled)
        {
            if (Api.IsCloseButtonPressed)
            {
                ExitVR();
            }

            if (Api.IsGearButtonPressed)
            {
                Api.ScanDeviceParams();
            }

            Api.UpdateScreenParams();
        }
        else
        {
            // TODO(b/171727815): Add a button to switch to VR mode.
            if (_isScreenTouched)
            {
                EnterVR();
            }
        }
    }

**Comment by jacobotrf** [comment]
It possible that it would be an error with Unity 2019.4. I have done the same thing with Unity 2020.2 and it works

**Comment by jballoffet** [comment]
Thanks for reporting this issue. Unfortunately, we cannot reproduce it locally on our devices (both buttons work well on an Android device using Unity 2019.4.19, 2020.1.17 and 2020.2.2) so in order to help you, I'd need the following items:

- Are you using an Android or an iOS device?
- Does this also take place with the Hello Cardboard sample scene?
- Android/iOS version being used.
- Phone being used.

It would also be really helpful if you could provide a repro project where the issue is shown and the steps required to reproduce it.

**Comment by jacobotrf** [comment]
Thanks for your answer. In this moment I have solved the problem. I think that the problem is the Unity version. But I will respond your question because maybe it could be useful to the other person

**- Are you using an Android or an iOS device?**
Android
**- Does this also take place with the Hello Cardboard sample scene?**
Yes
**- Android/iOS version being used.**
Android 7.1
**- Phone being used.**
BQ Aquarius V (spanish phone)

Thanks

**Comment by jballoffet** [comment]
Thanks for the information provided, please reopen this issue if the problem comes up again.

**Comment by CadsoftBrianW** [comment]
I have the same issue if I use the new input system for Unity:
![image](https://user-images.githubusercontent.com/29311562/111480169-0fd46d00-8708-11eb-8474-3176497ebcf9.png)
