### ISSUE TITLE
Standard Unity default shader is not rendered when vr mode is enabled

### ISSUE THREAD

**Issue by CreaProjects** [googlevr/cardboard#217]
**The issue is only on iOS.**

Repro:
In VrMode scene, add a 3D sphere. Just let the default Unity shader (Standard Shader) on it.

Without the VR mode enabled, the sphere is rendered correctly:
![image](https://user-images.githubusercontent.com/71306904/108819078-a5258b00-75ba-11eb-97d7-5b3f06725571.png)

With VR enabled, the sphere disapears.
![image](https://user-images.githubusercontent.com/71306904/108819114-b1a9e380-75ba-11eb-9332-02891fdb29e4.png)

**Comment by jballoffet** [comment]
Thanks for reaching out to us @CreaProjects! Sorry for the long delay. Could you please share a simple repro project with us where the issue is shown and the steps required to reproduce it? It would be really helpful for us in order to reproduce, debug and check the fix. Thanks!

**Comment by jballoffet** [comment]
Without a repro project, we can not help here. If you are still having this issue, please reopen and point us to a repro project with steps to reproduce. Thanks!
