### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by azizi436** [googlevr/cardboard#22]
Hi 
I was trying to run this project on my phone but it gave me an error like below :

![error](https://user-images.githubusercontent.com/36598338/76522054-2acc2b80-647b-11ea-89a1-1f5683a03935.png)

what should i do ? could you help me

**Comment by FractionalRadix** [comment]
> 
> 
> Hi
> I was trying to run this project on my phone but it gave me an error like below :
> 
> ![error](https://user-images.githubusercontent.com/36598338/76522054-2acc2b80-647b-11ea-89a1-1f5683a03935.png)
> 
> what should i do ? could you help me

I had this problem too. In my case I had not run the "Assemble" task in the Gradle view. 
You should use the "Assemble" task under “:sdk”, not the one under “:hellocardboard-android".
Hope this helps.

**Comment by jballoffet** [comment]
@azizi436 , as @FractionalRadix said, you need to generate the SDK's AAR first (which includes native libraries among other stuff), before building the sample app. Please take a look to #9.

**Comment by azizi436** [comment]
@jballoffet @FractionalRadix Thank you for your help ,it worked ...now i want to play a video from Api into card board , How can I do this ?

**Comment by StrikeNP** [comment]
I see OP got their issue resolved, but I wanted to add that I ran into numerous issues trying to run the hello cardboard app on Windows and spend almost a week debugging it. Once I tried running it on Linux everything worked without a hitched, so my suspicion is that it is more friendly towards Linux based development environments.

**Comment by chaosemer** [comment]
In v1.1 we removed the need for libprotobuf on Android and are instead using a Java protobuf library. This makes building on Windows much easier.

I personally verified that I was able to build v1.1's sample app on Windows in Android Studio, if you have further issues here, let me know!
