### ISSUE TITLE
Build problems IOS -  OpenGLES2/3 (unity 2020.2)

### ISSUE THREAD

**Issue by k-tests** [googlevr/cardboard#223]
Hi, 
Any ideas why I cannot build in ios? 
this is what I get: 
(this is a build from the 2020.2 version of unity where there is no OpenGLES2/3 options anymore...)
Thanks in advance for any help.... 

Showing Recent Messages
: "_glUniform2f", referenced from:

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glGenBuffers", referenced from:

: Cardboard::rendering::OpenGlEs2DistortionRenderer::OpenGlEs2DistortionRenderer() in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::OpenGlEs3DistortionRenderer() in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glBlendFunc", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: "_glViewport", referenced from:

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glScissor", referenced from:

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glBlendEquation", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: "_glClear", referenced from:

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glBindBuffer", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::SetMesh(CardboardMesh const*, CardboardEye) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::SetMesh(CardboardMesh const*, CardboardEye) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: ...

: "_glBindFramebuffer", referenced from:

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glEnableVertexAttribArray", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glVertexAttribPointer", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glEnable", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glUseProgram", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glActiveTexture", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glClearColor", referenced from:

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glDrawArrays", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: "_glDeleteRenderbuffers", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::DestroyGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)

: "_glCreateProgram", referenced from:

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glLinkProgram", referenced from:

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glCompileShader", referenced from:

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glAttachShader", referenced from:

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glDetachShader", referenced from:

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glDeleteShader", referenced from:

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glBindTexture", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glBindRenderbuffer", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)

: "_glDrawElements", referenced from:

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glGenTextures", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)

: "_glGetShaderInfoLog", referenced from:

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glTexParameteri", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)

: "_glRenderbufferStorage", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)

: "_glDeleteTextures", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::DestroyGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)

: "_glBufferData", referenced from:

: Cardboard::rendering::OpenGlEs2DistortionRenderer::SetMesh(CardboardMesh const*, CardboardEye) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::SetMesh(CardboardMesh const*, CardboardEye) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glUniform1i", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: "_glGetProgramiv", referenced from:

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glCreateShader", referenced from:

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glTexImage2D", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)

: "_glGenRenderbuffers", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)

: "_glGetShaderiv", referenced from:

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glGetUniformLocation", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::GlSetup() in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::OpenGlEs2DistortionRenderer() in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::OpenGlEs3DistortionRenderer() in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glDisable", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glGetError", referenced from:

: (anonymous namespace)::CheckGlError(char const*, int) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::CheckGlError(char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::CheckGlError(char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glShaderSource", referenced from:

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(cardboard_xr_unity.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)

: (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glGetAttribLocation", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::GlSetup() in cardboard_api.a(cardboard_xr_unity.o)

: Cardboard::rendering::OpenGlEs2DistortionRenderer::OpenGlEs2DistortionRenderer() in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::OpenGlEs3DistortionRenderer() in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glDeleteBuffers", referenced from:

: Cardboard::rendering::OpenGlEs2DistortionRenderer::~OpenGlEs2DistortionRenderer() in cardboard_api.a(opengl_es2_distortion_renderer.o)

: Cardboard::rendering::OpenGlEs3DistortionRenderer::~OpenGlEs3DistortionRenderer() in cardboard_api.a(opengl_es3_distortion_renderer.o)

: "_glBindVertexArray", referenced from:

: Cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)

: "_glGetIntegerv", referenced from:

: Cardboard::unity::CardboardApi::GetBoundFramebuffer() in cardboard_api.a(cardboard_xr_unity.o)

: Symbol(s) not found for architecture arm64

: Linker command failed with exit code 1 (use -v to see invocation)

**Comment by jballoffet** [comment]
Building for iOS platforms using Unity 2020.x is currently blocked by the Metal integration (as you said, OpenGL support is removed from that Unity version on). We are currently working on it (we have already finished integrating it to iOS natively and we are now solving some issues in the Unity integration via the XR Plugin). Once we have finished the integration and we have kicked off the QA process, I'll reply on issue #11 to communicate this. I’d recommend you star or watch it to be notified. Thanks for reaching out!
