### ISSUE TITLE
Issue with google XR with interactions

### ISSUE THREAD

**Issue by vaishakhcherukat** [googlevr/cardboard#227]
We are building a VR-based application which renders 360 videos and allows users to interact with them through gaze-enabled UI. This was developed using the Google VR SDK.
The original Google VR SDK was causing issues on iOS v14.0 and above, like the content started spinning in VR mode. To resolve the issues, we migrated our application to Google XR SDK as suggested here - https://developers.google.com/vr/develop/unity/get-started-android . The migration was difficult, but we managed to even have UI interactivity working on our end. But rendering issues for the VR popped up. Please find an attached screenshot, along with a sample of how it should actually look like. Our application has two separate orientation modes, initially the UI is in portrait mode, but on moving into VR, it is changed into landscape mode. Also, VR doesn't seem to work properly, unless it's set for 'Initialize XR on Startup' under XR plugin management  in Unity.

![half-screen](https://user-images.githubusercontent.com/17946290/111426053-0e13a500-871a-11eb-9959-ef1a9c295001.jpg)
![normal](https://user-images.githubusercontent.com/17946290/111426057-0f44d200-871a-11eb-9464-0831cc167b84.jpg)

Unity Version : 2019.4.16f1
Targeted platforms: Android and iOS

Do we need any specific settings for the camera when changing from 2D mode to VR mode? Is there any specific setting to enable stereoscopic rendering for such an XR setup? Is the UI setup in any way responsible for such a behavior?

**Comment by jeff-rey-unity** [comment]
#168 states it's a timing issue with the screen.orientation and the initialization of vr.  If you haven't already see if waiting a frame after you change the orientation, then switching to vr fixes the problem.

**Comment by amjadalth9** [comment]
Did you solved this problem? And how?

**Comment by jballoffet** [comment]
Thanks for reaching out to us, @vaishakhcherukat! Sorry for the delay here.

As @jeff-rey-unity pointed out, this seems to be the same issue as it was in #168. Please try the solution posted by the developer in such ticket and in case it does't work for you please reach out to us again by reopening this ticket and providing a simple repro project where the issue is depicted and the steps required to reproduce it.
