### ISSUE TITLE
Attempting to get Magic Window working

### ISSUE THREAD

**Issue by CadsoftBrianW** [googlevr/cardboard#229]
Hi all!,

Sorry if this is a duplicate and I thank you for your time.

I am trying to get magic window working for panoramas on our application. For this mode the user doesn't need a headset and simply pans the phone around to view the panorama. I only need the gyro data from the XR input subsystem to accomplish this and I have got it working with the following:

` 
    private static IEnumerator turn_on_xr_for_input_only(Action action)
    {

        Debug.Log("Turning on HeadTracking...");
        yield return turn_vr_device_on(null);

        var loader = XRGeneralSettings.Instance.Manager.activeLoader;
        if (loader != null)
        {
            var display = loader.GetLoadedSubsystem<XRDisplaySubsystem>();

            if (display.running)
            {
                display.Stop();
                display.Destroy();

                if (action != null)
                {
                    action();
                }
            }
        }
    }
private static IEnumerator turn_vr_device_on(Action doafter)
    {

        yield return null;
        Debug.Log("Initializing XR...");
        yield return XRGeneralSettings.Instance.Manager.InitializeLoader();
        Debug.Log("XR initialized.");

        if (XRGeneralSettings.Instance.Manager.activeLoader == null)
        {
            Debug.LogError("Initializing XR Failed.");
        }
        else
        {
            Debug.Log("Starting XR...");
            XRGeneralSettings.Instance.Manager.StartSubsystems();
            Debug.Log("XR Started.");

        }
        yield return null;

        if (Api.HasNewDeviceParams())
        {
            Api.ReloadDeviceParams();
        }

        if (doafter != null)
        {
            doafter();
        }
    }`

**The Problem:** 
I am unable to deinitialize the loader without throwing an exception. I believe the issue is due to destroying the display system. I was unable to get my scene working by only stopping the display subsystem.

The exception when I try to deinitialize:

`: ArgumentNullException: Value cannot be null.
03-18 14:39:56.412 11340 11362 E Unity   : Parameter name: _unity_self
03-18 14:39:56.412 11340 11362 E Unity   :   at (wrapper managed-to-native) UnityEngine.IntegratedSubsystem.Stop(UnityEngine.IntegratedSubsystem)
03-18 14:39:56.412 11340 11362 E Unity   :   at UnityEngine.XR.Management.XRLoaderHelper.StopSubsystem[T] () [0x00015] e\com.unity.xr.management@4.0.1\Runtime\XRLoaderHelper.cs:68
03-18 14:39:56.412 11340 11362 E Unity   :   at Google.XR.Cardboard.XRLoader.Stop () [0x00001] in b\Runtime\XRLoader.cs:111
03-18 14:39:56.412 11340 11362 E Unity   :   at UnityEngine.XR.Management.XRManagerSettings.StopSubsystems () [0x0002d]he\com.unity.xr.management@4.0.1\Runtime\XRManagerSettings.cs:425
03-18 14:39:56.412 11340 11362 E Unity   :   at UnityEngine.XR.Management.XRManagerSettings.DeinitializeLoader () `

**Comment by CadsoftBrianW** [comment]
I was able to get magic window working with this:

   
        Debug.Log("Initializing XR...");
        yield return XRGeneralSettings.Instance.Manager.InitializeLoader();

        if (XRGeneralSettings.Instance.Manager.activeLoader == null)
        {
            Debug.LogError("Initializing XR Failed.");
        }  

        var loader = XRGeneralSettings.Instance.Manager.activeLoader;
        if (loader != null)
        {
            var input = loader.GetLoadedSubsystem<XRInputSubsystem>();
            input.Start();
        }

Also I had to render my camera manually inside update: 

        Quaternion rotation;

        TryGetCenterEyeRotation(out rotation);

        vr_camera.transform.localRotation = rotation;

        vr_camera.Render();

Hopefully this helps someone.

**Comment by jballoffet** [comment]
Thanks @CadsoftBrianW for writing down all the resolution details! What you did is correct, in case stereo rendering isn't required, only the input subsystem can be loaded. I'm closing this issue as it is solved now.
