### ISSUE TITLE
Head Tracking with Daydream's module

### ISSUE THREAD

**Issue by hyenachi** [googlevr/cardboard#232]
When I set Daydream in XRSetting GoogleVR, head tracking was very good.
Is there any way to apply only Posion head tracking part of Daydream in cardboard xr plugin SDK?

**Comment by jballoffet** [comment]
Thanks for reaching out to us and sorry for the long delay here.

About your question, GVR and the old Cardboard SDK have been deprecated and this new version should be used instead. Furthermore, Unity's XR Settings option has also been deprecated and it is removed from Unity 2020.1 onwards.
