### ISSUE TITLE
Drop in frame rate.

### ISSUE THREAD

**Issue by dipaw** [googlevr/cardboard#234]
XR Plugin, 
Unity 2020.3.0f1

The frame rate gradually drops to 40. Recovered when minimizing and then expanding the application.
![](https://i.gyazo.com/e816266b7b11de446f358ce7230f8600.png)
When the camera is turned towards the sky, a stable 60 but gradually drops when viewing objects.
Here are the profiler stats.
[profiler stats for cardboard scene .zip](https://github.com/googlevr/cardboard/files/6201457/profiler.stats.for.cardboard.scene.zip)
Perhaps you have an idea?
looks like a sync problem.

**Comment by synthercat** [comment]
It sounds perfectly normal. Shouldn't a mobile phone render nothing (the sky) faster than actual 3d objects?

**Comment by dipaw** [comment]
> It sounds perfectly normal. Shouldn't a mobile phone render nothing (the sky) faster than actual 3d objects?

Yes, this situation works as it should.
But there is a randomly 20-frame drop or up when the application is minimized. This is pretty abnormal.

**Comment by jballoffet** [comment]
Thanks for reaching out to us! Sorry for the long delay here. Could you please provide more information about the issue, such as:
- Does the issue take place with the sample app, Hello Cardboard?
- Is this taking place on Android or iOS phones?
- The phone and OS version being used.
- The steps required to reproduce the issue.
In case it does not take place in Hello Cardboard sample scene, a repro project would be very helpful as well. Thanks!

**Comment by dipaw** [comment]
> Thanks for reaching out to us! Sorry for the long delay here. Could you please provide more information about the issue, such as:
> 
> * Does the issue take place with the sample scene, Hello Cardboard?
> * Is this taking place on Android or iOS phones?
> * The phone and OS version being used.
> * The steps required to reproduce the issue.
> 
> In case it does not take place in the Hello Cardboard sample scene, a repro project would be very helpful as well. Thanks!

Never mind. Unfortunately, this is common throttling that is inevitable on the target device.

**Comment by jballoffet** [comment]
No worries! Thanks for replying.
