### ISSUE TITLE
When v1.5 will be released?

### ISSUE THREAD

**Issue by mmortall** [googlevr/cardboard#246]
Hello. Our team is waiting for Metal support for Google Cardboard. It was promised to be implemented in v.1.5.
Could you clarify when this version will be released? Thanks

**Comment by xiesi88** [comment]
My team is also waiting for version 1.5. We have developed a children's VR product. We need the support of a new version.

**Comment by neptali-duque** [comment]
We're also waiting for this version since the Metal support is critical for our project that was already working until it stopped working on iOS 14 devices due to the old GVR SDK.

**Comment by jballoffet** [comment]
A new release of the Cardboard SDK (including Metal support on iOS) is nearing completion and is currently working through the QA process. If all goes as planned, we hope to be able to ship the release soon.

Thank you for your excitement and your continued patience.

**Comment by xiesi88** [comment]
> A new release of the Cardboard SDK (including Metal support on iOS) is nearing completion and is currently working through the QA process. If all goes as planned, we hope to be able to ship the release soon.
> 
> Thank you for your excitement and your continued patience.

We really can't wait for a moment. Our product will be released soon. We need the support of the new version very much. Thank you for your efforts.

**Comment by chaosemer** [comment]
v1.5.0 is now out.
