### ISSUE TITLE
Xcode Build Crash - unity 2020.3.1

### ISSUE THREAD

**Issue by juandapark** [googlevr/cardboard#249]
Hello 
Currently i cannot select OpenGLES3 on unity 2020.3.1, the app is not building on xcode, please see errors below, thanks.

Undefined symbols for architecture arm64:
  "_glUniform2f", referenced from:
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glGenBuffers", referenced from:
      cardboard::rendering::OpenGlEs2DistortionRenderer::OpenGlEs2DistortionRenderer() in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::OpenGlEs3DistortionRenderer() in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glBlendFunc", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
  "_glViewport", referenced from:
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glScissor", referenced from:
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glBlendEquation", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
  "_glClear", referenced from:
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glBindBuffer", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::SetMesh(CardboardMesh const*, CardboardEye) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::SetMesh(CardboardMesh const*, CardboardEye) in cardboard_api.a(opengl_es3_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
      ...
  "_glBindFramebuffer", referenced from:
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glEnableVertexAttribArray", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glVertexAttribPointer", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glEnable", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glUseProgram", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glActiveTexture", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glClearColor", referenced from:
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glDrawArrays", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
  "_glDeleteRenderbuffers", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::DestroyGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)
  "_glCreateProgram", referenced from:
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glLinkProgram", referenced from:
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glCompileShader", referenced from:
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glAttachShader", referenced from:
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glDetachShader", referenced from:
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glDeleteShader", referenced from:
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glBindTexture", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glBindRenderbuffer", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)
  "_glDrawElements", referenced from:
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderDistortionMesh(CardboardEyeTextureDescription const*, CardboardEye) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glGenTextures", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)
  "_glGetShaderInfoLog", referenced from:
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glTexParameteri", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)
  "_glRenderbufferStorage", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)
  "_glDeleteTextures", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::DestroyGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)
  "_glBufferData", referenced from:
      cardboard::rendering::OpenGlEs2DistortionRenderer::SetMesh(CardboardMesh const*, CardboardEye) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::SetMesh(CardboardMesh const*, CardboardEye) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glUniform1i", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
  "_glGetProgramiv", referenced from:
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::CreateProgram(char const*, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glCreateShader", referenced from:
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glTexImage2D", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)
  "_glGenRenderbuffers", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::CreateGlRenderTexture(cardboard::unity::CardboardApi::CardboardApiImpl::GlRenderTexture*) in cardboard_api.a(cardboard_xr_unity.o)
  "_glGetShaderiv", referenced from:
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glGetUniformLocation", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::GlSetup() in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::OpenGlEs2DistortionRenderer() in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::OpenGlEs3DistortionRenderer() in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glDisable", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::RenderEyeToDisplay(int, int, int, int, int, CardboardEyeTextureDescription const*, CardboardEyeTextureDescription const*) const in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glGetError", referenced from:
      (anonymous namespace)::CheckGlError(char const*, int) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::CheckGlError(char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::CheckGlError(char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glShaderSource", referenced from:
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(cardboard_xr_unity.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es2_distortion_renderer.o)
      (anonymous namespace)::LoadShader(unsigned int, char const*) in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glGetAttribLocation", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::GlSetup() in cardboard_api.a(cardboard_xr_unity.o)
      cardboard::rendering::OpenGlEs2DistortionRenderer::OpenGlEs2DistortionRenderer() in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::OpenGlEs3DistortionRenderer() in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glDeleteBuffers", referenced from:
      cardboard::rendering::OpenGlEs2DistortionRenderer::~OpenGlEs2DistortionRenderer() in cardboard_api.a(opengl_es2_distortion_renderer.o)
      cardboard::rendering::OpenGlEs3DistortionRenderer::~OpenGlEs3DistortionRenderer() in cardboard_api.a(opengl_es3_distortion_renderer.o)
  "_glBindVertexArray", referenced from:
      cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams) in cardboard_api.a(cardboard_xr_unity.o)
  "_glGetIntegerv", referenced from:
      cardboard::unity::CardboardApi::GetBoundFramebuffer() in cardboard_api.a(cardboard_xr_unity.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jballoffet** [comment]
Sorry for the delay here. As you pointed out, given that OpenGL isn't available from Unity 2020.2 onwards, the Xcode project fails to build. We have included the fix for this in the next release (v1.5.0, to be released soon), and it consists on adding the OpenGL framework dependency to the [iOS library](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Runtime/iOS/cardboard_api.a).

This can be performed in two different ways:
- By selecting them on the Unity UI: click on the library (once imported you'll find it in Packages/com.google.xr.cardboard/Runtime/iOS/cardboard_api.a) and then select OpenGLES and GLKit in `Framework dependencies` in the inspector.
- Add them manually to the [meta file](https://github.com/googlevr/cardboard-xr-plugin/blob/38cb0047bbc1b5a56c113164c9915fe2d22bc664/Runtime/iOS/cardboard_api.a.meta#L77):
```
FrameworkDependencies: OpenGLES;GLKit;
```
As said above, this dependencies will be set in the next release of the Cardboard SDK.

**Comment by chaosemer** [comment]
This was fixed in v1.5.0.
