### ISSUE TITLE
Eye textures rendered in a wrong location when the app is launched for the first time

### ISSUE THREAD

**Issue by jballoffet** [googlevr/cardboard#253]
When in VR mode in Unity, the eyes may be rendered in the wrong location when the app is launched for the first time. Minimizing the app and maximizing it again fixes the issue.

**Comment by synthercat** [comment]
I am trying to understand the severity of this issue. What does "the next time" mean? 1. The first time after the phone boots or 2. The first time ever? Because if it's the second I'll just create a playerprefs to mark the first time it runs and just quit the app so that the user re-opens it!

**Comment by jballoffet** [comment]
@synthercat, we were able to detect this issue sometimes when the app is launched. Minimizing it and maximizing it again solves the issue. If the is closed (not minimized) and launched again, the issue may appear again.

**Comment by jballoffet** [comment]
A fix for this has been submitted and it will be included in v1.7.0. Thanks for reaching out!

**Comment by Layfully** [comment]
Great ! Thank you 👍 🥇

**Comment by sammorris-fss** [comment]
Hi! Would it be possible to get a preview of this fix (or an ETA on 1.7.0)? We're trying to demonstrate something to a client and we've got an issue where the app will have the eye positions entirely messed up if Android is in portrait mode before the app starts. Not ideal given most people don't have landscape launchers.

**Comment by jballoffet** [comment]
A new release of the Cardboard SDK is nearing completion and is currently working through the release process. If all goes as planned, we hope to be able to ship the release soon.

@sammorris-fss About the fix, just add a call to `ReloadDeviceParams()` right below [this](https://github.com/googlevr/cardboard-xr-plugin/blob/48e5eafae7d60bf65b5be9435a70b7234a474062/Runtime/Api.cs#L219) line (within the if body).

**Comment by chaosemer** [comment]
This was fixed in v1.7.0.

**Comment by sammorris-fss** [comment]
Thank you very much @jballoffet @chaosemer!
