### ISSUE TITLE
Can't build Cardboard SDK sample

### ISSUE THREAD

**Issue by shanu-jha** [googlevr/cardboard#26]
I am simply following the Quickstart for Android NDK to compile the app.
Haven't changed a thing in the project itself.

I have the latest ndk, sdk, gradle, android studio, etc.

I am trying to run the app and am running into this issue

[Here is the build log](https://gist.github.com/shanu-jha/e0aed1ba5350771a459f2be65e900ef9)

The ERROR during assemble in grade:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':hellocardboard-android:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process C:\Users\Shanu\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build E:\Projects\Android\testing\cardboard\hellocardboard-android\.externalNativeBuild\cmake\debug\arm64-v8a --target cardboard_jni}
  
  ninja: error: '../../../../libraries/jni/arm64-v8a/libcardboard_api.so', needed by '../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libcardboard_jni.so', missing and no known rule to make it


```
The ERROR during running the app:
```
Build command failed.
Error while executing process C:\Users\Shanu\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build E:\Projects\Android\testing\cardboard\hellocardboard-android\.externalNativeBuild\cmake\debug\arm64-v8a --target cardboard_jni}

ninja: error: '../../../../libraries/jni/arm64-v8a/libcardboard_api.so', needed by '../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libcardboard_jni.so', missing and no known rule to make it
```

What is the issue and how can I fix it?

**Comment by shanu-jha** [comment]
I 've also put a similar question on stack, but seems no one has answered : (
[link to the question on stack](https://stackoverflow.com/questions/61008108/how-to-fix-ndk-build-error-for-hellocardboard-sample)

**Comment by FractionalRadix** [comment]
FWIW I had a similar issue. In my case, I had not built the SDK. 
The sample app tells you to click the  "assemble" option in the Gradle tab. You should click the "assemble" option under ":sdk", **not** the one under ":hellocardboard-android".

Hope this helps!

**Comment by shanu-jha** [comment]
10/10 would recommend adding this info in the documentation.

Thanks @FractionalRadix , you are a good man.

> Under Gradle, click the "assemble" option under ":sdk", not the one under ":hellocardboard-android".

**Comment by jballoffet** [comment]
Thank you for reporting this. We’ll review the documentation and improve this step to make it easier to follow.

**Comment by wangyendt** [comment]
![image](https://user-images.githubusercontent.com/18455758/177682172-f084c9cc-8624-4060-8447-d14bebbe8f59.png)

I am wondering why I am missing "assemble" option?

**Comment by wangyendt** [comment]
This is an auto-sent e-mail. 
 
I am sorry that currently I could not reply your e-mail. I will reply you as soon as possible.

**Comment by KimMingyeol** [comment]
> ![image](https://user-images.githubusercontent.com/18455758/177682172-f084c9cc-8624-4060-8447-d14bebbe8f59.png)
> 
> I am wondering why I am missing "assemble" option?

The following way worked for me.

1. Double click "Task list not built..." to show Gradle Settings window (or, just click "spanner icon > Gradle Settings...")

   ![1](https://user-images.githubusercontent.com/68853120/185358819-20eb72fa-7bdc-477a-bc7e-299f1b650e61.png)

2. On "Experimental" tab, uncheck the option "Do not build Gradle task list during Gradle sync", and then "apply"
   
   ![2](https://user-images.githubusercontent.com/68853120/185359400-3882836c-49a1-4d11-8065-fbaad5003fe4.png)

3. Back to the Gradle window, right click "cardboard", and click "Reload Gradle Project"

   ![3](https://user-images.githubusercontent.com/68853120/185360657-4a500391-a06c-403a-aff6-9c22254dd36c.png)

4. After reloading, Tasks folders appear and you can find "assemble" at "cardboard/sdk/Tasks/build"

   ![4](https://user-images.githubusercontent.com/68853120/185360774-272bf8ea-fe25-46b2-a3e8-7d0b437d046d.png)

**Comment by PowerhouseG** [comment]
For those of us with newer versions of Android Studio. Enable "Configure all Gradle tasks during Gradle Sync".
![image](https://github.com/googlevr/cardboard/assets/31847113/a25ca4c8-0f8b-43d3-8397-74f47c051a3b)

**Comment by wangyendt** [comment]
This is an auto-sent e-mail. 
 
I am sorry that currently I could not reply your e-mail. I will reply you as soon as possible.
