### ISSUE TITLE
Turn off split screen while keeping movement

### ISSUE THREAD

**Issue by convalise** [googlevr/cardboard#263]
Hello. Is it possible to turn off just the split/stereo rendering while keeping the camera movement/rotation?

The only option I found out so far is to turn off the XR entirely, as shown in the VrModeController on the Hello Cardboard demo ( which, by the way, causes bug #186 ).

How can this be achieved?

I'm using the current Unity plugin (https://github.com/googlevr/cardboard-xr-plugin).

EDIT: Forgot to say that, apparently, the old cardboard Unity plugin had this feature. The problem is how to achieve this with the current version which uses the Unity XR management.

**Comment by jballoffet** [comment]
Thanks for reaching out to us. In case your app only requires head tracking input, you can modify the XR Plugin source code to only initialize the XR Input Subsystem (see https://github.com/googlevr/cardboard-xr-plugin/blob/bca15f76c8940f5fa126eae023d4a92695c86d9b/Runtime/XRLoader.cs#L81). See also #229 for another way to achieve this. Hope this helps.

**Comment by convalise** [comment]
@jballoffet I was able to succeed with the links you provided, thank you.

**Comment by prakyath-07** [comment]
Hi @jballoffet , can we switch between split screen and single screen in runtime?

**Comment by jballoffet** [comment]
You should be able to do it, yes. I suggest you check the [VrMode scene](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Samples~/hellocardboard-unity/Scenes/VrMode.unity) and the corresponding [controller](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Samples~/hellocardboard-unity/Scenes/VrMode.unity) from the sample project.

**Comment by prakyath-07** [comment]
Thanks for the quick reply.

I should be able look around in both single and split screen. Is that possible? If yes, could you please explain the steps to be followed?
