### ISSUE TITLE
Google Cardboard - 360 Viewer with the real world North Pole

### ISSUE THREAD

**Issue by NexTrom** [googlevr/cardboard#264]
Hi,

I need to use GoogleCardboard for an 360 Viewer Experience.
To realize my 360 viewer, I put a camera inside a sphere with a panoramic.

My problem, when i play the apk, my sphere is align in same position of my camera. No matter the position where i play the apk, when i start, i look always the same view.

But i need that my sphere has locked in the North Pole in real world, when i play the apk, to align automaticaly the sphere with my panoramic and the real environment. Like this, no matter the position where i play the apk, my start view will be different, and align with the real world.

I tried to use "Compass.magneticHeading", maybe of the bad way but it didn't work. Currently i'm blocked.

If someone can help me ?

I hope that my explains was clear...

Thank in advance :)

**Comment by Mandelbrow** [comment]
Hi,
Is your Camera parented to the sphere? 
Doesn't that make it also turn when the sphere is rotated towards the north pole, making you not notice the turn?

**Comment by NexTrom** [comment]
Hi,

No my camera is detached of my sphere
i search a script or other way to lock my sphere when the game initialized

**Comment by Mandelbrow** [comment]
How about using some Debug.Log, or a canvas in front of the camera to display what angles _Compass.magneticHeading_ is outputting? And go from there to figure out a method to align the sphere/scene to the world space, and recenter the cardboard camera i the true direction too.

**Comment by Layfully** [comment]
It's not possible with Compass magneticHeading / trueHeading because they only work when the phone is put parallel to the ground. It's probably possible with compass.rawVector but you need to be good at math behind vectors and quaternions.

**Comment by Mandelbrow** [comment]
@Layfully Isn't the compass sensor three axis? Just use the right one depending on how the phone is held?

**Comment by Layfully** [comment]
I don't know I tried to implement it myself but failed. I found math to calculate it, but then again it only worked when phone was parallel to the ground. Here's the paper where some guy explains how he did it https://upcommons.upc.edu/bitstream/handle/2099.1/19709/memoria.pdf. Check out section 6.5 and code in the annex. If you figure out how to make it work no matter the phone orientation please let me know. You can start by creating Arrow which points to the magnetic north pole and when you are sure it works the rest should be easy to figure out.

**Comment by Mandelbrow** [comment]
Perhaps it better to access the gps then to determine the current direction of the phone?

**Comment by NexTrom** [comment]
Hi, i resolved my problem, look the script. 
The last part, isn't necessary, it was just to see the degrees ^^

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System;
using TMPro;

public class CompassController : MonoBehaviour
{
    public GameObject cam;
    //public TextMeshProUGUI headingText;

    void Start()
    {
        cam = Camera.main.gameObject;
        Input.location.Start();
        StartCoroutine(InitializeCompass());
        Input.compass.enabled = true;
    }

    IEnumerator InitializeCompass()
    {
        yield return new WaitForSeconds(0.1f);

        Quaternion cameraRotation = Quaternion.Euler(0, cam.transform.rotation.eulerAngles.y, 0);
        Quaternion compass = Quaternion.Euler(0, -Input.compass.trueHeading, 0);
        Quaternion north = Quaternion.Euler(0, cameraRotation.eulerAngles.y + compass.eulerAngles.y - 140, 0);
        transform.rotation = north;

    }

    private static string DegreesToCardinalDetailed(double degrees)
    {
        string[] caridnals = { "N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW", "N" };
        return caridnals[(int)Math.Round(((double)degrees * 10 % 3600) / 225)];
    }
}
```

This script is on my sphere and when i start, the sphere is locked on the north pole 😄

**Comment by Layfully** [comment]
Great, the issue has been resolved you can close it :)
