### ISSUE TITLE
There is no stereo rendering effect in version 1.5

### ISSUE THREAD

**Issue by xiesi88** [googlevr/cardboard#265]
There is no stereo rendering effect in version 1.5.Hope it can be resolved as soon as possible. Our products are waiting to be launched.
![IMG_4101](https://user-images.githubusercontent.com/27883184/118464321-4db73700-b733-11eb-9b2c-2606ed84ad1b.PNG)

**Comment by jballoffet** [comment]
Thanks for reaching out to us. I'm closing this issue as it is a duplicate of #259.
