### ISSUE TITLE
1.5.0 black screen on iOS.

### ISSUE THREAD

**Issue by m-Chinese-Solution-Limited** [googlevr/cardboard#271]
Unity version: unity 20.19.4.21.
I imported 1.5.0 in my unity project and build the hello cardboard scene to my iOS device and turns out black screen.
I am using metal.
The left X button works fine as it will close the app when clicked.
![59546AF6-EC9A-4D36-A49A-032289AE214E](https://user-images.githubusercontent.com/66660263/120423453-010f6500-c39d-11eb-9f1d-ae6166b375b1.png)

**Comment by m-Chinese-Solution-Limited** [comment]
This is solved after updated to unity 2019.4.27.

**Comment by jballoffet** [comment]
Exactly, https://fogbugz.unity3d.com/default.asp?1329845_kbs6b00dog2rlij7 was fixed in Unity 2019.4.27f1.
