### ISSUE TITLE
VR rendered in the left half of the screen.

### ISSUE THREAD

**Issue by detraxo** [googlevr/cardboard#274]
![WhatsApp Image 2021-06-13 at 19 11 13](https://user-images.githubusercontent.com/59394222/121839892-a9f08500-ccf8-11eb-8210-c1dbef1fc588.jpeg)

This doesn't always happen and gets rectified if I exit the app and open it again. I have tried tweaking everything in the player settings, but nothing seems to happen. I also clearly followed the guidelines given in the Quickstart for Google Carboard for unity.

**Comment by Mandelbrow** [comment]
It would be nice with an option for the user to choose how much of the display should be used, too. The slightly rounded corner will probably reduce the processor load by some 25% or so, just from skipping the far out corners no one notices anyway.

**Comment by detraxo** [comment]
I think it has something to do with my AndroidManifest.xml file since I added an additional plugin for Text To Speech. 

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.starseed.speechtotext" 
		  android:versionCode="1" android:versionName="1.0">
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.INTERNET" />
  <application 
    android:requestLegacyExternalStorage="true"
    android:icon="@drawable/app_icon" 
    android:label="@string/app_name" android:debuggable="false"
    android:configChanges="orientation|screenSize|locale"
    android:theme="@style/UnityThemeSelector">
    <activity 
      android:name="com.starseed.speechtotext.MainActivity" 
      android:label="@string/app_name">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>   
  </application>
</manifest>`

If someone figure out what's causing the bug it'd be really helpful.

**Comment by detraxo** [comment]
Ok so I tweaked the xml file a little bit and I finally fixed the bug.
