### ISSUE TITLE
After updating from Unity 2019.4 to 2020.3 switching to VR freezes application screen

### ISSUE THREAD

**Issue by Varollo** [googlevr/cardboard#277]
## ISSUE
After updating from Unity 2019.4 to 2020.3, switching to VR freezes application screen. Everytime we tap to change to VR mode the application keeps running (won't crash and we can still hear audio and all scripts keep running), but the screen either freezes completly or the video keeps updating but we can't make any kind of VR input.
This is happening on Android and in the Editor, but we couldn't test on IOS.

## WHAT IS IN THE PROJECT
- Firebase Messaging
- Cardboard
- Universal Render Pipeline

## WHAT IS HAPPENING
When using version 1.4.1 of cardboard (the version we used when working with unity 2019.4).
When we switched to 1.6.0 we got two results:
- Using the mainTemplate.gradle that was already in the project the application video kept updating, but couldn't accept input.
- Using a new mainTemplate.gradle gerenated in a test project ( that worked fine with 2020.3 ) we got the same result as with cardboard 1.4.1, the screen freezes but we can still hear audio.

We tried updating firebase and the application crashed before the Unity splash screen.

## LOGCAT
When we build the application on Android and ran it on a Samsung S20fe alongside Unity Android Logcat, we got the following portion of logs (using cardboard 1.6.0):

```2021/06/23 15:24:09.675 23245 25023 Fatal CardboardXRUnity [../../../../unity/xr_unity_plugin/cardboard_xr_unity.cc : 92] Unsupported API: -1
2021/06/23 15:24:09.675 23245 25023 Info Unity [XR] [CardboardXrMain]: Input subsystem successfully loaded.
2021/06/23 15:24:09.681 23245 25023 Debug CardboardXRUnity [../../../../unity/xr_unity_plugin/cardboard_xr_unity.cc : 644] Configured OpenGL ES3.0 as Graphics API.
2021/06/23 15:24:09.685 23245 25023 Info Unity [XR] [CardboardXrInputProvider]: Lifecycle initialized
2021/06/23 15:24:09.686 23245 25931 Info CardboardSDK AccelerometerSensor: Created new event looper for accelerometer sensor capture thread.
2021/06/23 15:24:09.687 23245 25932 Info CardboardSDK Android Gyro Sensor: ASENSOR_TYPE_GYRO_UNCALIBRATED
2021/06/23 15:24:09.687 23245 25932 Info CardboardSDK AccelerometerSensor: Created new event looper for gyroscope sensor capture thread.
2021/06/23 15:24:09.701 23245 25023 Info Unity [XR] [CardboardXrInputProvider]: Lifecycle started
2021/06/23 15:24:09.701 23245 25075 Info Unity [XR] [CardboardXrDisplayProvider]: Initializes Cardboard API.
2021/06/23 15:24:09.703 23245 25075 Debug CardboardParamsUtils Reading device parameters from both scoped and external storage.
2021/06/23 15:24:09.711 23245 25075 Debug CardboardParamsUtils Parameters file not found for reading: java.io.FileNotFoundException: /storage/emulated/0/Cardboard/current_device_params: open failed: ENOENT (No such file or directory)
2021/06/23 15:24:09.713 23245 25075 Debug CardboardParamsUtils Parameters file not found for reading: java.io.FileNotFoundException: /data/user/0/com.realvi/files/Cardboard/current_device_params: open failed: ENOENT (No such file or directory)
2021/06/23 15:24:09.718 23245 25932 Info CardboardSDK Android gyro bias is: -0.027379, -0.010192, 0.005704
2021/06/23 15:24:09.720 23245 25075 Fatal com.realvi java_vm_ext.cc:578] JNI DETECTED ERROR IN APPLICATION: java_object == null
2021/06/23 15:24:09.720 23245 25075 Fatal com.realvi java_vm_ext.cc:578]     in call to GetObjectClass
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677] Runtime aborting...
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677] Dumping all threads without mutator lock held
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677] All threads:
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677] DALVIK THREADS (28):
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677] "Thread-35" prio=6 tid=2 Runnable
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   | group="" sCount=0 dsCount=0 flags=0 obj=0x12cc0000 self=0x770b501510
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   | sysTid=25075 nice=-2 cgrp=default sched=0/0 handle=0x7438feccc0
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   | state=R schedstat=( 4442155595 1372561338 44994 ) utm=301 stm=142 core=7 HZ=100
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   | stack=0x7438ef5000-0x7438ef7000 stackSize=995KB
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   | held mutexes= "abort lock" "mutator lock"(shared held)
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   native: #00 pc 00000000004a7eac  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+140)
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   native: #01 pc 00000000005b593c  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+376)
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   native: #02 pc 00000000005d2a74  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+924)
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   native: #03 pc 00000000005cc9b4  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+528)
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   native: #04 pc 00000000005cbb80  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1920)
2021/06/23 15:24:09.797 23245 25075 Fatal com.realvi runtime.cc:677]   native: #05 pc 00000000005664cc  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1864)
```

## TESTS DONE
In the past few days, since we upgrated our Unity version, we have been condutcing a series of tests to find out the root of the problem.
- First we created a new project following "the first steps", using Unity 2020.3 and cardboard version 1.6.0:
   - **Results**: worked just fine on the same Android device.
- We then, tried to add all packages to the project, inculding firebase]
   - **Results**: worked as well.
- We also tried to copy the mainTemplate.gradle and properties from the other project to the new one
   - **Results**: worked as expected

## TOUGHTS
We have very thoroughly studied all prior and current issues and found only one issue that may correlate with this one, the issue #258. The only problem we have to point that issue as being the one is that the application doesn't crash from the start, but in the same manner we have the same log that says:

> Fatal CardboardXRUnity [../../../../unity/xr_unity_plugin/cardboard_xr_unity.cc : 92] Unsupported API: -1

As stated in [this comment](https://github.com/googlevr/cardboard/issues/258#issuecomment-840804559), we have almost the same log, but unlike their problem we are not having reocurring crashes. We are using OpenGLES3.0 as the target graphics API and OpenGLES2.0 as a backup, both supported by this version of cardboard. 

After doing the tests mentioned above we were kind of lost, since the same cardboard version, with the same Unity version worked fine on a new project, but not on ours, even when removing some packages and assets from the build and the log of "Unsupported API" left us stranded without a clear course of action.

**Comment by Mandelbrow** [comment]
Hi, perhaps your camera object, or code for loading the XR device, are deviating from the demo code for Cardboard 1.6.0? Think there were some differences between 1.4.1, and 1.5.0.

**Comment by Varollo** [comment]
I tried importing the demo project to my project and it still freezes the screen, already checked the code and it's the same as the demo code as well

**Comment by Mandelbrow** [comment]
Are your project not running your own code?

**Comment by Varollo** [comment]
Not on the demo scene, I just added as the first scene in the build settings and ran with the scripts it came with, didn't change one line

**Comment by Varollo** [comment]
Ok after some more testing I've isolated the problem to the inclusion of a URP renderer feature, since this issue didn't have anything related to that and was getting a bit confusing I opened a new one here #283 and I am close this one.
