### ISSUE TITLE
URP Renderer Feature breakes Cardboard VR in Unity 2020.3

### ISSUE THREAD

**Issue by Varollo** [googlevr/cardboard#283]
## Issue
When adding URP and a renderer feature to a project with cardboard on Unity 2020.3 the screen is completly black.
If you toggle between no vr and vr the screen just freezes.

This was not happening on unity 2019.4.

## How to replicate
- Create a project in Unity 2020.3
- Add the cardboard VR package
- Add Unity's Universal Render Pipeline package
- Add any renderer features to the pipeline asset's foward renderer data
- Build the project and test on Android

I've also created a repository with the most basic version of the project that breaks and you can find it [here](https://github.com/Varollo/cardboard-urp-rendererfeature-issue).

I've already created an issue before, but after a lot of testing I've isolated the problem to the inclusion of an URP renderer feature, and the old issue was very confusing, so I've decided to open a new one.

**Comment by jballoffet** [comment]
Thanks for reaching out to us! Since there's already an open ticket for the URP issue (see #199), I'm closing this one. Thanks for all the provided details and feel free to comment on the aforementioned ticket.
