### ISSUE TITLE
Issue with building on Android

### ISSUE THREAD

**Issue by MusemoDeveloper** [googlevr/cardboard#292]
I am using unity version 2020.314f1 LTS and getting this issue while building on Android. How to fix that?
![Снимок](https://user-images.githubusercontent.com/55288472/129075388-1f7631e0-8b5f-4a4c-ba84-e986a81a104f.PNG)

**Comment by MusemoDeveloper** [comment]
found solution

**Comment by leksi37** [comment]
can you share the solution please? @MusemoDeveloper
