### ISSUE TITLE
Cardboard and Unity AR Foundation AR Plane Manager Not Working 

### ISSUE THREAD

**Issue by MAC9844** [googlevr/cardboard#295]
In Unity 2019, when I install it by adding cardboard sdk under xr settings under player settings, the plane cannot be detected because cardboard bends the image. How can I fix? 
![unity AR SDK Cardboard 2](https://user-images.githubusercontent.com/89253663/130224165-b73e2c15-e177-4f89-815e-63acf6152283.png)
![1](https://user-images.githubusercontent.com/89253663/130224183-b0a0a98f-8aeb-4a98-aa1c-5fd62de13d83.jpg)

**Comment by jballoffet** [comment]
Given the issue description, I suspect this is not related to the new Cardboard SDK but to the old one. Please bear in mind that GVR and the old Cardboard SDK have been deprecated and this new version should be used instead. See https://developers.google.com/cardboard/develop/unity/quickstart for the steps required to configure it.

Having said that, if you’re still having issues with the new SDK, please reach out to us again, by reopening this ticket and providing a repro project and the steps required to reproduce the issue.
