### ISSUE TITLE
MSAA Anti-Aliasing not applying when using Cardboard XR + Unity

### ISSUE THREAD

**Issue by BenWoodford** [googlevr/cardboard#296]
Didn't notice this on my Windows builds but the moment I deploy to Android and use CardboardXR a lot of my text becomes incredibly unreadable (TextMesh Pro FYI) - or as my client described it "like old-TV interference" - due to it not being aliased.

I've tried setting the `scaleOfAllRenderTargets` value of the DisplaySubsystem to 4 and it still looks heavily aliases too (bit difficult to find what you actually need to set in Unity these days as it seems to change every week...)

Is there some other setting I'm unaware of, or does the Cardboard XR package simply not support any form of aliasing or render scaling? This is the built-in pipeline on 2019.4.26f1, I believe I'm currently on Cardboard 1.6.0

**Comment by Mandelbrow** [comment]
SDK 1.7.0 is much better than 1.6.0. Not sure though how it's related to CloudXR.

**Comment by BenWoodford** [comment]
> SDK 1.7.0 is much better in general than 1.6.0. Not sure though how it's related to CloudXR.

That was my d’oh, I do a lot of CloudXR tinkering and went into autopilot when typing

I meant to say Cardboard XR!

**Comment by jballoffet** [comment]
Thanks @BenWoodford for reporting this issue! I'd really appreciate it if you could please provide a link to a simple Unity project where this issue is shown and the required steps to expose it. That would allow us to analyze it and properly prioritize it.
