### ISSUE TITLE
No Movement (Alt and CTRL) or Pointer Crosshair in HelloCardboard Demo Scene on Unity Windows ?

### ISSUE THREAD

**Issue by QaunainM** [googlevr/cardboard#297]
Hi all, I'm using Unity 2020.3.17f1 and I followed all the instructions here (i.e. installing via the GIT URL, updating all the player/project/build settings, modifying the 2 gradle files)  https://developers.google.com/cardboard/develop/unity/quickstart 

But I get no movement ability at all when I press Play in the Unity editor in Windows 10, I've tried  this on having the Build platform set to Windows and PC, MAC & Linux Standalone

Based on past versions of the Cardboard Unity integration I get the below features, of course, I want to use this newer integration instead of going back to a working deprecated version, can anyone help please, thanks.

**What Is currently not working** 

- No Crosshair / Reticle Pointer
- Alt + Mouse does nothing, it's supposed to move the camera
- CTRL + Mouse does nothing, its supposed to rotate 

Screenshot of what I see when I press Play https://drive.google.com/file/d/1c-rYInah88WoalqG7WfRvvm4HBzWuUqN/view?usp=sharing

**Comment by Mandelbrow** [comment]
Hi, it looks like you are running the demo in the Editor. Think you have to write your own code to use the keyboard to emulate the gyro for moving the camera. 

There are some common tips here:
[github.com/googlevr/cardboard/issues/140](https://github.com/googlevr/cardboard/issues/140)

**Comment by QaunainM** [comment]
Thanks, I noticed that on issue (140) it's mentions that Google have now removed the 'movement and look' aka 'Rectile and Gaze'

It's a shame, as the older versions of the Cardboard Unity API has this built in.

I don't see a point of making move and look from scratch, especially not for the raw basics, I think it goes against the philosophy of making  the whole pipeline fast, quick and easier.

Seems this will push people to use the older Cardboard Unity APIs :-(

**Comment by QaunainM** [comment]
Just to let everyone know, in order to get the movement, gaze and reticle pointer at the date of this post I could get it working with the old Cardboard Unity SDK and **Unity Version 2019.4.30f1**

**Comment by whizzkid** [comment]
@QaunainM beware that the old cardboard SDK is deprecated and won't work on IOS anymore (android still works).

**Comment by QaunainM** [comment]
@whizzkid , thanks for letting me know, damn, so the only solution I'm guessing for iOS compiling is to use the new Google Cardboard SDK and then make customer scripts, objects and prefabs to simulate movement and pointers.

It just seems so long as this is the core basic interactional elements that all end-users will require so it makes sense for it to be standardised in the SDK

**Comment by jballoffet** [comment]
Thanks @QaunainM for reaching out! Currently, the Cardboard XR plugin does not provide editor play mode capabilities. We haven't been able to prioritize this feature request yet but in case you'd like to propose the required changes, please feel free to do so, just read CONTRIBUTING.md and follow the process. Patches are welcome. I'm closing this ticket since we're tracking this effort in #51.

**Comment by QaunainM** [comment]
@jballoffet thanks for the reply, where can we submit feature requests.

Google Cardboard really has an opportunity to crush it and make a huge dent in the VR market.

It needs to have the basics like moving and cross hairs built into to the core SDK so developers can get moving on the rest of the VR pipeline.

Also since the magnet interaction was dropped I've noticed it's hard to get good headsets for V2 which have the push button in the headset.

I think one strandised cheap controller would also make Google cardboard a game changer
