### ISSUE TITLE
Reticle is not aligned in both screens (left & right eye)

### ISSUE THREAD

**Issue by unbounded26** [googlevr/cardboard#298]
### SPECIFIC ISSUE ENCOUNTERED
Firstly reticle is not included in the latest v1.8. So I used the following 2 ways to add it:

1. Implemented using old gvr, by adding the same shader and script
2. Implemented using Unity UI, simply added circle in the middle of the screen

But the issue remains the same. The reticle is not precise at the same location for both eyes. Especially in Android, it has more differences (the screenshot attached is for Android)

### SMARTPHONE (please complete the following information):
- OS
  - [x] Android
  - [x] iOS

### EXPECTED BEHAVIOR
The reticle should appear in the middle of both views (left & right)

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard XR Plugin 1.8.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Unity 2021.1.18f1

- Select in which graphics API you can reproduce the bug.
   - [x] OpenGL ES2
   - [x] OpenGL ES3
   - [x] Metal

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
**(This is not mandatory but it allows us to faster reproduce, prioritize, debug and fix the reported issue)**
[e.g. https://github.com/googlevr/cardboard]

### SCREENSHOTS
![photo_2021-09-16_09-35-18](https://user-images.githubusercontent.com/7029364/133551552-49cf861c-3b7c-4695-8fe7-a59863c36b29.jpg)

### ADDITIONAL CONTEXT

- There is no way to access the left and right eye view, so we can adjust it programmatically
- There is no way to test the click and two eye view on Unity Editor

If you are not going to include them in the SDK, then at least you can provide these functionalities in sample projects

**Comment by Mandelbrow** [comment]
Hi, doesn't it look like your white reticle dot is centered in the middle of both views, at a fixed distance? Which may not correspond to any of the objects in the rest of the scene, which in turn does not appear to have so much of a stereo view.

The reticle dot should not be different from any other object, or sprite image in the scene. What happens if you put a static object in the scene, is the stereo rendering off for that too?

**Comment by jballoffet** [comment]
Thanks @unbounded26 for reaching out! As @Mandelbrow pointed out, until this feature is added to the Cardboard XR plugin, you should be able to add the reticle as a game object within the scene and it should be properly placed within it when it is rendered by the distortion renderer.

About the reticle feature request, please see #47. In case you would like to propose changes, please feel free to read CONTRIBUTING.md and follow the process to send a PR. Thanks!

**Comment by unbounded26** [comment]
Thanks @Mandelbrow for your quick reply. Actually I couldn't see any settings related to stereo, even I checked [this link](https://docs.unity3d.com/2021.1/Documentation/Manual/SinglePassStereoRendering.html). As I'm using Unity 2021.1.18f1

Thanks @jballoffet  for your reply. May I know when the reticle would be added to the plugin?

> until this feature is added to the Cardboard XR plugin, you should be able to add the reticle as a game object within the scene and it should be properly placed within it when it is rendered by the distortion renderer.

As in Unity only 1 view can be seen and reticle is placed using Unity UI Image with center `(0, 0)`, still it's not correct. Also deviation is variant according to different devices.

As obviously view is not the same, so reticle issue seems to be linked with that

**Comment by Layfully** [comment]
@unbounded26 I have a different setup and I don't see an issue with rectile pointing at different places in left/right views. I made my rectile as a quad and applied texture to it. Then I made a custom overlay shader so that it is always displayed before everything else, even if it is behind it.

**Comment by imartini** [comment]
I have the same problem, I added a reticle in 0,0,0 position with canvas image. In Unity appears perfect but when I build in android, its not showing correctly. Any solution?

**Comment by jballoffet** [comment]
The reticle feature has been submitted and it was included in v1.20.0.
