### ISSUE TITLE
Unity XR + URP + Android + GLES2: black whole screen artifacts  

### ISSUE THREAD

**Issue by msuencksen** [googlevr/cardboard#300]
### SPECIFIC ISSUE ENCOUNTERED
On certain camera orientations,  black artifacts appear over the whole screen (pixelized and/or bars).

### SMARTPHONE (please complete the following information):
- Device: Xiaomi Mi8 Lite (Snapdragon 660) and reportedly Google Pixel 5
- OS
  - [x] Android
  - [ ] iOS
- OS version: Android 10 and MIUI 12 (latest)

### STEPS TO REPRODUCE THE ISSUE
1. Setup the Unity Universal Renderpipeline Sample Scene with Cardboard XR Plugin
2. Upload to smartphone 
3. Look around: the artifacts appear on certain camera orientations

### EXPECTED BEHAVIOR
No artifacts expected

### VERSIONS USED
Cardboard SDK/Cardboard XR Plugin 1.8

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
2020.3.19 + 2021.1.23

- Select in which graphics API you can reproduce the bug.
   - [x] OpenGL ES2
   - [ ] OpenGL ES3
   - [ ] Metal

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
https://github.com/msuencksen/CardboardArtifacts

### SCREENSHOTS
![Screenshot_2021-10-04-10-29-30-553_com DefaultCompany MyMobileProject2](https://user-images.githubusercontent.com/16103106/135823149-1382c38d-5062-46e0-8a50-741ee422d18c.jpg)
### ADDITIONAL CONTEXT
The artifacts disappear when XR mode is turned off for the APK.

**Comment by olive-farrell** [comment]
I've encountered this before - I think it happens if Disable Depth and Stencil (in Project Settings > Player > Android > Resolution and Presentation) is unchecked.

**Comment by msuencksen** [comment]
Thank you for this information. I can confirm the "Disable Depth Stencil" settings let the artifacts go away over here.

**Comment by jballoffet** [comment]
We confirm what @olive-farrell said. When using OpenGL ES2 if you set `Disable Depth and Stencil (in Project Settings > Player > Android > Resolution and Presentation)` this problem is solved. Also, we tested that using OpenGL ES3 works just fine with both configurations. We conclude this is a OpenGL ES2 only issue and the provided fix (at least) mitigates the bug.

**Comment by xinyunh0929** [comment]
To make more clear, we won't do any fix for it since it is an OpenGL ES2 issue.

**Comment by msuencksen** [comment]
Could you add the workaround on the Cardboard-Unity [quickstart page](https://developers.google.com/cardboard/develop/unity/quickstart) ?

**Comment by arilow** [comment]
Closing as GLES2 is not supported by Unity anymore.
