### ISSUE TITLE
Head tracking fails on some older Android devices after sleep

### ISSUE THREAD

**Issue by rawnsley** [googlevr/cardboard#302]
If my Android 5.1.1 device has gone to sleep at any point, the head tracking in the Google VR SDK fails spectacularly when it wakes up again. In the most mild version of the problem head tracking is jerky and unpredictable, but at worst the pose angle is effectively random from frame-to-frame. It is not solved by restarting the app and requires a full device reboot.

I've tracked this down to the result of `ComputeTimeDifferenceInSeconds` in [SensorFusionEkf::PredictRotation](https://github.com/googlevr/cardboard/blob/master/sdk/sensors/sensor_fusion_ekf.cc#L156) being wrong because *requested_timestamp* and *current_state_.timestamp* can come from two very different sources.

*requested_timestamp* is [calculated using CLOCK_BOOTTIME](https://github.com/googlevr/cardboard/blob/master/hellocardboard-android/src/main/jni/util.cc#L431), which includes time spent in suspend ([ref](https://stackoverflow.com/a/3527632/671393)).

*current_state_.timestamp* comes from the sensor events and is somewhat opaque. It should be set [using elapsedRealtimeNano](https://developer.android.com/reference/android/hardware/SensorEvent#timestamp) and that function [may use /dev/alarm in older versions of Android](https://android.googlesource.com/platform/system/core/+/refs/heads/lollipop-mr1-release/libutils/SystemClock.cpp#109), but [uses CLOCK_BOOTTIME in later versions](https://android.googlesource.com/platform/system/core/+/refs/heads/oreo-m8-release/libutils/SystemClock.cpp).

Actually, although recent [Android compatibility guidelines](https://source.android.com/compatibility/android-cdd) say the system event timestamp MUST come from `SystemClock.elapsedRealtimeNano()` it was [only a suggestion previously](https://source.android.com/compatibility/5.1/android-5.1-cdd). I have not found a device that doesn't follow this suggestion though, so this complication can probably be ignored.

I'm struggling to come up with a suitable workaround. The obvious answer is to call `SystemClock.elapsedRealtimeNano()` instead of using `clock_gettime` directly, but SystemClock lives in **libutils**, which isn't exposed in the Android NDK.

**Comment by arilow** [comment]
Closing as it's been a while since the last comment. In case this is still an issue for you, please feel free to reopen this ticket. Thanks!
