### ISSUE TITLE
Unity XR plugin library CardboardXrProvider is unable to be open sourced.

### ISSUE THREAD

**Issue by chaosemer** [googlevr/cardboard#32]
Unity XR plugin libraries libCardboardXrProvider.so for Android and CardboardXrProvider.a for iOS are still unable to be open sourced. We hope to do it in a future update.

**Comment by StephenHodgson** [comment]
Literally what I was looking for. Any ETA on this?

**Comment by jballoffet** [comment]
We are currently working on including the source code for these binaries in a future release. Please star or watch this issue to be notified when it becomes available.

**Comment by chaosemer** [comment]
With 1.2.0 out, this is now resolved.
