### ISSUE TITLE
Unity/iOS Archive fails in Xcode 13.1: All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64

### ISSUE THREAD

**Issue by rubit0** [googlevr/cardboard#321]
### SPECIFIC ISSUE ENCOUNTERED
I'm using the Unity XR Plugin of the latest Cardboard Version and it all works great in Android and iOS but sadly I can't make an Archive in Xcode for publishing to TestFlight.

This is the error in Xcode when I perform the Archive operation:

> ld: bitcode bundle could not be generated because '..../builds/ios/Libraries/com.google.xr.cardboard/Runtime/iOS/cardboard_api.a(cardboard.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

### EXPECTED BEHAVIOR
Archive in Xcode should work.

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard XR Plugin 1.11.0

**If you are using Cardboard XR Plugin:**
Unity 2020.3.20f1

**Comment by rubit0** [comment]
Quick update, this code snipped fixed the Xcode issue: https://forum.unity.com/threads/bitcode-bundle-could-not-be-generated-issue.897590/#post-5914007

Maybe that could be integrated into the next XR-Plugin release or at least mentioned in the quickstart guides iOS section.

**Comment by ChaosAlfa** [comment]
I have the same problem and would like to see a permanent solution

**Comment by Archi97** [comment]
Anything new on this? Bitcoin "NO" not helping.

**Comment by jballoffet** [comment]
A fix for this issue has been submitted and it will be included in v1.18.0. Thanks for reaching out!

**Comment by xinyunh0929** [comment]
This was fixed in v1.18.0.
