### ISSUE TITLE
documentation says minSDK level is 16, but code appears to require 24

### ISSUE THREAD

**Issue by jharan55** [googlevr/cardboard#328]
### SPECIFIC ISSUE ENCOUNTERED
I built the hellocardboard app and sdk intending to run it on my old Samsung Galaxy S4, which runs Android 4.4.2, API level 19.
The documentation states hardware requirements as "Android device running Android 4.4 "KitKat" (API level 16) or higher". However when I attempt to run the hellocardboard app, I get this warning:

minSdk(API 24) > deviceSdk(API 19) on device samsung
SAMSUNG-SGH-I337Z

and this:

02/01 17:50:45: Launching 'hellocardboard-android' on <default>.
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_OLDER_SDK

List of apks:
[0] '/home/android/cardboard/cardboard/hellocardboard-android/build/intermediates/apk/debug/hellocardboard-android-debug.apk'
The application's minSdkVersion is newer than the device API level.

Which is wrong, the code or the documentation? If its the code, how can I fix this?

### SMARTPHONE (please complete the following information):
- Device: [Samsung Galaxy S4
- OS
  - [X] Android
  - [ ] iOS
- OS version [4.4.2]

### STEPS TO REPRODUCE THE ISSUE
Follow Step 4 in the documentation at https://developers.google.com/cardboard/develop/c/quickstart.

### EXPECTED BEHAVIOR
I expected to see the sample app install and run on my phone.

### VERSIONS USED
SDK Manager says Android SDK Platform 32 is installed

Its the hellocardboard app so its using the NDK.

- Select in which graphics API you can reproduce the bug.
You tell me. 8)

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
This one: https://github.com/googlevr/cardboard

**Comment by jharan55** [comment]
Just documenting what I did to get past this problem in case others run into it.

There are 3 files named build.gradle in the project. Two of them:

./hellocardboard-android/build.gradle, and,
./sdk/build.gradle

contain this line:

               minSdkVersion 24

I changed that 24 to an 18 (since my phone apparently supports 19), did a File->Sync Project to Gradle Files and double clicked the assemble options under:

Gradle window->cardboard->sdk->Tasks->build->assemble

then

Gradle window->cardboard->hellocardboard-android->Tasks->build->assemble

Then Run->Run and select the hellocardboard-android line with the little green Android head next to it. Now the code downloads to my old phone and runs at least something that looks like the app shown in the documentation.

I haven't received my cardboard viewer in the mail yet, so that's as far as I could go, but progress.

There's a bunch of other steps necessary to get this far that aren't covered in https://developers.google.com/cardboard/develop/c/quickstart, particularly around putting the phone in developer mode and getting it to connect to the PC running Android Studio. Some of that is described at:

https://developer.android.com/training/basics/firstapp/running-app

Though even that is missing some steps about accepting RSA keys and clicking "Revoke USB debugging authorization" whenever you reattach the phone.

**Comment by jballoffet** [comment]
Thanks @jharan55 for reaching out to us! I just wanted to mention that we have updated the [requirements section in the Android NDK quickstart](https://developers.google.com/cardboard/develop/c/quickstart#set_up_your_development_environment). As stated [here](https://github.com/googlevr/cardboard/blob/e7a1c22e456ff67116dd016c760dcc469bfa973e/sdk/build.gradle#L11-L18), the minSdkVersion can be reduced down to 16 depending on the rendering API that needs to be supported. HTH.

**Comment by jharan55** [comment]
OK, so you are saying it should work with an API level 19 phone like my old Galaxy S4, right?

If that's the case, should I file a bug for the behavior I see when I try to run it on my old Galaxy S4?

Thanks
