### ISSUE TITLE
Saving/Getting device details does not work on Android versions < 10

### ISSUE THREAD

**Issue by johnfriedrich** [googlevr/cardboard#329]
### SPECIFIC ISSUE ENCOUNTERED
When setting device information via 
```
Api.SaveDeviceParams
```
(Did not check QR code)
it reports a permission denied error as the sdk tries to access external storage.

I did follow the tutorial and added the request permissions to manifest. Thats our manifest file:

```
<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED BY UNITY. REMOVE THIS COMMENT TO PREVENT OVERWRITING WHEN EXPORTING AGAIN-->
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.unity3d.player"
    xmlns:tools="http://schemas.android.com/tools">
    <application android:requestLegacyExternalStorage="true">
        <activity android:name="com.tiledmedia.clearvrforunityandroid.ClearVRForUnityAndroidActivity"
                  android:theme="@style/UnityThemeSelector">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
        </activity>
    </application>
</manifest>

```

### SMARTPHONE (please complete the following information):
- Device: Samsung S8
- OS
  - [x ] Android
  - [ ] iOS
- OS version 9
- Target Api 31/32 (tested both)

### STEPS TO REPRODUCE THE ISSUE
- Set Device params via code
- Build and Run to Android
- watch logcat. Device params cannot be fetched, cannot be saved and are therefore not applied at all

### EXPECTED BEHAVIOR
Device params are saved and applied

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard SDK/Cardboard XR Plugin 1.12.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
2020.3.25

Log:
```
D/CardboardParamsUtils(27361): Reading device parameters from external storage.
D/CardboardParamsUtils(27361): Parameters file not found for reading: java.io.FileNotFoundException: /storage/emulated/0/Cardboard/current_device_params (Permission denied)
I/Unity   (27361): [CardboardApi] No device params found.
I/Unity   (27361): Google.XR.Cardboard.Api:HasDeviceParams()
I/Unity   (27361): <StartXR>d__17:MoveNext()
I/Unity   (27361): UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
I/Unity   (27361): 
D/CardboardParamsUtils(27361): Following redirects for original URI: https://goo.gl/cfliQY
D/NetworkSecurityConfig(27361): No Network Security Config specified, using platform default
I/CardboardSDK(27361): Android gyro bias is: 0.019029, -0.019459, -0.019860
I/CardboardParamsUtils(27361): Response code: 301
I/CardboardParamsUtils(27361): Location: http://google.com/cardboard/cfg?p=CgZIb21pZG8SCUhvbWlkbyBWMh2WQws9JbbzfT0qEAAASEIAAEhCAABIQgAASEJYATUpXA89Oghcj0I-CtejPVAAYAI
I/CardboardParamsUtils(27361): Param URI redirect to https://google.com/cardboard/cfg?p=CgZIb21pZG8SCUhvbWlkbyBWMh2WQws9JbbzfT0qEAAASEIAAEhCAABIQgAASEJYATUpXA89Oghcj0I-CtejPVAAYAI
D/CardboardParamsUtils(27361): Writing device parameters to external storage.
E/CardboardParamsUtils(27361): Parameters file not found for writing: java.io.FileNotFoundException: /storage/emulated/0/Cardboard/current_device_params (Permission denied)
D/CardboardParamsUtils(27361): Could not write Cardboard parameters to storage.
I/Unity   (27361): [CardboardApi] Reload device parameters.
I/Unity   (27361): Google.XR.Cardboard.Api:ReloadDeviceParams()
```

### ADDITIONAL CONTEXT
It works on Android 10 and higher. When having a look at the code, that also makes sense. But not sure why the permission is not working.

We are currently using, due to reasons, cardboard sdk 1.1, where this still works, even on Android 10 devices and higher.
But we are in the process of upgrading and encountered this issue.

**Comment by jballoffet** [comment]
Thanks @johnfriedrich for reaching out to us!  In order to allow us to reproduce this issue, could you please provide a link to a simple Unity project where this issue is shown? (it's ok if it's just a Unity project with the HelloCardboard sample scene). That would help us to reproduce the issue and find a way to fix it.

Thanks!

**Comment by jballoffet** [comment]
Without a repro project, we can not help here. If you are still having this issue, please reopen and point us to a repro project with steps to reproduce. Thanks!

**Comment by arjenveenhuizen** [comment]
Apologies for bumping a closed issue, but this looks like a valid bug to me and it would be great if it would get solved. 

The issue lies here: https://github.com/googlevr/cardboard/blob/407fffc4b0c984fef821db51e04c151d691c02a8/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java#L488

On API > 23 and < Android.Q, one has to actively request `android.permission.WRITE_EXTERNAL_STORAGE` to write to `Environment.getExternalStorageDirectory()`. 

I do not have a repro project lying around, but I think the following should be sufficient:
1. Remove storage write permissions from sample project.
2. Run sample project on API > 23 but < Q device
3. Observe problem.

Or does the cardboard SDK require this permission? I could only find a reference to using the camera permission for QR code scanning?

**Comment by arjenveenhuizen** [comment]
For anyone wondering, the following patch fixed the issue for us:

```
diff --git a/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java b/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java
index 43b3fcf..b9b90ab 100644
--- a/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java
+++ b/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/CardboardParamsUtils.java
@@ -485,9 +485,7 @@ public abstract class CardboardParamsUtils {
   private static File getDeviceParamsFile(StorageSource storageSource, Context context) {
     File configFolder =
         new File(
-            storageSource == StorageSource.SCOPED_STORAGE
-                ? context.getFilesDir()
-                : Environment.getExternalStorageDirectory(),
+                context.getExternalFilesDir(null),
             CARDBOARD_CONFIG_FOLDER);
 
     if (!configFolder.exists()) {

```
