### ISSUE TITLE
Unity XR plugin will have build errors unless iOS and Android support are both installed in Unity.

### ISSUE THREAD

**Issue by chaosemer** [googlevr/cardboard#33]

**Comment by npig** [comment]
Could I please have some clarifcation on what 'iOS and Android support' means? Is this a reference to Install Modules or Unity Packages?

**Comment by chaosemer** [comment]
This refers to the "Android Build Support" and "iOS Build Support" modules for Unity. You don't have to actually use them beyond that (it's fine to build your project for just Android, for example).

**Comment by jballoffet** [comment]
A fix for this has just been submitted and it will be included in the next release.

**Comment by chaosemer** [comment]
This was fixed in v1.3.0.
