### ISSUE TITLE
Gradle fails to build when XR Cardboard Plugin installed

### ISSUE THREAD

**Issue by irojdest** [googlevr/cardboard#330]
Unity 2020.3.21f. Works fine with AR Foundation. However if I install XR Cardboard Plugin from https://github.com/googlevr/cardboard-xr-plugin.git I get errors like

![image](https://user-images.githubusercontent.com/49315303/152401870-2d0fcf95-443e-4b9a-a791-a9701fa5b64a.png)

Read almost everything regarding issues and tried almost all recipes found in forums. No avail!

**Comment by Warwlock** [comment]
I don't know you tried that but here is documentation how to setup:
[https://developers.google.com/cardboard/develop/unity/quickstart](https://developers.google.com/cardboard/develop/unity/quickstart)

Under the [Publishing Settings](https://developers.google.com/cardboard/develop/unity/quickstart#publishing_settings) you can see some changes required for gradle. 

I recommend read from top to bottom in any case you forget something.

**Comment by irojdest** [comment]
Did everything to letter, of no avail.

**Comment by Warwlock** [comment]
So, how did you add `Custom Main Gradle Template` and `Custom Gradle Properties Template` to your project?

In documentation says, add some line of code but it doesn't say where to add. I think gradle error happend becuse either you didn't check publishing settings for `Custom Main Gradle Template` and `Custom Gradle Properties Template` or you added those lines of code from documentation incorrectly. Here is my files:

![Untitled](https://user-images.githubusercontent.com/73683644/152545793-fe627e07-c5ce-417b-a688-a2afa4bda5de.png)

And those are the my changes on custom templates:
(In `mainTemplate.gradle` added four extra `implementation` lines under `dependencies`)
(In `gradleTemplate.properties` added two extra lines with different alignment (alignment is not important just for remember))
[Custom Main Gradle Template (mainTemplate.gradle)](https://github.com/Warwlock/additionalThings/blob/main/mainTemplate.gradle)
[Custom Gradle Properties Template (gradleTemplate.properties)](https://github.com/Warwlock/additionalThings/blob/main/gradleTemplate.properties)


Other than that, I don't know what would cause this issue.

**Comment by irojdest** [comment]
Warwlock, I still get an error 
> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by irojdest** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Unity\2011124ARTest13\Temp\gradleOut\unityLibrary\build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':unityLibrary'.
> No signature of method: java.lang.String.positive() is applicable for argument types: () values: []
  Possible solutions: notify(), size(), size(), tokenize()

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by arilow** [comment]
Thanks @irojdest for reaching out to us! This issue seems to be related to something missing in the project configuration.


In order to allow us to reproduce this issue, could you please provide a link to a simple Unity project where this issue is shown? (it's ok if it's just a Unity project with the HelloCardboard sample scene). That would help us to pinpoint the issue and find a way to fix it.


Thanks!

**Comment by jballoffet** [comment]
Without a repro project, we can not help here. If you are still having this issue, please reopen and point us to a repro project with steps to reproduce. Thanks!
