### ISSUE TITLE
6DoF and Position Tracking

### ISSUE THREAD

**Issue by Warwlock** [googlevr/cardboard#331]
There is a pull request #210 called 6DoF tracking support. And I'm wondering, when it will be available for Unity? Or, was it just a test project?

**Comment by arilow** [comment]
Thanks @Warwlock for reaching out to us! 6DoF has not been prioritized among other tasks yet. 


I'm closing this issue as it is a duplicate of #7. Please feel free to leave comments on that issue if needed.
