### ISSUE TITLE
Xr plugin not works with Firebase

### ISSUE THREAD

**Issue by MusemoDeveloper** [googlevr/cardboard#344]
### SPECIFIC ISSUE ENCOUNTERED
Application is not building. Getting issue with manifest

### SMARTPHONE (please complete the following information):
- Device: 
 Android

### STEPS TO REPRODUCE THE ISSUE
1. Add firebase Auth sdk to project
2.  Add xrPlugin to project. Followed intructions:https://developers.google.com/cardboard/develop/unity/quickstart. Application is not building
3.  Follow the intructions: https://developers.google.com/cardboard/develop/unity/quickstart.
4. Build on Android

### VERSIONS USED
-Cardboard XR Plugin 1.13
-Unity 2020.3.20f1

Graphics API to reproduce the bug.
   -  OpenGL ES2
   - OpenGL ES3
![manifestfail](https://user-images.githubusercontent.com/55288472/160868137-9d69ec7a-a31c-4ccd-9d1e-faf45d938878.PNG)

**Comment by arilow** [comment]
Thanks for reaching out to us @MusemoDeveloper! I got that error when I forgot to follow step 2 from [Other Settings](https://developers.google.com/cardboard/develop/unity/quickstart#other_settings) in the [Quickstart](https://developers.google.com/cardboard/develop/unity/quickstart).
You just have to go to `Project Settings > Player > Other Settings` and, in the `Minimum API Level` section, select `API 24` or higher.


Please reopen this ticket in case this does not solve your issue or you encounter new issues.

**Comment by MusemoDeveloper** [comment]
Thak you. that works)
