### ISSUE TITLE
PAD and Google Cardboard compilation error with apps upper than +150MB 

### ISSUE THREAD

**Issue by imartini** [googlevr/cardboard#347]
I having a error when I creating the app  (aab). Unity shows a duplicated dependencies

[https://i.ibb.co/1KN31Ns/Captura-de-pantalla-2022-05-04-161032.jpg](https://i.ibb.co/1KN31Ns/Captura-de-pantalla-2022-05-04-161032.jpg)

I'm using:

- Unity Addressables with Unity example project [->](https://github.com/Unity-Technologies/Addressables-Sample/tree/master/Advanced/Play%20Asset%20Delivery)
- App upper than 150 MB (2 GB aproximate)
- Unity 2020.3.33f1

**Comment by arilow** [comment]
Thanks @imartini for reporting this issue and sharing an example project. In order to allow us to help you with this, it would be really helpful if you could provide us with a detailed list of the required steps to expose the issue.


Thanks!

**Comment by imartini** [comment]
Hi arolow, sorry for the late response. Seems the error is fixed in the las build of Unity. I need more testing to see if the cardboard loads correctly.

**Comment by arilow** [comment]
Closing as this seems to be fixed. Feel free to reopen this issue in case you find any issue after you do the testing.


Thanks!
