### ISSUE TITLE
Left and right eyes are rendered identically in iOS, without separation

### ISSUE THREAD

**Issue by dantepfer** [googlevr/cardboard#352]
### SPECIFIC ISSUE ENCOUNTERED
Running the Hello Cardboard example on iOS 15, there is no stereoscopy between the eyes — they are rendered identically. Running the same example on Android yields the expected result, with separate images rendered for each eye from different vantage points.

### SMARTPHONE (please complete the following information):
- Device: iPhone 12 Pro
- OS
  - [ ] Android
  - [x] iOS
- OS version 15

### STEPS TO REPRODUCE THE ISSUE
1. run Hello Cardboard project on iOS2. 
2. compare the two eyes, and see that they are identical

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard SDK/Cardboard XR Plugin 1.15.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Example: 2021.3.2f1

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [ ] OpenGL ES3
   - [x] Metal
   
   -screenshot:
![IMG_97D64444120A-1](https://user-images.githubusercontent.com/22966048/167585945-a550bf65-31fb-41b1-88a6-eb65a4a0a60c.jpeg)

**Comment by Layfully** [comment]
Those images are not the same. Take a look again :)

**Comment by dantepfer** [comment]
> Those images are not the same. Take a look again :)

You're right, they're not identical — something I noticed after posting this bug. The issue is that the stereo separation on iOS is much smaller than that on Android. For the exact same project, on Android the two eyes are noticeably different; on iOS they're almost the same. Is this a matter of setting the distance between the eyes? Any ideas?

**Comment by dantepfer** [comment]
Thank you for your answer, @arilow. To be clear, this issue is occurring when using the XR Plugin for Unity. The native sample works perfectly, with the expected separation between the eyes. It's quite a difference when running the Unity sample; everything looks flat. How would I change the `device_params_.inter_lens_distance()` value in the XR Plugin?
