### ISSUE TITLE
I Cannot Find the Hello Cardboard Sample App after installing the Cardboard XR Plugin

### ISSUE THREAD

**Issue by lightbe** [googlevr/cardboard#360]
### SPECIFIC ISSUE ENCOUNTERED
When I follow the instructions on this link: https://developers.google.com/cardboard/develop/unity/quickstart to use the Cardboard XR Plugin for Unity I can't import this folder: **Assets/Samples/Google Cardboard/<version>/Hello Cardboard**. 

### SMARTPHONE (please complete the following information):
- Device: iPhone XR
- OS: iOS 15.5

### STEPS TO REPRODUCE THE ISSUE (from the Google Developer link above):
1. Open Unity and create a new **3D** project.
2. In Unity, go to **Window > Package Manager**.
3. Click **+** and select **Add package from git URL**.
4. Paste **https://github.com/googlevr/cardboard-xr-plugin.git** into the text entry field.
The package should be added to the installed packages.
5. Navigate to the **Google Cardboard XR Plugin for Unity** package. In the Samples section, choose **Import into Project**.
The sample assets should be loaded into **Assets/Samples/Google Cardboard/<version>/Hello Cardboard**.

After step 4 I saw progress windows for the plugin installation. I didn't see any errors. I checked **Cardboard XR Plugin** in the **Unity XR Plug-in Management** project settings after step 4 had finished. Again I saw progress windows and saw no errors.

### EXPECTED BEHAVIOR
I expect to find the  **Google Cardboard XR Plugin for Unity** listed in the **Window > Package Manager** list. I assume that is where I'm supposed to choose **Import into Project**.  

### VERSIONS USED
**What version of Google Cardboard are you using?**
I have no entry for the **Google Cardboard XR Plugin** in the **Package Manager** list so I can't provide the version number.

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
2019.4.37f1 - the Google documentation recommends to use this starting with Unity version 2019.4.25f1

- Select in which graphics API you can reproduce the bug.
N/A

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
N/A

### SCREENSHOTS
![Screen Shot 2022-07-15 at 12 35 43 PM](https://user-images.githubusercontent.com/1304976/179278844-1788d7c7-dc7e-4bfe-9169-3c9c895b9795.jpg)

### ADDITIONAL CONTEXT
I'm running Unity 2019.4.37f1 on a Mac Mini M1 running macOS Monterey 12.4.

**Comment by arilow** [comment]
Thanks @lightbe for reporting this issue! 

In the image you shared, in the top left corner of the package manager, it says "Unity Registry". Click on that button and change it to "In Project". You should now see something similar to what is in the following image:

![issue_image](https://user-images.githubusercontent.com/43258762/179507830-e8ed918a-9fdf-4282-bbd5-0862d376147c.png)

After doing that, you should be able to import the sample without any problems.

Please let us know if this does not solve your issue or you need further help.

Thanks!

**Comment by lightbe** [comment]
@arilow I was able to successfully import the project. Your response should replace the first sentence in step 5. I had no idea what 'Navigate' in step 5 meant since this is my first time trying to use the plugin. Thanks so much!
