### ISSUE TITLE
How to adjust the XR cardboard mask size to be larger a bit ?

### ISSUE THREAD

**Issue by rickygai** [googlevr/cardboard#362]
Hi,

Apologizing, this is not an issues but a features to request.

Is there a way to adjust the size of the XR cardboard mask as I am using 6.5" phone, there are still plenty of space on the phone screen size.

For example, the **picture B** below is built with **Google Cardboard XR Plugin for Unity version 1.16.0** where its cardboard mask is smaller in size:

![image](https://user-images.githubusercontent.com/15626855/184853975-aee9a871-73b8-4cf1-afa2-1431abb4cb38.png)

Please advise.

**Comment by rickygai** [comment]
Found the answer, it required the Cardboard QR Code that comes with the VR headset, if you don't have you may check at the link [HERE](https://www.hypergridbusiness.com/faq/vr-headset-qr-codes/). 

Alternatively, you may generate Cardboard QR Code based on your VR headset measurement [HERE](https://arvr.google.com/cardboard/viewerprofilegenerator/).

**Comment by arilow** [comment]
Thanks @rickygai for sharing your solution!


I’m closing this as it seems to be solved.
