### ISSUE TITLE
Is the stencil buffer not supported?

### ISSUE THREAD

**Issue by ImmotionPeterL** [googlevr/cardboard#365]
### SPECIFIC ISSUE ENCOUNTERED
A shader using the stencil buffer doesn't work in VR.

### SMARTPHONE (please complete the following information):
- Device: tested on Samsung Galaxy Note 10, iPhone 11, 13 Pro Max
- OS
  - [x] Android
  - [x] iOS
- OS version [e.g. 12]: Android 12, iOS 15

### STEPS TO REPRODUCE THE ISSUE
1. Run VR with a shader that uses the stencil buffer
2. Stencil buffer is ignored

### EXPECTED BEHAVIOR
Shader to act as it does out of VR and respect the stencil buffer.

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard SDK/Cardboard XR Plugin 1.16 and 1.17

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
2020.3.25

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [x] OpenGL ES3
   - [x] Metal

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
**(This is not mandatory but it allows us to faster reproduce, prioritize, debug and fix the reported issue)**
[e.g. https://github.com/googlevr/cardboard]

### SCREENSHOTS
![Screenshot_20220818-125709](https://user-images.githubusercontent.com/71014042/186650558-717841f1-7bda-491a-819b-0a6c209f0c43.jpg)
![Screenshot_20220818-125730](https://user-images.githubusercontent.com/71014042/186650592-267f751c-48b4-4728-9a1f-8d9cb744e836.jpg)

**Comment by arilow** [comment]
Thanks @ImmotionPeterL for reaching out to us. And for all the information provided! 


Given that  this issue has been already reported in #162, I am going to close this ticket in favor of that one. Thus, this ticket is going to be linked to the original one.


Please feel free to leave comments on that issue if needed.


Thanks!

**Comment by 3493000** [comment]
using UnityEngine;

public class Test : MonoBehaviour
{
    private void OnRenderImage(RenderTexture source, RenderTexture destination)
    {
        Graphics.Blit(source,destination);
    }
}
