### ISSUE TITLE
Cardboard 3.2 crash on GS4

### ISSUE THREAD

**Issue by OmegaMule** [googlevr/cardboard#368]
### SPECIFIC ISSUE ENCOUNTERED
Application crashes instantly after start.

### SMARTPHONE (please complete the following information):
Galaxy S4 
Android 4.4

### STEPS TO REPRODUCE THE ISSUE
Install the app, click on its icon.

### EXPECTED BEHAVIOR
Should not crash on supported devices.

### ADDITIONAL CONTEXT
09/02 14:39:35.022 23673 23673 Error AndroidRuntime java.lang.NoClassDefFoundError: vn
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at aie.<clinit>(PG:1)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at etr.<init>(PG:1)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at esc.<init>(PG:1)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at esd.<init>(PG:1)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at ery.a(PG:7)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at esa.onCreate(PG:2)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4581)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at android.app.ActivityThread.access$1600(ActivityThread.java:161)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:102)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:157)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:5356)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at java.lang.reflect.Method.invokeNative(Native Method)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Method.java:515)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
09/02 14:39:35.022 23673 23673 Error AndroidRuntime 	at dalvik.system.NativeStart.main(Native Method)

**Comment by arilow** [comment]
Thanks for reaching out to us @OmegaMule! 


Given that this repository is meant to maintain only the Cardboard SDK and the Cardboard XR Plugin, I am afraid I have to close this ticket as it is not related to the mentioned packages.


In order to send feedback to the Android App team, you can do it by pressing the “Help and Feedback” buttons in the 3 dots menu.


Thanks!
