### ISSUE TITLE
Support for new iPhone 14 variants

### ISSUE THREAD

**Issue by johnfriedrich** [googlevr/cardboard#369]
### SPECIFIC ISSUE ENCOUNTERED
Small reminder: It is that time again, new iPhones are out and they need new dpi values.

https://www.theiphonewiki.com/wiki/D74AP
https://www.theiphonewiki.com/wiki/D73AP
https://www.theiphonewiki.com/wiki/D28AP
https://www.theiphonewiki.com/wiki/D27AP

**Comment by jballoffet** [comment]
A fix for this issue has been submitted and it will be included in v1.18.0. Thanks for reaching out!

**Comment by championsnet** [comment]
How can we fix it manually until the update rolls out?

**Comment by johnfriedrich** [comment]
> How can we fix it manually until the update rolls out?

You could update the sdk with these values and compile it yourself.
https://github.com/johnfriedrich/cardboard/commit/1969dfca78afe1a0b059f26438cff4576a654445
Please check yourself if they are correct before using.

**Comment by xinyunh0929** [comment]
This was fixed in v1.18.0.
