### ISSUE TITLE
Fresh Unity iOS build has xcode undefined symbol errors

### ISSUE THREAD

**Issue by andypoly** [googlevr/cardboard#376]
### SPECIFIC ISSUE ENCOUNTERED
In an Xcode (13.4.1) build from Unity 2020 LTS latest, I build the HelloCardboard sample scene to device.
I get numerous errors about Undefined symbols for architecture arm64
e.g. "_objc_msgSend$lock", referenced from: -[CardboardSensorHelper invokeBlock:withLock:] in GfxPluginCardboard.a (sensor_helper.o)"

Am I missing something?!

### SMARTPHONE (please complete the following information):
iOS 12+ pre-iPhone build completed

### STEPS TO REPRODUCE THE ISSUE
Build cardboard test in 2020 LTS, build to xcode 13, try and run on iOS phone

### EXPECTED BEHAVIOR
no errors

### VERSIONS USED
see above, latest cardboard 1.18

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
2020.3.41 LTS 

Auto Graphics API - irrelevant

**Comment by andypoly** [comment]
ok bad. But if I re-get the plugin via git link in Unity, it is still getting 1.18.0 currently

**Comment by isurfraz** [comment]
This is still happening even with the patch
