### ISSUE TITLE
Inverted video image and inverted phone moves in stereoscopic view

### ISSUE THREAD

**Issue by bat01** [googlevr/cardboard#377]
### SPECIFIC ISSUE ENCOUNTERED
I'm playing VR videos through my app using Cardboard XR Plugin for Unity. After the recent iOS 16 update (and Xcode 14 update too), videos in stereoscopic mode were flipped upside down and backwards. After trying to change sides manually in code, I only managed to show correct sides (it's not all upside down anymore), but when I turn the phone UP, the view is moving DOWN to the ground, and vice versa. Same issue for left-right phone moving - moving left shows the right side and vice versa. Also Unity-made popup question is shown on the wrong side (backside - shown in the video attachment)

IMPORTANT: I did manage few times fixing it to work on local build, but when I build it for AppStore, it is always inverted. I think it is related to how Unity is receiving the axis orientation from iOS. Is it possible that your Cardboard XR Plugin can be optimized to fix this issue?

Again, this is only happening on iOS 16 built with Xcode 14 and I'm out of ideas.

### SMARTPHONE (please complete the following information):
- Device: multiple iPhones running multiple iOS 16 versions
- OS
  - [ ] Android
  - [x] iOS
- OS version [16.1]

### STEPS TO REPRODUCE THE ISSUE
1. Local builds are working fine (although I'm always using release builds from Unity).
2. Try to build for iOS 16 with Xcode 14. Release builds through Flutter is having issue on iOS.

### EXPECTED BEHAVIOR
VR videos should show right side (not upside down image) and moving up should show upper part of the video, and vice versa. Same goes for left and right move.

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard XR Plugin
1.18.1

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
2022.1.13f1

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [ ] OpenGL ES3
   - [x] Metal

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
**(This is not mandatory but it allows us to faster reproduce, prioritize, debug and fix the reported issue)**
https://github.com/googlevr/cardboard-xr-plugin

### ADDITIONAL CONTEXT
Please see my videos of playing the video and showing the Unity-made popup question. One is showing everything upside down, and other is showing correct orientation, but when turning phone left and right, up and down - it moves in wrong (opposite) direction.

https://user-images.githubusercontent.com/66939897/199540064-939d86c4-3b99-498e-9d15-e6680b9e6516.mp4

https://user-images.githubusercontent.com/66939897/199540074-28ec1c5b-b9c7-42b9-87b4-51e7491218e1.mp4

**Comment by arilow** [comment]
Thanks for reporting this issue. in order to allow us to reproduce this issue, could you please provide:
- The exact model of your device.
- Unity version.
- Can you reproduce this behavior with the hellocardboard scene? If so, A video using the sample would be really helpful. If not, please provide us with a project where the bug can be reproduced.

Thanks!

**Comment by dipinarora9** [comment]
Hi @bat01  ,it might be the case that unity is not recognizing the orientation of the device. 
try to set rotation explicitly by calling
`Screen.orientation = ScreenOrientation.LandscapeLeft;`
