### ISSUE TITLE
Cardboard on Unity: DllNotFoundException when running in Editor

### ISSUE THREAD

**Issue by ws18** [googlevr/cardboard#38]
Hello,

I am using Unity 2019.3.13. I have imported the package from https://github.com/googlevr/cardboard-xr-plugin
But if I try to run the sample I'm getting **DllNotFoundException: cardboard_api** and I cannot figure out how to fix this.

What am I missing?
Thanks in advance.

**Comment by synthercat** [comment]
Maybe you haven't actually imported the package then. Are you sure that the package list is updated with "Google Cardboard XR Plugin for Unity"? 
![Annotation 2020-05-20 103658](https://user-images.githubusercontent.com/15571710/82419797-83c1cc80-9a87-11ea-92ae-3aeae0c94bc7.jpg)
I had such an issue here: https://github.com/googlevr/cardboard/issues/37

Another thing is that you might neglected to switch tab to android on build settings or on XR plug-in manager:
![android](https://user-images.githubusercontent.com/15571710/82419743-77d60a80-9a87-11ea-9e33-4967ee2f492c.jpg)

**Comment by ws18** [comment]
The package is imported successfully.

By the way, the guide is outdated. If you try to git clone git@github.com:googlevr/cardboard-xr-plugin.git it says you don't have the rights to read it. So, I cloned by downloading the package and reading the json from Unity. Manually imported the Samples folder, followed the guide, still DllNotFoundException.

Please, update the guide at least...

**Comment by ws18** [comment]
I have deleted the project and started over. Still, the problem is the same. The package is imported successfully, but nothing. I'm attaching a screenshot for reference: https://imgur.com/gtYbkUT

Fun fact: the Cardboard XR Plugin disappears when you run the scene and encounter the DllNotFoundException. So you have to reboot Unity to start over.

I don't know where to look anymore.

**Comment by Zitronengras** [comment]
I experience the same error. I also use Unity 2019.3.13 and followed all instructions. Any ideas yet what the cause is and how to fix it?

**Comment by brotherlymite** [comment]
I've tried reimporting but still getting the same error (Unity 2020.2.0).

**Comment by SRochem** [comment]
Hello,

I have the same problem with Unity 2019.3.14f1
Everything goes well then I get this error when i try to launch the scene in the editor. 

I'm not a pro but what surprise me is that under "#elif UNITY_EDITOR" in "Google.XR.Cardboard" we have : CardboardApi = "NOT_AVAILABLE";
why does it search for cardboard_api ? It should do so in UNITY_ANDROID (CardboardApi = "cardboard_api";) not in editor, no ?

Can you guys build the project ? I can't, I get a black screen when I try on my android mobile.

**Comment by CarlBinneman** [comment]
Same situation

**Comment by ws18** [comment]
> 
> 
> Unity 2019.3.13f1
> This was fixed by enabling the deprecated "virtual reality supported" and adding the 'None' sdk.
> Answer courtesy of ArthurAtlantico on #35

Yes, however the problem persists in editor.

**Comment by jballoffet** [comment]
Thanks for reporting this. Cardboard XR Plugin is not able to run on the Unity Editor, it only runs on Android or iOS platforms. We will add to the backlog improving this by adding an error message when trying to run it there to make it clearer.

**Comment by agalbachicar-gg** [comment]
I failed to reproduce this error with recent version of the Cardboard XR Plugin. I particularly tried with Unity 2019.4.15f1 and 2020.2.0b13 targeting Android and Standalone (in editor and in the platform itself). Note that the plugin code will not run in the editor but the sample application behaviour should be noticed.

Please, do reopen the issue and provide us more details if the defect is still there for you.
