### ISSUE TITLE
git package gets broken iOS version 1.18.0 not fixed patch release 1.18.1

### ISSUE THREAD

**Issue by andypoly** [googlevr/cardboard#380]
How do I get the patch-fix version that works on iOS?
by Git URL in unity it is broken version, can you only manually download and add a patch 1.18.1 release?!

### SPECIFIC ISSUE ENCOUNTERED
git package gets broken iOS version 1.18.0 not fixed patch release 1.18.1

### SMARTPHONE (please complete the following information):
- Device: [e.g. iPhone 6]
- OS
  - [ ] Android
  - [ ] iOS
- OS version [e.g. 12]

### EXPECTED BEHAVIOR
Get's a working iOS version from git?!

### VERSIONS USED
trying to use latest

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
2020 LTS

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [ ] OpenGL ES3
   - [ ] Metal

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
**(This is not mandatory but it allows us to faster reproduce, prioritize, debug and fix the reported issue)**
[e.g. https://github.com/googlevr/cardboard]

### SCREENSHOTS
If applicable, add screenshots to help depict your problem.

**Comment by arilow** [comment]
Thanks @andypoly for reaching out to us! Unfortunately I am not being able to reproduce this issue with Xcode 14.0 and Unity 2020 LTS (2020.3.41f1). Bear in mind that the version string is still 1.18.0 but you may easily change it [here](https://github.com/googlevr/cardboard-xr-plugin/blob/master/package.json#L4) and [here](https://github.com/googlevr/cardboard-xr-plugin/blob/master/Runtime/UnitySubsystemsManifest.json#L3) on your end if needed. This will be solved on the next release of the Cardboard XR Plugin.


From #376, I see you are using Xcode 13.4.1. Could you please try updating your Xcode version and let us know how that goes?


Thanks!

**Comment by andypoly** [comment]
So how can I tell the difference between the releases to be sure I have the patched one?

**Comment by andypoly** [comment]
builds with xcode 14.1 anyway, thanks
