### ISSUE TITLE
[libunity.so] | After updating from Unity 2019.4.12f1 to 2021.3.11f1

### ISSUE THREAD

**Issue by sateyr** [googlevr/cardboard#387]
### SPECIFIC ISSUE ENCOUNTERED
I am getting these crashes after updating the App on Google Play

![image](https://user-images.githubusercontent.com/4160082/205910749-44c22a39-4327-4fd9-b109-488084af7e3d.png)

[libunity.so]
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.educainventions.heromask <<<

backtrace:
  #00  pc 0x000000000010762c  /data/app/~~c7_f-n8ydqn6MJsL--1dhQ==/com.educainventions.heromask-FbuKZD52bJoptUGglD1O2w==/lib/arm/libunity.so
  #01  pc 0x00000000001d214d  /data/app/~~c7_f-n8ydqn6MJsL--1dhQ==/com.educainventions.heromask-FbuKZD52bJoptUGglD1O2w==/lib/arm/libunity.so
  #02  pc 0x00000000002812db  /data/app/~~c7_f-n8ydqn6MJsL--1dhQ==/com.educainventions.heromask-FbuKZD52bJoptUGglD1O2w==/lib/arm/libunity.so
  #03  pc 0x00000000002819ed  /data/app/~~c7_f-n8ydqn6MJsL--1dhQ==/com.educainventions.heromask-FbuKZD52bJoptUGglD1O2w==/lib/arm/libunity.so
  #04  pc 0x000000000014f32b  /data/app/~~c7_f-n8ydqn6MJsL--1dhQ==/com.educainventions.heromask-FbuKZD52bJoptUGglD1O2w==/lib/arm/libunity.so
  #05  pc 0x000000000014f34d  /data/app/~~c7_f-n8ydqn6MJsL--1dhQ==/com.educainventions.heromask-FbuKZD52bJoptUGglD1O2w==/lib/arm/libunity.so
  #06  pc 0x000000000014f4e3  /data/app/~~c7_f-n8ydqn6MJsL--1dhQ==/com.educainventions.heromask-FbuKZD52bJoptUGglD1O2w==/lib/arm/libunity.so
  #07  pc 0x000000000023ed61  /data/app/~~c7_f-n8ydqn6MJsL--1dhQ==/com.educainventions.heromask-FbuKZD52bJoptUGglD1O2w==/lib/arm/libunity.so
  #08  pc 0x000000000024ebc1  /data/app/~~c7_f-n8ydqn6MJsL--1dhQ==/com.educainventions.heromask-FbuKZD52bJoptUGglD1O2w==/lib/arm/libunity.so
  #09  pc 0x00000000000f3a8d  /apex/com.android.art/lib/libart.so
```
- Unity Player Settings
Graphics APIs: OpenGLES2
Minimum API Level: 7.0 ´Nougat´
Target API Level: 31
Il2CPP
Target Architecture: ARMv7 and ARM64

### SMARTPHONE (please complete the following information):
- Devices: 
Redmi dandelion | Android 10 (SDK 29) 118 Events / 16.6% | OpenGL ES version 3.2
Samsung a03s | Android 12 (SDK 31) 61 Events / 8.6% | OpenGL ES version 3.2
OPPO OP4F97 | Android 11 (SDK 30) 42 Events / 5.9% | OpenGL ES version 3.2
ZTE P963F60 | Android 11 (SDK 30) 37 Events / 5.2% | OpenGL ES version 3.2

- OS
  - [x] Android
  - [ ] iOS

- OS version
Android 11 (SDK 30) 333 Events / 45.9%
Android 10 (SDK 29) 198 Events / 27.3%
Android 12 (SDK 31) 164 Events / 22.6%

### VERSIONS USED
**What version of Google Cardboard are you using?**
Google Cardboard XR Plugin for Unity 1.17.0

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Example: 2021.3.11f1

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [x] OpenGL ES3
   - [ ] Metal

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
The app can be downloaded, and opened on Google Play
https://play.google.com/store/apps/details?id=com.educainventions.heromask&hl=es&gl=US&pli=1

**Comment by arilow** [comment]
Thanks @sateyr for reaching out to us!


The Cardboard XR Plugin code is in `libGfxPluginCardboard.so`, so if your crash was related to Cardboard, you should be seeing calls to that binary in the backtrace.


On the other hand, in your issue, it is stated that your App uses OpenGL 2:
```
Graphics APIs: OpenGLES2
```


But when you share the devices that are having problems, they seem to be using OpenGL 3.2:
```
Redmi dandelion | Android 10 (SDK 29) 118 Events / 16.6% | OpenGL ES version 3.2
Samsung a03s | Android 12 (SDK 31) 61 Events / 8.6% | OpenGL ES version 3.2
OPPO OP4F97 | Android 11 (SDK 30) 42 Events / 5.9% | OpenGL ES version 3.2
ZTE P963F60 | Android 11 (SDK 30) 37 Events / 5.2% | OpenGL ES version 3.2
```
Which one is the correct version?


Since there are no mentions of the Cardboard XR Plugin in the error logs, it might be possible that the culprit dependency is a different one. We suggest you try to reproduce the issue by bumping the Unity version while not using the Cardboard XR Plugin and check whether it still takes place.


In order to help you debug this, please provide us with a simple repro project where your issue can be depicted.


Thanks!

**Comment by sateyr** [comment]
I have uploaded a new version to google play with the debug symbols, and i have get more datails about the user errors.

`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 7276 >>> com.educainventions.heromask <<<

backtrace:
  #00  pc 0x000000000010762c  /data/app/~~EBgbji28Qn6oLKLMTD2yWw==/com.educainventions.heromask-HYt_oLqSQwlwy-K_yE6N1w==/lib/arm/libunity.so (RenderTexture::SetSRGBReadWrite(bool))
  #01  pc 0x00000000001d214d  /data/app/~~EBgbji28Qn6oLKLMTD2yWw==/com.educainventions.heromask-HYt_oLqSQwlwy-K_yE6N1w==/lib/arm/libunity.so (GenerateEnvironmentData(int, float*, bool))
  #02  pc 0x00000000002812db  /data/app/~~EBgbji28Qn6oLKLMTD2yWw==/com.educainventions.heromask-HYt_oLqSQwlwy-K_yE6N1w==/lib/arm/libunity.so (EnlightenRuntimeManager::UpdateEnvironmentLighting())
  #03  pc 0x00000000002819ed  /data/app/~~EBgbji28Qn6oLKLMTD2yWw==/com.educainventions.heromask-HYt_oLqSQwlwy-K_yE6N1w==/lib/arm/libunity.so (EnlightenRuntimeManager::Update())
  #04  pc 0x000000000014f32b  /data/app/~~EBgbji28Qn6oLKLMTD2yWw==/com.educainventions.heromask-HYt_oLqSQwlwy-K_yE6N1w==/lib/arm/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*))
  #05  pc 0x000000000014f34d  /data/app/~~EBgbji28Qn6oLKLMTD2yWw==/com.educainventions.heromask-HYt_oLqSQwlwy-K_yE6N1w==/lib/arm/libunity.so (ExecutePlayerLoop(NativePlayerLoopSystem*))
  #06  pc 0x000000000014f4e3  /data/app/~~EBgbji28Qn6oLKLMTD2yWw==/com.educainventions.heromask-HYt_oLqSQwlwy-K_yE6N1w==/lib/arm/libunity.so (PlayerLoop())
  #07  pc 0x000000000023ed61  /data/app/~~EBgbji28Qn6oLKLMTD2yWw==/com.educainventions.heromask-HYt_oLqSQwlwy-K_yE6N1w==/lib/arm/libunity.so (UnityPlayerLoop())
  #08  pc 0x000000000024ebc1  /data/app/~~EBgbji28Qn6oLKLMTD2yWw==/com.educainventions.heromask-HYt_oLqSQwlwy-K_yE6N1w==/lib/arm/libunity.so (nativeRender(_JNIEnv*, _jobject*))
  #09  pc 0x000000000001de13  /data/app/~~EBgbji28Qn6oLKLMTD2yWw==/com.educainventions.heromask-HYt_oLqSQwlwy-K_yE6N1w==/oat/arm/base.odex`

I have deleted OPENGLES2 and it's working now (https://forum.unity.com/threads/android-crash-with-enlighten-after-upgrade-to-unity-2021-lts.1267358/)

Thanks for all ^^
