### ISSUE TITLE
Failed to compile on Android

### ISSUE THREAD

**Issue by ricardoquesada** [googlevr/cardboard#390]
### SPECIFIC ISSUE ENCOUNTERED
Cannot compile SDK on Android. Using ToT.

### SMARTPHONE (please complete the following information):
- Device: Pixel 6a
- OS
  - [X] Android
  - [ ] iOS
- OS version: 12

### STEPS TO REPRODUCE THE ISSUE

Context: Linux machine

`ANDROID_HOME` points to correct location. 

```
$ git clone --recursive https://github.com/googlevr/cardboard.git
$ cd cardboard
$ ./gradlew installDebug
```

Error is:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':hellocardboard-android:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/ricardoq/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /mnt/src/cardboard/hellocardboard-android/.cxx/cmake/debug/armeabi-v7a cardboard_jni}
  ninja: Entering directory `/mnt/src/cardboard/hellocardboard-android/.cxx/cmake/debug/armeabi-v7a'
  
  ninja: error: '/home/ricardoq/src/cardboard/hellocardboard-android/libraries/jni/armeabi-v7a/libGfxPluginCardboard.so', needed by '/home/ricardoq/src/cardboard/hellocardboard-android/build/intermediates/cmake/debug/obj/armeabi-v7a/libcardboard_jni.so', missing and no known rule to make it
```

### EXPECTED BEHAVIOR
Should Compile Ok

### VERSIONS USED
**What version of Google Cardboard are you using?**

Cardboard SDK 1.19.0 (which is ToT as of Today)
Hash: e17632c2f6e5ffe3c807bb138153a05a35f7a6fe

### ADDITIONAL CONTEXT
Using Linux, Debian (sort of)

**Comment by arilow** [comment]
Thanks @ricardoquesada for reaching out to us!


Before building the Hello Cardboard native sample it is necessary to build the SDK. You can take a look at the [Quickstart for Google Cardboard for Android NDK](https://developers.google.com/cardboard/develop/c/quickstart)


In case you want to build it from terminal, I suggest you to try these steps:


```
$ git clone --recursive https://github.com/googlevr/cardboard.git
$ cd cardboard
$ ./gradlew sdk:assemble
$ ./gradlew assemble
$ ./gradlew installDebug
```


Please let us know if you get any errors after following those steps.
Thanks!

**Comment by ricardoquesada** [comment]
Thanks. This is very useful info... Yes, I went to the link you mentioned, but it didn't include the "command line" option.

Not sure how many people use command line, but would be great to the command line info in the "Quickstart" as well.
