### ISSUE TITLE
Spining effect on ios 16

### ISSUE THREAD

**Issue by MuhammadSafyan** [googlevr/cardboard#392]
facing the spinning effect on vr enable on ios.
iphone xs.
unity 2019 lts
google vr latest sdk.
https://www.youtube.com/watch?v=N0sFKZmJfpE&t=8s
you can check video

**Comment by arilow** [comment]
Thanks @MuhammadSafyan for reaching out to us!

Google VR is deprecated. We suggest you use Cardboard OSS which has already solved that bug.

You can follow the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart) to get started. Please take into account that you will need Unity 2020 lts or later.

Let us know if you need help regarding your setup with Cardboard OSS
Thanks!

**Comment by MuhammadSafyan** [comment]
> Thanks @MuhammadSafyan for reaching out to us!
> 
> Google VR is deprecated. We suggest you use Cardboard OSS which has already solved that bug.
> 
> You can follow the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart) to get started. Please take into account that you will need Unity 2020 lts or later.
> 
> Let us know if you need help regarding your setup with Cardboard OSS Thanks!

Thanks its solved my problem
