### ISSUE TITLE
Y

### ISSUE THREAD

**Issue by tran09** [googlevr/cardboard#393]
### SMARTPHONE (please complete the following information):
- Device: [e.g. iPhone 6]
- OS
  - [ ] Android
  - [x] iOS
- OS version [e.g. 12]

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard SDK/Cardboard XR Plugin 1.4.1/1.5.0/1.6.0/1.7.0...

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Example: 2019.4.25f1

- Select in which graphics API you can reproduce the bug.
   - [x] OpenGL ES2
   - [x] OpenGL ES3
   - [x] Metal

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
**(This is not mandatory but it allows us to faster reproduce, prioritize, debug and fix the reported issue)**
[e.g. https://github.com/googlevr/cardboard]

### SCREENSHOTS
If applicable, add screenshots to help depict your problem.

**Comment by tran09** [comment]
Nice

**Comment by tran09** [comment]
For example

**Comment by tran09** [comment]
Bug

**Comment by arilow** [comment]
Thanks @tran09 for reaching out to us. I'm closing this issue as it has no description.


Feel free to create another one if you need help regarding the Cardboard SDK or the Cardboard XR Plugin.


Thanks!
