### ISSUE TITLE
Lenses do not take full screen on IPhone 8 Plus

### ISSUE THREAD

**Issue by Lasbleic** [googlevr/cardboard#394]
### SPECIFIC ISSUE ENCOUNTERED
We have two version of our app built via Unity:
- One is built for iOS thanks to Google Cardboard XR Plugin
- One is built for Android thanks to Google VR Cardboard
On the version for iOS, the lenses do not take the full screen, while on the Android version it does (See attached screenshots)

##### iPhone 8 Plus
- Device: iPhone 8 Plus
- OS
  - [ ] Android
  - [X] iOS
- OS version : iOS 16.0
- Resolution: 1920*1080

##### Huawei p20 pro
- Device: Huawei p20 pro
- OS
  - [X] Android
  - [ ] iOS
- OS version : Android 10 (EMUI 12)
- Resolution: 2240*1080

### EXPECTED BEHAVIOR
I would expect lenses to take the full width and height of the screen. Am I missing a parameter somewhere ?

### VERSIONS USED
For iOS: Cardboard XR Plugin 1.9
For Android: Cardboard VR 2.0
Both use Unity 2019.4.27f1

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES2
   - [X] OpenGL ES3
   - [ ] Metal

### SCREENSHOTS
On iOS:
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/52287780/214053664-937b335e-2e86-45a5-b8d1-f2921a75d99f.png)

On Android:
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/52287780/214053716-de51c53e-5789-46fb-b2ee-8072a1315567.png)

**Comment by arilow** [comment]
Thanks @Lasbleic for reaching out to us!


Depending on the Cardboard viewer and the specs of the phone, the eyes may (or may not)  take the full screen. In your case:

1. Which viewer are you using?
2. Are you using the same viewer for both devices?


Knowing that would allow us to help you debug this issue.
Thanks!

**Comment by Lasbleic** [comment]
Thank you for your fast answer!

We are using default viewer configuration in both case. I guess they differ from one phone to another, or maybe between the two versions of the Cardboard SDK (VR and XR) ?

Is there any way to modify these viewer configurations directly in our Unity Application ? Or is it mandatory to use the Google Cardboard application to scan the viewers QR Code ?

It would be very helpful to pre-register some configurations to avoid our clients downloading another application and doing extra steps.

**Comment by Lasbleic** [comment]
Thank you very much for your detailed answer
