### ISSUE TITLE
Viewer Profile Generator site fails to show link at STEP 2

### ISSUE THREAD

**Issue by shinji-yoshida** [googlevr/cardboard#396]
Hi,
[Viewer Profile Generator](https://wwgc.firebaseapp.com/) fails to show link at STEP 2.
This issue has already been reported (https://github.com/google/wwgc/issues/8), but maintainers don't seem to be aware of it.

**Comment by arilow** [comment]
Thanks @shinji-yoshida for reporting this issue. It has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it.

**Comment by arilow** [comment]
Closing as this is fixed now.
