### ISSUE TITLE
Android 12 - Doesn't work constantly crashes.

### ISSUE THREAD

**Issue by AndreySkyFoxSidorov** [googlevr/cardboard#408]
CRASH app after scanning QR code on Android 12.
Phone Samsung S21

**Comment by arilow** [comment]
Thanks @AndreySkyFoxSidorov for reporting this issue. 


I confirm I’m able to repro de issue locally when setting Vulkan as graphics API. It has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it.


In the meantime, as a workaround you could try running the sample with OpenGL ES 3 as graphics API, please let us know how that goes.


Thanks!

**Comment by AndreySkyFoxSidorov** [comment]
> 
I have examined the cardboard SDK for implementation in the project. Unfortunately, this library is in a very raw Alpha state (((, and it is disappointing that there hasn't been a stable version after all these years. Additionally, I don't understand why it doesn't utilize the cross-platform capabilities of the Unity engine, for which it is designed. Most of the necessary functionality is already present in the engine's standard features. It's unclear to me why lens curvature calculations and downloading configuration settings have been transferred to native code. Furthermore, the SDK is lacking in functions for adjusting lenses for children and changing the eye distance for the user.
The competitors of cardboard have many solutions that are significantly better thought out. Unfortunately, we will refrain from further work with this SDK until it becomes more mature. Crashes and the complexity of fixing errors due to the native functionality make this concept unprofitable.
Please take note of my observations and consider the possibility of improving the library's functionality. I hope for your understanding and willingness to address these factors in future development.

**Comment by dletozeun** [comment]
Hi Andrey, thank you for your insights. May I ask what competitors are you considering in this regard?
