### ISSUE TITLE
Cardboard XR Plugin not present in XR Plug-in Management Settings

### ISSUE THREAD

**Issue by Rovexx** [googlevr/cardboard#41]
**Problem**
I started a new Unity project and followed the quickstart instructions.
But when selecting the Plug-in provider for XR the Cardboard XR Plugin does not show up in the list.

**Available options**
I have the following options available.
![image](https://user-images.githubusercontent.com/32699476/82534733-ea0d2480-9b45-11ea-9469-a99ba688a76a.png)

**What I tried**
I have installed the XR Plug-in Management and the Google Cardboard XR Plugin for unity.
I succesfully completed all previous steps from the quickstart guide.
I am using Unity 2019.3.14f1
I have redone the entire setup process multiple times.
I tried reimporting the Cardboard XR plugin and XR Plugin Management.

**Comment by lexar** [comment]
Hi, try to enable iOS support for the project. The cardboard XR plugin appeared only after I enabled support for both iOS and Android.

**Comment by Rovexx** [comment]
Downloading the iOS build support fixed the issue. the plugin is now available.
