### ISSUE TITLE
Update project "hellocardboard-android" to build in recent Android Studio

### ISSUE THREAD

**Issue by tellypresence** [googlevr/cardboard#410]
"hellocardboard-android" has several things broken when attempting to build on modern Android Studio (e.g. "Flamingo"); as is often the case, fixing the initial errors allows the build to proceed further, and illuminates other problems downstream

### Errors and warnings encountered when attempting to build the project "out of the box"
(this is with an arm64 device attached via usb cable as usual)

_`libGfxPluginCardboard.so` error_
```
ninja: error: '../../../../libraries/jni/arm64-v8a/libGfxPluginCardboard.so', needed by \
    '../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libcardboard_jni.so', \
   missing and no known rule to make it
```

_`opens java.io` error_
```
Unable to make field private final java.lang.String java.io.File.path accessible: \
    module java.base does not "opens java.io" to unnamed module @6952e86e
```

_API level warning_
```
AGPBI: {"kind":"warning","text":"An API level of 31 is not supported by this compiler. \
    Please use an API level of 30 or earlier","sources":[{}],"tool":"D8"}
```

### Update AGP to 7.0.2*, compile/target APIs to 33
*that's right, "Flamingo" prefers AGP 8.0.1, but that in turn requires updating gradle to 8.X, and then moving package names out of manifest files and into `namespace` blocks in both `app` and `sdk` `build.gradle` files -- so deliberately undershot the newest possible AGP version to minimize the hassle of getting the project to a buildable state

After the above modification, will need to make a few more changes to get the project to build

_SDK XML version warning_
```
This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 \
    was encountered. This can happen if you use versions of Android Studio and the \
    command-line tools that were released at different times.
```

#### Hack to fix missing `.so` lib
The `.so` lib is generated, but the `.aar` generation seems to fail; anyway the library can't be located in its original location.  To fix the file simply needs to be copied to where it is expected to be located...

Look for this file:
`sdk/build/intermediates/cmake/debug/obj/arm64-v8a/libGfxPluginCardboard.so`
Create the 3 nested subfolders `libraries/jni/arm64-v8a` under `hellocardboard-android` and copy the file to this location; when finished you should have:
`hellocardboard-android/libraries/jni/arm64-v8a/libGfxPluginCardboard.so`

#### Hack to fix missing `cardboard.h` header
```
In file included from cardboard/hellocardboard-android/src/main/jni/hello_cardboard_jni.cc:22:
cardboard/hellocardboard-android/src/main/jni/hello_cardboard_app.h:29:10: fatal error: 'cardboard.h' file not found
```
In files
 - `hellocardboard-android/src/main/jni/hello_cardboard_app.h`
 - `hellocardboard-android/src/main/jni/hello_cardboard_app.cc`
 Replace line
```
#include "cardboard.h"
```
with
```
#include "../../../../sdk/include/cardboard.h"
```

#### To fix the `opens java.io` error
In project root level (not "app" module!) `build.gradle` update from
```
classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.18'
```
to
```
classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.1'
```

With these changes the project should build and run (will still be some complaints about the android SDK version)

Caveat: the above instructions contain some ugly hacks so are not tenable for a production pipeline, but if your interest is to quickly build a demo project to be able to check code against a running app it may suffice to get you started.

"Cardboard" headset viewer optional, won't need one to run the sample app
<img src="https://github.com/googlevr/cardboard/assets/26958898/188d0011-1eba-46ca-85e8-00c4ee77db77" alt="hello_cardboard_android_no_viewer_required" width=320>

**Comment by arilow** [comment]
Thanks @tellypresence for reaching out!

I was able to reproduce the error you are mentioning by trying to build the hellocardboard-android sample without building the Cardboard SDK.

By taking a look at the [Quickstart](https://developers.google.com/cardboard/develop/c/quickstart#download_and_build_the_demo_app), step 3 builds the SDK and step 4 builds the sample.

I’m closing this issue as it should be resolved. Please feel free to reopen if that is not the case and share:

- Steps required to reproduce the issue.
- A repro project where the issue can be reproduced. It's ok if it is a simple Cardboard project.

Thanks!
