### ISSUE TITLE
Advice for parallel build for Quest 2?

### ISSUE THREAD

**Issue by rev111** [googlevr/cardboard#421]
Hello!
I built a Cardboard application for Android with Unity. Now I would like to build this app for a Meta Quest 2 without losing the ability to build for phones with cardboard. Has anyone here done this already and has advice what I should prepare to avoid problems? For example, turn on/off specific player/build/platform settings?

**Comment by arilow** [comment]
Thanks @rev111 for reaching out!


Unfortunately, we don’t have experience integrating Cardboard and the Meta Quest 2 on the same project and we can’t help you with that. I'm leaving this issue open as a question in case someone from the community is able to help here.


Thanks!

**Comment by arilow** [comment]
Closing this as there hasn't been any activity in a while. 

Feel free to reopen if this is still relevant for you.

Thanks.
