### ISSUE TITLE
Is there a timeline for fixing Upside Down rendering known issue?

### ISSUE THREAD

**Issue by julien-tamade** [googlevr/cardboard#424]
I saw in the latest release notes about the known issue of upside down rendering on iOS. We've been experiencing that issue and were wondering if there's a timeline to fix it?

Thank You!

**Comment by omargda** [comment]
+1, I've also been experiencing this and am wondering when we'll get a fix. Thanks!

**Comment by arilow** [comment]
Thanks @julien-tamade for reaching out to us. This bug was solved on the Unity side. We confirmed it is solved from the following versions on:
- 2021.3.28f1
- 2022.2.17f1
- 2022.3.5f1


Please let us know if anything.
Thanks!
