### ISSUE TITLE
App does not quit on close button

### ISSUE THREAD

**Issue by yoegshmore77** [googlevr/cardboard#426]
Hi

When I press the close button "X" the app comes out of the VR mode but it won't get closed. Any idea how to handle this issue.

Device Android version - 12
Unity version - 2021.3.12f1
Cardboard XR Plugin v1.21.0

Regards
Yogesh

**Comment by Mandelbrow** [comment]
Hi,

Perhaps you need to enable the "Input Manager (Old) in the Player settings?
Check this thread in Unity Forum:
[https://forum.unity.com/threads/xr-features-gear-setting-icon-and-close-button-of-cardboard-vr-mask-not-responding.1323852/](url)

**Comment by yoegshmore77** [comment]
Hi Mandelbrow

Thanks for the reply...

At Project Settings > Player > Active Input Handling* > select "Both" option.

Have tried this as mentioned in the post but no luck...

On click of the cross button the VR mode toggles between  stereo to mono and viceversa but the app doesnt quit...

**Comment by Mandelbrow** [comment]
Then maybe something else is missing? 
It's not the Cardboard SDK that quits your app. 

You need a script to check for _Api.IsCloseButtonPressed_, and then take necessary actions to quit the app. For example by calling _Application.Quit();_.

**Comment by yoegshmore77** [comment]
Hi Mandelbrow

Thanks for pointing that out...Have tried this and it worked....

            if (Api.IsCloseButtonPressed)
            {
                //ExitVR();
                Application.Quit();
            }

Thanks once again
Regards

**Comment by arilow** [comment]
Closing as this seems to be fixed. 

Thanks!

**Comment by ezemanoukian** [comment]
Thanks, it worked for me!

**Comment by ezemanoukian** [comment]
> Hi Mandelbrow
> 
> Thanks for pointing that out...Have tried this and it worked....
> 
> ```
>         if (Api.IsCloseButtonPressed)
>         {
>             //ExitVR();
>             Application.Quit();
>         }
> ```
> 
> Thanks once again Regards

Thanks! It worked for me.
