### ISSUE TITLE
Unreal Engine 5 ?

### ISSUE THREAD

**Issue by 1unknwn** [googlevr/cardboard#431]
Guys can you please comeback to Unreal Engine 5 ? Since it was deprecated ages ago. This project is actively development for Unity but not Unreal Engine.

**Comment by kafumanto** [comment]
Hi, I don't share any link because it could be inappropriate, but we developed a plugin for Unreal Engine 4/5 integrating this SDK. You can find it searching for "Cardboard" in the Unreal Engine Marketplace. Just to avoid any misunderstanding, it's a paid plugin.
