### ISSUE TITLE
The view rendering in the iPhone 15 pro not a full view

### ISSUE THREAD

**Issue by tomsuperman** [googlevr/cardboard#433]
### SMARTPHONE (please complete the following information):
- Device: [ iPhone 15 pro]
- OS
  - [ ] iOS
- OS version [e.g. 17.0.2]

### STEPS TO REPRODUCE THE ISSUE
Build to iPhone 15 pro and open the App directly.

### EXPECTED BEHAVIOR
View is only render about half of the iPhone screen. App works fine with iPhone 12 pro and iPhone 13 with iOS 17.0.

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard SDK/Cardboard XR Plugin v.1.21

**If you are using Cardboard XR Plugin:**
- What version of Unity are you using?
Example: 2021.3.1

- Select in which graphics API you can reproduce the bug.
   - [ ] OpenGL ES3

### SCREENSHOTS
![screenshot](https://github.com/googlevr/cardboard/assets/7873823/43779e40-3820-42bf-ad40-a1705ecd0d9f)

**Comment by tomsuperman** [comment]
fixed with #144

**Comment by julien-tamade** [comment]
This happens every time a new version of the iPhone comes out. We always need a new version of the plugin to support fullscreen view for that phone

**Comment by xinyunh0929** [comment]
This was fixed in v1.22.0.
