### ISSUE TITLE
Remove eye mask

### ISSUE THREAD

**Issue by DaReign** [googlevr/cardboard#448]
### SPECIFIC ISSUE ENCOUNTERED
I want to remove eye mask. I want to have just split screen with headtracking is this possible to archive ? Isuppose yu don't provided api for this but maybe I can change sdk source code for that ?

### SMARTPHONE (please complete the following information):
Android

**If you are using Cardboard XR Plugin:**
Unity 2021.3.25

**Comment by DaReign** [comment]
Second question how to add labels for issues because every at start get bug label but this is not a bug just feature request / assist

**Comment by Mandelbrow** [comment]
Why do you want to render the full view? Any part outside what's visible in the headset is just a waste of gpu, and cpu cycles.

**Comment by DaReign** [comment]
I know is strange but this is one of requirement I got for the app :) I know that I easily could do it in much older version of unity (which doesn't need sdk)  but I don't know how to do this with this sdk. So is it possible to do that or maybe to manipulate mask that render for each eye fill as much area as it is possible leaving black area just on the edge ? And I obviously don't think about creating profile because as I understand it don't work in that way that at on every phone it will try fill as much space as it possible or maybe I am wrong and I can do this pragmatically. So goal is that user after firing application have as much render for each eye as possible. I think removing mask shouldn't be  hard but I just don't know where turn it off.

**Comment by DaReign** [comment]
Is this possible to archive by XR module from Unity ? Because I didn't find code in sdk which do that.

**Comment by lneumarkt** [comment]
Thank you for reaching out to us!

Cardboard doesn’t use a mask to create the stereoscopic effect. Instead,  it renders two distorted images as eye textures onto the display. You can find the code that renders the eye textures in [this link](https://github.com/googlevr/cardboard/blob/master/sdk/unity/xr_unity_plugin/opengl_es3_renderer.cc#L225C1-L236C4).

If you just want to have the split screen easily, a workaround is to use the [Cardboard Viewer Generator](https://wwgc.firebaseapp.com/) and set the distortion coefficient to a low value (e.g: 0,0001) leaving all the other parameters as default. That would generate a QR code that contains your viewer profile with no eye distortion. You can then scan that QR code to apply your profile to your app.
The following image shows the sample app with a distortion coefficient of `k=0.0001`.

![HelloCardboard_without_distortion](https://github.com/googlevr/cardboard/assets/78873247/e4ec6f95-14d6-4008-8674-bd6e231f3906)


Another approach could be to modify the [RenderEyeToDisplay](https://github.com/googlevr/cardboard/blob/master/sdk/unity/xr_unity_plugin/opengl_es3_renderer.cc#L225) function, and replace the [CardboardDistortionRenderer_renderEyeToDisplay](https://github.com/googlevr/cardboard/blob/master/sdk/unity/xr_unity_plugin/opengl_es3_renderer.cc#L232) with a custom C++ class that renders the eyes as squares, without any distortion. To avoid reinventing the wheel, you can use the [RenderWidget](https://github.com/googlevr/cardboard/blob/master/sdk/unity/xr_unity_plugin/opengl_es3_renderer.cc#L252) function, which renders the `x` and gear widgets as 2 squared images.


Let us know if you need further help. 
Thanks!

**Comment by arilow** [comment]
Closing as it's been a while since the last comment. In case this is still an issue for you, please feel free to reopen this ticket. Thanks!
