### ISSUE TITLE
How to import The SDK into Android Studio

### ISSUE THREAD

**Issue by mrtineu** [googlevr/cardboard#449]
I know it is a silly question but because the lack of explenatory docs I cant find how to import into new android project without the sample app.

**Comment by lneumarkt** [comment]
Thank you for reaching out to us!

To integrate the Cardboard SDK to an existing Android project you would need to follow these steps:
1. Clone the [cardboard repository](https://github.com/googlevr/cardboard).
2. In Android Studio, import the [cardboard](https://github.com/googlevr/cardboard) project into your Android project by following [these steps](https://developer.android.com/studio/projects/add-app-module#ImportAModule). 
   1. Click `File > New > Import Module`.
   2. In the Source directory box, type or select the directory of the Cardboard folder.
   3. Uncheck the `hellocarboard-android` module to only import the SDK module.

![import_sdk_android_studio](https://github.com/googlevr/cardboard/assets/78873247/14c3b429-2101-4e13-b592-81a8a214adba)


3. Copy the [proto](https://github.com/googlevr/cardboard/tree/master/proto) and [third party](https://github.com/googlevr/cardboard/tree/master/third_party/unity_plugin_api) folders into your project’s root directory.
4. If necessary: Add the following line in the sdk [build.gradle](https://github.com/googlevr/cardboard/blob/master/sdk/build.gradle#L4) file with inside de android scope:
“com.google.cardboard.sdk”.


- Another solution could be to open the Cardboard project and remove the [helloCardboard-android](https://github.com/googlevr/cardboard/tree/master/hellocardboard-android) folder.


Please let us know if you need further help integrating your project with the Cardboard SDK..


Thanks!

**Comment by arilow** [comment]
Closing as this seems to be fixed
