### ISSUE TITLE
toggle between VR on and off?

### ISSUE THREAD

**Issue by friggasaint** [googlevr/cardboard#45]
Is it possible to reliably turn VR on and off?
I succeed in dynamically starting VR mode by calling :
**XRGeneralSettings.Instance.Manager.InitializeLoader()  (async)
XRGeneralSettings.Instance.Manager.StartSubsystems()**

But as I try to switch off VR:
**XRGeneralSettings.Instance.Manager.StopSubsystems()**
The left eye camera is just pulled onto the whole screen, which gives a distorted view.
Also calling 
**XRGeneralSettings.Instance.Manager.DeinitializeLoader()**
crashes the application as I try to dynamically try to turn VR mode on again, which is no problem without deinitialize.

Unity 2019.3.13f1
XR Plugin Management 3.2.9
Cardboard XR Plugin for unity 1.1.0

**Comment by JacobBWaggoner** [comment]
Try running cam.ResetAspect(); after stopping subsystems, that seems to fix it on our end!

**Comment by friggasaint** [comment]
Works perfectly for me as well.
Thank you!

**Comment by MrETea** [comment]
Hey all! We are having issues with switching VR on and off as the initial bug mentioned.

When we try to start VR for a second time Android crashes.
With the above steps we've managed to get it to not crash, in the non-VR scene the camera doesn't render/everything is black.

Can anyone help?

**Comment by JacobBWaggoner** [comment]
What Unity version are you using? We had that problem on 2019.3.15, but not on 2019.3.12! I'm not sure why, but have been focusing on other issues and rolled back to 12 to focus on those.

**Comment by MrETea** [comment]
> What Unity version are you using? We had that problem on 2019.3.15, but not on 2019.3.12! I'm not sure why, but have been focusing on other issues and rolled back to 12 to focus on those.

Thanks for the reply! We are using 2019.3.15, so we are going to try to downgrade and see how we go.

I would suggest that considering this is such a painful crash bug, and 100% reproducible, that the thread be reopened? Or should a new one be started? @jballoffet what would be the best process here.

**Comment by JoaoBorks** [comment]
PR #124 fixes the crash on starting the VR a second time.
