### ISSUE TITLE
Where is the Unity package to import?

### ISSUE THREAD

**Issue by 253153** [googlevr/cardboard#466]
Hi, I'd love to use this SDK, where is the download for the Unity package?

**Comment by lneumarkt** [comment]
Thanks @253153 for reaching out!

Here is the link to the [Cardboard XR Plugin](https://github.com/googlevr/cardboard-xr-plugin).

You can follow the [Quickstart for Unity](https://developers.google.com/cardboard/develop/unity/quickstart) to get started. Please take into account that you will need a [Unity version supported by Cardboard](https://developers.google.com/cardboard/develop/unity/quickstart#set_up_your_development_environment).

Let us know if you need help regarding your setup with Cardboard OSS.
Thanks!

**Comment by arilow** [comment]
Closing as this seems to be solved.
