### ISSUE TITLE
Feature Request: GvrReticlePointer prefab in Unity.

### ISSUE THREAD

**Issue by ws18** [googlevr/cardboard#47]
Is it possible to have back GvrReticlePointer prefab? It was useful to give the user a proper feeback wether they were looking on special object or not.

**Comment by jballoffet** [comment]
Thanks for requesting the feature, adding the reticle is on our roadmap. Please star or watch this issue to be notified when it becomes available.

**Comment by Sourcetreehugger** [comment]
Any updates on this?

**Comment by Sourcetreehugger** [comment]
I ended up using the reticle from the old google vr package.

**Comment by julien-tamade** [comment]
@Sourcetreehugger can you elaborate on how you did that?

**Comment by Sourcetreehugger** [comment]
Hey Julien. You used the old package before right? If you parent the reticle from the old package under the main camera you can use it. Maybe you will also need an event system to handle pointer events. Check out the HelloVR scene from the old package.

**Comment by julien-tamade** [comment]
> Hey Julien. You used the old package before right? If you parent the reticle from the old package under the main camera you can use it. Maybe you will also need an event system to handle pointer events. Check out the HelloVR scene from the old package.

Thank You! I got a hacked together version working doing essentially what you said. Calling the OnPointerEnter and OnPointerExit functions and tweaking things a big.

**Comment by jballoffet** [comment]
This feature has not been prioritized in the short run, nevertheless, if you want to send your proposed changes, please read CONTRIBUTING.md and follow the process. Patches are welcome.

**Comment by JoaoBorks** [comment]
I've requested googlevr/cardboard-xr-plugin#13 that adds the Gaze Pointer

**Comment by lz7cjc** [comment]
> 
> 
> This feature has not been prioritized in the short run, nevertheless, if you want to send your proposed changes, please read CONTRIBUTING.md and follow the process. Patches are welcome.

Google Cardboard is a fantastic entry point for VR. So we need to offer this functionality. Without it you need a working button or handles to control the experience. The buttons don't always work on the cheap headsets and people aren't necessarily going to have controllers given this is a budget solution. 

So why isn't it priority? What is more important than being able to control the experience?

**Comment by xinyunh0929** [comment]
This is merged in v1.20.0
