### ISSUE TITLE
Problem building w/NDK v27 due to removed function ALooper_pollAll()

### ISSUE THREAD

**Issue by tellypresence** [googlevr/cardboard#474]
As discussed/mentioned in
- https://github.com/android/ndk/discussions/2020
- https://github.com/microsoft/vcpkg/issues/40268

Cardboard config failing with NDK v27 due to removed function `ALooper_pollAll()`

Possible solution: replace w/`ALooper_pollOnce()`

**Comment by lneumarkt** [comment]
Thanks @tellypresence for reaching out and reporting the issue you encountered.

I confirm that I’m able to reproduce the issue.
Your proposed solution has already been internally merged and it will be included in v1.26.0.

Thanks!

**Comment by xinyunh0929** [comment]
This was fixed in v1.26.0.
