### ISSUE TITLE
No 3D depth in cardboard

### ISSUE THREAD

**Issue by hgabor47** [googlevr/cardboard#57]
I built the hellocardboard sample code and I recognised that the left and right eye created from same position. No 3D depth feelings only flat fixed depth length. How I can set 3D stereo?
I have 2560x1440 phone resolution and Gear VR. The VR set by right QRCode. 
What can I do? 
![image](https://user-images.githubusercontent.com/1212585/83953982-55910a80-a845-11ea-94f6-a560921b47b0.png)
(You can see this image with crosseye method if you want)

**Comment by hgabor47** [comment]
I built a similar space with blender for crosseye method so you can feel the 3D in this picture
![stereogood](https://user-images.githubusercontent.com/1212585/83970035-9e8fa000-a8d3-11ea-88e6-ee1f25787370.png)

**Comment by hgabor47** [comment]
Is anybody else not recognise this problem?

**Comment by jballoffet** [comment]
Based on what can be seen in the provided pictures, it seems that the viewer being used has very little parallax (both eyes images are too similar). Take into consideration that Gear VR is not an official Google Cardboard viewer. My suggestion is to try a different viewer and share the QR code being used if the problem persists.

**Comment by spectrowolf13** [comment]
> Is anybody else not recognise this problem?

Me too and I dont found a solution yet.

**Comment by jballoffet** [comment]
Closing this issue because it is device (viewer) related. If you think there is anything in the library that is affecting the experience with this device please open a new ticket.
