### ISSUE TITLE
Cannot found libcardboard_api.so.

### ISSUE THREAD

**Issue by grp0916** [googlevr/cardboard#58]
ninja: error: '../../../../libraries/jni/arm64-v8a/libcardboard_api.so', needed by '../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libcardboard_jni.so', missing and no known rule to make it

**Comment by Kopilov** [comment]
Have you built the SDK module library?
Look https://github.com/googlevr/cardboard/issues/26  and
 https://developers.google.com/cardboard/develop/c/quickstart#download_and_build_the_demo_app, "To assemble the Cardboard SDK, double-click the assemble option within cardboard/:sdk/Tasks/build folder in the Gradle tab (View > Tool Windows > Gradle)."

**Comment by jballoffet** [comment]
as @Kopilov said, you need to generate the SDK's AAR first (which includes native libraries among other stuff), before building the sample app. Please take a look at #9.
