### ISSUE TITLE
The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor

### ISSUE THREAD

**Issue by LuisAngelGR** [googlevr/cardboard#60]
hello I am using unity 2019.4.0f1 (Android) and I have some problems, the first one is the one I leave below

"The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor'"
![image](https://user-images.githubusercontent.com/31941637/84357415-3b2f9780-ab8b-11ea-8fab-fd41ec935e6c.png)

I tried to remove some of the code that causes the error and it works, the error disappears, now I can enter to play mode  but others appear, which are as follows

"DllNotFoundException: cardboard_api"
"SendMessage OnPointerEnter has no receiver!"
"SendMessage OnPointerExit has no receiver!"
![image](https://user-images.githubusercontent.com/31941637/84361340-20f8b800-ab91-11ea-8d20-178240f651e1.png)

Probably these errors appear due to the quick fix of the first error. I don't know, that's the reason I put them here together.

when I tried to compile this other one appeared

(The number of errors that appear in the console is more than 60)

![image](https://user-images.githubusercontent.com/31941637/84365600-48eb1a00-ab97-11ea-8249-ea2a9f040d76.png)

the project is new, the API level is 22 and the plugin was imported from the package manager, also already reviewed the XR management which is as follows

![image](https://user-images.githubusercontent.com/31941637/84366380-594fc480-ab98-11ea-9faa-44687d3fea60.png)

Thanks and sorry for the English, I'm still not very good

**Comment by npig** [comment]
add iOS build support module to your install. Did you add the dependencies to Assets/Plugins/Android/mainTemplate.gradle?

https://developers.google.com/cardboard/develop/unity/quickstart#publishing_settings

**Comment by jballoffet** [comment]
As @npig pointed out, it seems that the iOS build support module isn’t installed and the Java dependencies are missing in the custom gradle file. Please take a look at #33.

**Comment by LuisAngelGR** [comment]
> agregar el módulo de compatibilidad de compilación de iOS a la instalación. ¿Agredió las dependencias a Assets/Plugins/Android/mainTemplate.gradle?
> 
> https://developers.google.com/cardboard/develop/unity/quickstart#publishing_settings

thanks it worked perfectly
