### ISSUE TITLE
MagicWindow/Cardboard InitializeLoader issue. 

### ISSUE THREAD

**Issue by npig** [googlevr/cardboard#62]
We have a MagicWindow/Cardboard 360 image viewer running on 2019.4. We can build to iOS and Android and the application functions as expected until the XR loader is reinitialized on Android. We've tried two methods of managing the Cardboard XR Plugin, both methods end up causing errors.

- A) 
`
activeLoader.Initialize(); > activeLoader.Start(); > activeLoader.Stop(); > activeLoader.Deinitialize(); > activeLoader.Initialize(); > activeLoader.Start();
`

- B) 
`
activeLoader.Initialize(); > activeLoader.Start(); > activeLoader.Stop(); > activeLoader.Start();
`

_edit: clarified issue._

**Comment by iLyxa3D** [comment]
Same problem with AVPro Video 360 player plugin: 1) camera image freeze on turning off VR Subsystems; 2) app crash on starting any AVPro media player in Cardboard mode.

**Comment by npig** [comment]
On Stop() and Deinitialize() of the plugin, ADB reports that "CardboardXrInputProvider" stops the Lifecycle but report from the CardboardXrDisplayProvider.

[XR] [CardboardXrInputProvider]: Lifecycle stopped
[XR] [CardboardXrInputProvider]: Lifecycle finished

**Comment by npig** [comment]
This could be an issue with Unity - I replaced the Cardboard Unity Plugin with the MockHMDLoader and get the same results.

**Comment by iLyxa3D** [comment]
Rolling back the project version to 2018.3 , removing XR plugins, using legacy XR/Cardboard helped me to start switching on and off on demand without bug.

```
public void VROn()  {
        StartCoroutine(DelayInit());
    }

    IEnumerator DelayInit()
        XRSettings.enabled = true;  //setup vr without visual changes, because no device, just init xr settings 
        yield return new WaitForSeconds(0.5f); //or for the new frame

        if (string.IsNullOrEmpty(XRDevice.model))
        {
            XRSettings.LoadDeviceByName("Cardboard");
            XRDevice.deviceLoaded += EnableVr;  // one more time vr enabling, lead to visual changes on the screen
        }        
    }

    void EnableVr(string text) {
        XRSettings.enabled = true;     
    } 

    public void VROff()  {        
        XRSettings.enabled = false;
    }

```

Not the best solution, but maybe it's just as important for someone to get rid of the bug as quickly as possible.

**Comment by npig** [comment]
iOS : We have working with MagicWindow on Unity 2019.4 . 
Android: We had to roll back to 2019.2.20 and use the old plugin

**Comment by RemyRM** [comment]
> iOS : We have working with MagicWindow on Unity 2019.4 .
> Android: We had to roll back to 2019.2.20 and use the old plugin
> 
> Ran into some unexpected behavior on iPhone 7 (OS 12.4.1)

Do you have Magic Window working on iOS using this plugin, or the older version that is last supported in 2019.4? I have so far been unable to get magic window to work with this version :/

**Comment by npig** [comment]
> Do you have Magic Window working on iOS using this plugin, or the older version that is last supported in 2019.4? I have so far been unable to get magic window to work with this version :/

Yep, We have the new plugin working with 2019.4 on iOS. We had to rollback to the old plugin on Android though.

**Comment by jballoffet** [comment]
This ticket has been labelled as a feature request and we will prioritise it along the others. Bear in mind that we will provide a fix to turn on and off the XRSubsystems in the upcoming release. Please, try it once it is out and let us know if the error persists. Note that both subsystems work together (display and input) and that might affect your use case.

**Comment by agalbachicar-gg** [comment]
We have fixed turning on and off the display and input subsystems at runtime. Issue #53 was tracking that specific bug and we think this will be fixed with the new release. Please do tell us if our assumptions were wrong and reopen this ticket.

**Comment by chaosemer** [comment]
v1.4.0 is out.
