### ISSUE TITLE
Are threre any equivalent "reticle pointer" in this new release?

### ISSUE THREAD

**Issue by ErickSimoes** [googlevr/cardboard#64]
In the previous API, there was a GvrReticlePointer prefab.
In my tests, I realized a implementation of this feature in the CameraPointer script, but that is not visible.
Will this be released soon?

**Comment by darkverse** [comment]
There is XRInteractorReticleVisual but I haven't been able to get it to work. I have been able to get a reticle at the end of a XRInteractorLineVisual but this is not a good solution for a gaze based pointer. There is also IXRCustomReticleProvider.

**Comment by jballoffet** [comment]
This is a duplicate issue, please take a look at #47.

**Comment by ErickSimoes** [comment]
Thanks @jballoffet!
