### ISSUE TITLE
Old version of cardboard unity plugin without uiWebView

### ISSUE THREAD

**Issue by whizzkid** [googlevr/cardboard#66]
Is it possible to get the old google vr sdk/unity plugin where the UIWebview component has been replaced with WKWebview?

We were trying to publish our project when we found out about the UIWebview block on the app store.. Tried to get the new Cardboard SDK / unity XR Plugin working, were now forced to upgrade unity, change to il2cpp etc, and seeing many issues arise with the new open source SDK and features missing that were in the old SDK.  (reticle, testing in editor)

the only thing that was blocking our app was the uiWebview :|

**Comment by jballoffet** [comment]
We are no longer releasing updates to the Google VR SDK. The Cardboard open source project replaces the Google VR SDK for use with Cardboard. We recommend that all developers actively building for Google Cardboard migrate (iOS, Android NDK) to using this new Cardboard SDK.
