### ISSUE TITLE
Backlog/roadmap

### ISSUE THREAD

**Issue by whizzkid** [googlevr/cardboard#67]
Is the roadmap or backlog viewable somewhere? 

There are a couple of issues and missing features in the open source project that are preventing our app from launching. It would be nice if we can see when to (approximately) expect to see when issues are planned to be resolved.

**Comment by xiesi88** [comment]
Yes, we are very anxious to get support. There are too many problems with the current SDK version. My team is developing a set of popular science content based on Cardboard. We really need a stable SDK. thank you very much!

**Comment by daltonbr** [comment]
I am using this other Unity Cardboard SDK, now working in iOS and Android.

It's based on the Google Cardboard API 1.1.0
https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK

**Comment by xiesi88** [comment]
> I am using this other Unity Cardboard SDK, now working in iOS and Android.
> 
> It's based on the Google Cardboard API 1.1.0 and the developer is doing an amazing job!
> https://github.com/mobfishgmbh/Cardboard-VR-Unity-SDK

Looks good, I am testing, thank you very much.

**Comment by chaosemer** [comment]
The project roadmap is available on the
[Projects](https://github.com/googlevr/cardboard/projects/1) page. I'm leaving this issue open for other people until we update our readme in the next release.

**Comment by chaosemer** [comment]
v1.4.0 now points to the Projects page in the readme.
