### ISSUE TITLE
It doesn't support Vulkan and OpenGL 3.2 API.

### ISSUE THREAD

**Issue by fakeeyes** [googlevr/cardboard#69]
It only support OpenGL 2.0 API. Anybody who knows for applying plan of Vulkan and OpenGL 3.2 API in Cardboard VR SDK?

**Comment by Handicap** [comment]
I would like to know this too. The project I'm currently working on depends on OpenGLES3 for AR functionality so downgrading to OpenGLES2 is not an option.

**Comment by jballoffet** [comment]
I’m closing this issue as is partially a duplicate of #40. For the Vulkan feature request, please open a new issue.
