### ISSUE TITLE
How do i control scene in editor? 

### ISSUE THREAD

**Issue by lz7cjc** [googlevr/cardboard#70]
Hi 
I can't find anyone else asking this question so am hoping i am just missing something. 
When I implement the new XR package for Cardboard, I have to delete the old GoogleVR assets to build in XCode on a Mac, otherwise I get loads of errors. 
This means I lose the GVRreticlepointer, the GVREditorEmulator and all the other files I previously used. 

So when I build the app, I don't get the reticlepointer which means I can't choose anything in my game. 
It also means I can't control the scene in play mode

How do i get the same functionality that the old system offered when controlling my scene in both the editor and when i build the app? 
thanks

**Comment by nukadelic** [comment]
I added mouse controls in my case : https://github.com/nukadelic/Unity-Cardboard

**Comment by lz7cjc** [comment]
thanks - i just want to move the camera as the head moves and then use gaze and pick with the reticlepointer. Does your code do that? 

Beyond my capabilities and shocked that this has been emitted from the new package - it was all so easy with the old system!

**Comment by jballoffet** [comment]
As it was explained in #38, Cardboard XR Plugin currently doesn’t support running on the Unity Editor so I’m closing this issue as is partially a duplicate. However, if you want to send changes, please read CONTRIBUTING.md and follow the process. Patches are welcome.
