### ISSUE TITLE
Does this SDK use WKWebView instead of UIWebView for iOS

### ISSUE THREAD

**Issue by MinhazMM** [googlevr/cardboard#71]
Hi there,

I am looking to develop a VR app for both Android and iOS. I kindly would like to know if this SDK has updated the component for iOS to have WKWebView instead of UIWebView.

Thank you

**Comment by friggasaint** [comment]
I don't know if it uses WKWebView but I can verify that it gives no issues with Appstore concerning UIWebView.

**Comment by MinhazMM** [comment]
@friggasaint Amazing. So if I start the development via Unity the VR app shouldn't have any issues when publishing yeah?

**Comment by jballoffet** [comment]
As was said [here](https://github.com/googlevr/cardboard/issues/8#issuecomment-627586485), Cardboard SDK doesn’t use UIWebView. Please let us know if you face any issues related to the SDK when publishing to the App Store.
