### ISSUE TITLE
Is it compatible with Unity 2020 ?

### ISSUE THREAD

**Issue by SRochem** [googlevr/cardboard#72]
Sorry, it might be a stupid question but is the package compatible with Unity 2020 ? 
Is it compatible with 2019.4 ? 
I'm using Unity 2019.3.14f1 and encouter a bug (no related to carboard) that was fixed for 2020 but I'm afraid cardboard con't work.

**Comment by jballoffet** [comment]
We aren’t aware of any issues when running the XR Plugin on Unity 2020 or 2019.4, but we haven’t finished setting up our CI tools to automatically test the package using different Unity versions yet. Please file issues for any bugs you find in 2020.
