### ISSUE TITLE
Uploading to App Store Issue

### ISSUE THREAD

**Issue by TuringFallAsleep** [googlevr/cardboard#74]
I am using Unity to develop a iOS VR app for Google Cardboard. It works fine via the local instalment, but when I try to upload to App Store for further testing. I received this error:

> ITMS-90206: "Invalid Bundle. The Bundle at 'MY_APP_NAME.app/Frameworks/UnityFramework.framework' contains disallowed file 'Frameworks'."

I figured this issue by adding a script in Build Phases for UnityFramework. 
`cd "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/"
if [[ -d "Frameworks" ]]; then 
    rm -fr Frameworks
fi`

Then I could do the uploading process, but I received an email from the App Store indicating that I have this issue: 

> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. 

Then I tried to exam whether I have used UIWebView by entering this script in the Terminal in my project file:
`grep -r UIWebView .` 
And I received this, indicating GVRSDK is using UIWebView rather than WKWebView: 
> Binary file ./Plugins/iOS/GVRSDK/Pods/GVRSDK/Libraries/libGVRSDK.a matches

Is this means currently, we couldn't upload our Google Cardboard app to the App Store? Or, if possible, how do I upload my VR app to the App Store? 

I am very nervous about it because this is an essential part of my MSc Project experiment, and it has already taken me almost a week to deal with this problem. Thank you for your help.

**Comment by friggasaint** [comment]
You are sure you have removed the old Plugin for your iOS build from package manager?
I'm specifically talking about the packages Google VR Android and Google VR iOS.

**Comment by TuringFallAsleep** [comment]
I haven't had the chance to try out Google VR Android. All my tools are newly installed. My Google VR iOS version is 2.0.1 on Unity. Is this the newest version?

**Comment by friggasaint** [comment]
You should completely remove Google VR iOS since it is deprecated for Appstore and instead use the new plugin which facilitates the Unity XR Framework.
https://developers.google.com/cardboard/develop/unity/quickstart

**Comment by TuringFallAsleep** [comment]
Thank you for your help. But after I tried the new Plugin in unity and export it to the Xcode, I received following errors when I was building the project. Do you have any ideas about it? 
<img width="222" alt="Screen Shot 2020-07-08 at 3 50 47 AM" src="https://user-images.githubusercontent.com/24510956/86835249-6516a400-c0ce-11ea-8895-5a505aeb4564.png">

**Comment by friggasaint** [comment]
That is not exactly an error message. All the errors are pretty much cut off. Dunno how anybody can help you with that.
If the errors say that the methods are reference twice you sill have to remove the old Google VR package(s).
Also check if you followed the quickstart guide correctly.

**Comment by TuringFallAsleep** [comment]
I followed exactly the methods on the website and even the player settings. However, the unity build does not generate a *.xcworkspace file. Then I used *.xcodeproj to build an iOS app, then a similar error happens. If I use xcode to build for the first time, only one error 
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
If I build it again the error will be something like the up-mentioned image.

I suppose the problem is why I change the new plugin, the *.xcworkspace cannot be generated?

**Comment by JacobBWaggoner** [comment]
@TuringFallAsleep have you had any luck with this? I now have fairly successful builds on the Android side, but am running into the same issues. When I build without removing everything, I can make it to xCode, but I am informed of conflicting files with the new plugin. If I remove everything and build, I can't get a Workspace file, and can't get the arm64 build to complete.

**Comment by jballoffet** [comment]
@TuringFallAsleep, based on your last comment, it seems the package you are using doesn’t include the SDK binary in it. I’d recommend that you take a look at the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart) for instructions on how the package should be included, and to check if the sample app works for you.

**Comment by JacobBWaggoner** [comment]
I know that this was just labeled as closed, but I found the issue on our end! We still had old Google VR files in the project that were causing a conflict. Removing them allowed the project to build and run on iOS.
