### ISSUE TITLE
Objects invisible on iOS build when in VR 

### ISSUE THREAD

**Issue by darkverse** [googlevr/cardboard#75]
Hi,

I have an app that starts in non-VR more and allows the user to select VR or magic window. On Android everything is fine, both VR and magic window work. However on an iOS build many of the objects become invisible (including a standard terrain with the default terrain material) when in VR mode but they are visible when in magic window mode. Is there some additional step to take to make sure all shaders are available to the XR plugin? I don't understand why they work when in magic window mode but not when the XR subsystem is loaded.

I am using Unity 2019.4.0f1, OPENGLES2, Gamma color space, .NET4.x api.

**Comment by darkverse** [comment]
Update on investigations. Apparently it has something to do with render queues and background. If I have a skybox (even the default skybox) then it is rendered on top of most objects (not all) making them invisible. If I remove the skybox then the objects are visible. I am investigating this lead further.

**Comment by darkverse** [comment]
I believe it is a problem with the depth buffer being reversed. When the XR subsystem is not running and I am in magic window mode everything renders correctly. When the XR subsystem is started the depth buffer is reversed causing objects to be drawn in the reverse order, ie the skybox is drawn last on top of everything (except transparent objects). 

Is there a way to workaround this? perhaps an API call to reverse the depth buffer that I can call after starting the subsystem?

**Comment by darkverse** [comment]
Ok, it is not that Z-direction is being reversed. I hacked into the projection matrix and flipped the z-direction but then everything disappeared (which is understandable). So it is some sort of problem writing the depth buffer when in VR. Is anyone else seeing this? Has anyone got a build to iOS with a skybox working?
If I have a simple scene with a default skybox and a default terrain then the skybox is rendered over the terrain making it seem invisible. I tried copying the standard skybox shader and creating a new shader and changing the render queue to geometry-999 and render type to opaque but that made no difference.

**Comment by darkverse** [comment]
Ok, I have solved the problem, or rather got a workaround.
In researching it I saw references to problems with the depth buffer if these three factors were in play: iOS+GrabPass+MSAA. I was using MSAA so I turned it off and the scene now renders correctly, so presumably the rendering when VR is enabled includes a GrabPass (or it is a different issue). In any event disabling anti-aliasing worked for me.

**Comment by JoaoBorks** [comment]
@jballoffet I just discovered this issue and had to turn MSAA off on my camera as well. Will the system support MSAA in the following updates? Or is it purposely not supported?

**Comment by jhclaura** [comment]
> Ok, I have solved the problem, or rather got a workaround.
> In researching it I saw references to problems with the depth buffer if these three factors were in play: iOS+GrabPass+MSAA. I was using MSAA so I turned it off and the scene now renders correctly, so presumably the rendering when VR is enabled includes a GrabPass (or it is a different issue). In any event disabling anti-aliasing worked for me.

I also have an same issue, VR + iOS + skybox + anti aliasing cause everything invisible except the skybox. It's rendering normally in magic window mode. Is there a way to fix it?

**Comment by darkverse** [comment]
The only way I found to "fix" it was to turn off anti-aliasing. I am starting to work on an update to my project so I will revisit it and see. I do not know why this issue was closed if it is still an open bug. @jballoffet was this closed because it was fixed or because it was identified as a bug??
