### ISSUE TITLE
Cannot build sample app with default Gradle bundled with Unity 2019.3.15f1.

### ISSUE THREAD

**Issue by chengnay** [googlevr/cardboard#80]
I was trying to build with Google Cardboard XR Plugin, but I get below errors.

1.	When I uncheck “Gradle Installed with Unity” from External Tools,
![image](https://user-images.githubusercontent.com/33050705/88247963-2853cb00-ccd2-11ea-90c5-9fedfb3b451c.png)

2.	When I check “Gradle Installed with Unity” from External Tools,
![image](https://user-images.githubusercontent.com/33050705/88248034-5a652d00-ccd2-11ea-810e-197c7c86716f.png)
![image](https://user-images.githubusercontent.com/33050705/88248061-723cb100-ccd2-11ea-9a8b-93ce20603a7c.png)

I am using Unity 2019.3.15f1, does anyone know how to resolve the above errors?

**Comment by robibkuiper** [comment]
You might need to add these lines 

`  implementation 'com.android.support:appcompat-v7:28.0.0'
  implementation 'com.android.support:support-v4:28.0.0'
  implementation 'com.google.android.gms:play-services-vision:15.0.2'
  implementation 'com.google.protobuf:protobuf-lite:3.0.0'` 

in the dependencies part of your gradle template. thetemplate can be found in Plugins/Android if you checked "custom main gradle template" in the player settings of unit

**Comment by chengnay** [comment]
New error occurs after I added above lines,
[gradle.txt](https://github.com/googlevr/cardboard/files/4964512/gradle.txt)

**Comment by jballoffet** [comment]
Based on your comment, it seems there are some Gradle dependencies missing. I recommend that you take a look at the [quickstart](https://developers.google.com/cardboard/develop/unity/quickstart) for instructions on how the custom Gradle file should be configured and to check if the sample scene works for you. I also recommend using the “Gradle installed with Unity” option.

**Comment by Oluwatosin-Ogunyebi** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/49772680/94798653-d28a5600-03d9-11eb-98e0-7cfeaa1680d1.png)
![Screenshot (47)](https://user-images.githubusercontent.com/49772680/94798660-d4ecb000-03d9-11eb-8529-e1ec3415d36d.png)
![Screenshot (46)](https://user-images.githubusercontent.com/49772680/94798669-d61ddd00-03d9-11eb-9c6b-080046ba0815.png)
I keep getting errors after adding the dependencies. Any help? @jballoffet @chengnay

**Comment by jballoffet** [comment]
It seems it is related to the fact that Cardboard SDK still uses Gradle 3.4 and you are using Gradle 5.1. It has been prioritised for the next release to bump the Gradle version. In case you can downgrade it, please do so for the time being.

**Comment by chaosemer** [comment]
This was fixed in v1.4.0.
