### ISSUE TITLE
carboard can not build in xcode

### ISSUE THREAD

**Issue by liuqun199211** [googlevr/cardboard#82]
duplicate symbol '_OBJC_IVAR_$_CardboardQRScanViewController._showingHUDMessage' in:
    /Libraries/com.google.xr.cardboard/Runtime/iOS/arm64/CardboardXrProvider.a(qr_scan_view_controller_ced8551fbfbac309fbbe25b74b186b4f.o)
/Libraries/com.google.xr.cardboard/Runtime/iOS/libsdk.a(qr_scan_view_controller_ced8551fbfbac309fbbe25b74b186b4f.o)
ld: 27 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I created a new empty project of unity, and then imported the cardboard plug-in according to the steps in the document. However, during the build process in Xcode, this error occurred. How should I solve this problem?

**Comment by jballoffet** [comment]
This issue should be solved on v1.2.0 (to be released very soon) as we have merged both the SDK and XR Provider into one single library (.a). Furthermore, release v1.2.0 also will include the XR Provider source code, which makes it possible for you to rebuild the binaries from source if needed.

**Comment by chaosemer** [comment]
With 1.2.0 out, this is now resolved.
