### ISSUE TITLE
After add new obj in Demo Code screen is getting black

### ISSUE THREAD

**Issue by umarmansuri** [googlevr/cardboard#85]
Hi Team,

I run the demo code successfully but when I add/replace another obj file from QuadeShpere.obj with Boy character I am getting black screen only.

**I am new to learn VR and C/C++ So can you please suggest some basic steps on how to achieve**

**Comment by jballoffet** [comment]
Could you please provide a link to a Unity project where this issue is shown in order for me to test it? Please also provide the required steps to expose the issue.

**Comment by chaosemer** [comment]
Without a repro project, we can not help here.

If you are still having this issue, please reopen and point us to a repro project with steps to reproduce.
