### ISSUE TITLE
QRCode doesn't recognize "URL" codes when scanning params

### ISSUE THREAD

**Issue by SupernaviX** [googlevr/cardboard#89]
Hi,

I'm trying to develop with the Android NDK Cardboard API, and I'm running into issues scanning the code to my new headset (http://goo.gl/R2gCV1, if it helps). When I try to scan it, I get an "Invalid QR Code" popup.

Debugging the code, I see that the [QrCodeContentProcessor](https://github.com/googlevr/cardboard/blob/ec0fff2d7e2d82a6df79952d67e0e6a0bf740531/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/QrCodeContentProcessor.java#L138) only accepts barcodes of type `Barcode.TEXT`. My parameters are coming back as `Barcode.URL` (and they are indeed a URL, and the rest of this code is expecting a URL), so the scanner won't accept them.

This check seems faulty; is there a reason it was added? Would it be right to change it to `Barcode.URL`, or would that break someone else?

**Comment by jballoffet** [comment]
Thanks for reporting this issue. We just submitted a fix for this and it will be included in the next release.

**Comment by chaosemer** [comment]
This was fixed in v1.3.0.
