### ISSUE TITLE
Does not compile using Android Studio 3.5.2

### ISSUE THREAD

**Issue by Consti10** [googlevr/cardboard#9]
Hello,
For me building a direct download of the source code did not work immediately with android studio.
(Message: libcardboard_api.so is missing)

This is probably due to the fact that the project is still configured to use the 'extractNDK' gradle task, but since all sources are now available (and we might want to modify them) I don't think thats necessary anymore.

Here are my fixes, requires only changes to CMakeLists.txt files:

In sdk/CMakeLists.txt, add
```
set_target_properties(cardboard_api
        PROPERTIES
        LIBRARY_OUTPUT_DIRECTORY "../../../../my_cardboard_api_output_lib/${ANDROID_ABI}")
```

To the bottom, this will create a new folder with the .so files.

We also have to link the sources and the cardboard_api.so file(s) in the hellocardboard-android project, therefore change its CMakeLists.txt following (whole file):

```
cmake_minimum_required(VERSION 3.4.1)

# Standard Android dependencies
find_library(android-lib android)
find_library(EGL-lib EGL)
find_library(GLESv2-lib GLESv2)
find_library(log-lib log)

#set(libs_dir ${CMAKE_CURRENT_SOURCE_DIR}/libraries)
set(libs_dir ${CMAKE_CURRENT_SOURCE_DIR}/../sdk/)

# === Cardboard Sample ===
# Sources
file(GLOB native_srcs "src/main/jni/*.cc")
# Output binary
add_library(cardboard_jni SHARED ${native_srcs})
# Includes
#target_include_directories(cardboard_jni PRIVATE ${libs_dir})
target_include_directories(cardboard_jni PRIVATE ${libs_dir}/include/)
# Build
target_link_libraries(cardboard_jni
    ${android-lib}
    ${EGL-lib}
    ${GLESv2-lib}
    ${log-lib}
    #${libs_dir}/jni/${ANDROID_ABI}/libcardboard_api.so)
    ${libs_dir}/my_cardboard_api_output_lib/${ANDROID_ABI}/libcardboard_api.so)
```

**Comment by Consti10** [comment]
Here is the (forked) source code on Github, with the described changes from above:
https://github.com/Consti10/cardboard

**Comment by jballoffet** [comment]
Thank you for reporting this. Hello Cardboard sample app depends on the AAR generated by the SDK compilation. Consequently, you need to generate the bundle to feed the Hello Cardboard sample app first. Consider revisiting step 6 from the [build instructions](http://developers.google.com/cardboard/develop/c/quickstart#download_and_build_the_demo_app). The 'extractNDK' gradle task is still used to show how to use the Cardboard SDK as an AAR package and not being forced to add the entire source code as a build dependency in other projects.

**Comment by Consti10** [comment]
For everyone who wants to play with the cardboard source code itself:
See [https://github.com/Consti10/cardboard/tree/415403d2684eaa78b44e632561357ad1f9836087](url)
Else, jballoffet said everything.
