### ISSUE TITLE
Cardboard XR on iOS Screen.orientation change Issue!!

### ISSUE THREAD

**Issue by UnityKR** [googlevr/cardboard#94]
Unity 2019.4.5f1
Google Cardboard XR Plugin for Unity v1.1.0 (2020-05-18)
iPhone 11
iOS 13.2.3

Build Settings

<img width="580" alt="Settings-orientation" src="https://user-images.githubusercontent.com/46150621/89869516-69633f00-dbef-11ea-830c-e48ddf7bcb70.png">

void Start()
{
            Screen.autorotateToPortrait = false;
            Screen.autorotateToPortraitUpsideDown = false;

            Screen.autorotateToLandscapeLeft = true;
            Screen.autorotateToLandscapeRight = true;

            Screen.orientation = ScreenOrientation.AutoRotation;
}

iPhone Run..

Then,
HelloCardboard Scene

LandscapeLeft is working correctly
but,
LandscapeRight is not working ( Turned Over )

How to fix it.

and

How to Camera Recenter.

**Comment by RossMck** [comment]
For camera recenter you can  turn vr on and off or create a object that you put everything in the scene into apart from the player and rotate that object.

typically you don't allow auto rotation in vr as it can't be good for the user to experience that in vr. Why are you wanting auto rotation ?

**Comment by jballoffet** [comment]
Currently, the Cardboard SDK and XR Plugin only supports LandscapeLeft orientation, and supporting other orientations will not be supported as it would not behave well in VR. If you want to use other rotations outside of VR, make sure to programmatically lock the orientation to LandscapeLeft before entering VR.

**Comment by UnityKR** [comment]
Thank you.
