### ISSUE TITLE
Unity iOS Cardboard XR : Hybrid Guide

### ISSUE THREAD

**Issue by UnityKR** [googlevr/cardboard#95]
I need help like this article for Cardboard XR

https://developers.google.com/vr/develop/unity/guides/hybrid-apps

how to implement..

**Comment by jballoffet** [comment]
Cardboard XR Plugin is a Unity XR Provider and its lifecycle is directly managed by Unity's XR Management package. I recommend you to take a look at https://docs.unity3d.com/Packages/com.unity.xr.management@3.2/manual/index.html for further information about this topic.
