### ISSUE TITLE
Unity Android. 3 cameras setup: Both Left/Right target eye rendered into left half of the screen

### ISSUE THREAD

**Issue by pppedrillo** [googlevr/cardboard#97]
Unity 2019.4.0f1

When you have 3 cameras in the scene 2 for each target eye and 1 for "both" target eye, "Both" target eye camera rendered OK in both halves of the screen, no camera for "Left" is visible but in that place sdk renders "Right" eye camera (left half of the screen).

Steps to repro:
1. Create new scene in Unity
2. Create plane and place it in front of the camera.
3. Create 2 extra layers "Left" and "Right"
4. Create cube and assign it to the "Left" layer
5. Create sphere and assign it to the "Right" layer
6. Configure Main camera "Culling mask " to render everything except   "Left" and "Right" layers
7. Ensure Main Camera has "Target eye" set to "Both"
8. Add new camera to the scene, call it "Left", change "Clear flags" to "Depth only" and its "Culling mask " to render only "Left" layer
9. Add new camera to the scene, call it "Right", change "Clear flags" to "Depth only" and its "Culling mask " to render only "Right" layer
10. Add "Tracked Pose Driver" component to **each** camera
11. For **each** camera : In "Tracked Pose Driver" change "Tracking Type" to "Rotation Only"
12. Build and run on the Android phone

Observe:
Main camera (with  "Target eye" == "Both") correctly rendered in both halves of the screen.
"Left" camera is not rendered and all (or, maybe gets overridden later with the output of "Right" camera???)
"Right" camera rendered ok but into wrong (left) half of the screen.
You'll see a plane in both halves of the screen and a sphere in the left half of the screen, no cube appears.

Investigations:
1. Try to disable "Right" camera in the scene.
2. Build and run on Android.
Observe:
Main camera (with  "Target eye" == "Both") correctly rendered in both halves of the screen. (As before)
"Left" camera now **rendered correctly** into left half of the screen !

I attached a test scene.
[cardboard_wrong_3cams.zip](https://github.com/googlevr/cardboard/files/5113595/cardboard_wrong_3cams.zip)

**Comment by andrewio** [comment]
Same issue (same image for different eyes) with 2 cameras for Both Eyes with different clear flags: Depth Only & Solid Color.
Env: Unity 2019.4.10, Android 10, Galaxy A71.

**Comment by dletozeun** [comment]
Hi,

I have a similar issue with a simpler issue. Just duplicating the camera in the sample scene and making one at left target eye and the other as right target eye doesn't work. Only the left half of the screen is rendered, the right camera renders black.

In my particular case, I need 2 cameras one for each eye to be able to render stereoscopic videos with the left camera rendering the left eye video screen and the right camera rendering the right video screen using Unity layers mechanism. This used to work before with the GoogleVR SDK.

Any pointers on how to fix this please?

**Comment by jballoffet** [comment]
Sorry for the long delay here. Thank you for the repro project, I’ve been able to reproduce the reported issue. Per [Unity documentation](https://docs.unity3d.com/ScriptReference/Camera-stereoTargetEye.html), the option TargetEye in the Camera game object is used by the built-in Virtual Reality mode (deprecated according to Unity documentation) instead of an external XR plugin (like the Cardboard XR Plugin). For rendering different stuff to each eye, please see #146.
